### ISSUE TITLE
If our project not support composer, how can we use pinpoint_php agent of version 0.2.x?

### ISSUE THREAD

**Issue by EyelynSu** [pinpoint-apm/pinpoint-c-agent#103]

**Comment by eeliu** [comment]
The AOP library implementation base on php classloader. If no classloader, it cant be done.
While, we were trying to find other way to support application without classloader.
The bad news is not found any efficiency and none-intrusive way to support AOP in PHP.

> If somebody found it, please let us know. 

Thanks
