### ISSUE TITLE
the pdo plugins reports 502 

### ISSUE THREAD

**Issue by linuxmyjob** [pinpoint-apm/pinpoint-c-agent#114]
hello,i write a plugin of pdo,but when i requests my php scripts that connect mysql and do query ,it reports 502
the pdo plugin:

[pdo_plugin_php.txt](https://github.com/naver/pinpoint-c-agent/files/3508708/pdo_plugin_php.txt)
the mysql test scripts:
![image](https://user-images.githubusercontent.com/8079815/63156924-6408fe00-c048-11e9-844e-24cdf6199db7.png)
when i set exit in onBefore or onend function of query,it dose not reports 502 and when i test   
it sometimes go to the onBefore function and sometimes dose not .i guess it is sample according the request couns. but why it is go to the query  onBefore and onend functinon then reports 502.

**Comment by eeliu** [comment]
@linuxmyjob 
hi, I find you add some checking
``` php 
if (empty($data['args'][0])) {
            return ;
        }
```
on `onEnd`, `onBefore`. The before and end must be matched: A before must have a end.

By the way, https://github.com/naver/pinpoint-c-agent/releases/tag/v0.2.0 had released. This version could be more easy and efficient. Hope you use our new version.

**Comment by linuxmyjob** [comment]
@eeliu The checking code cut off the onBefore and onEnd that it is your idea? where the checking code shuld be place?
The version 2.0 i had look at,but we use php5.6 can not use it .

**Comment by eeliu** [comment]
@linuxmyjob 
if you cut off the before , the end should be cut off too.

**Comment by linuxmyjob** [comment]
@eeliu hello,i had deleted the checking code,it is also reports 502 how can i debug it and find the problem?

**Comment by eeliu** [comment]
@linuxmyjob 

The 502 means the php-fpm is crash, you can use gdb to attached it, or enable crash dump on you server.

If you catch it, post the crash stack information to us.
 Sorry to let your server crash.

> Note: v0.1.x not support zts

**Comment by linuxmyjob** [comment]
@linuxmyjob i will catch it according to you later,but i have a problem that the hole php-fpm is not crash  i can request  the other uri and it is ok. i had saw the php-fpm log and it is:
![image](https://user-images.githubusercontent.com/8079815/63238269-31454c80-c278-11e9-8edb-0ff5a0e49a47.png)

**Comment by linuxmyjob** [comment]
@eeliu 
the crash stack 

[core.7447.txt.zip](https://github.com/naver/pinpoint-c-agent/files/3518269/core.7447.txt.zip)
[core.7452.txt.zip](https://github.com/naver/pinpoint-c-agent/files/3518270/core.7452.txt.zip)
and the error:
![image](https://user-images.githubusercontent.com/8079815/63311042-7b3d3980-c32f-11e9-8e32-584e4d43dd14.png)
the stack trace
![image](https://user-images.githubusercontent.com/8079815/63311061-8ee8a000-c32f-11e9-9617-59b021c80646.png)

**Comment by eeliu** [comment]
@linuxmyjob
Nice catch! 
This catch was very wired, PhpInfoInterceptor::onEnd does not call any GC.
Could you attach the script when php-fpm crash?

**Comment by linuxmyjob** [comment]
@eeliu   i dot understand about your idea.Could you explain it?

**Comment by eeliu** [comment]
@linuxmyjob 
Hard to debug is the v0.1.x's drawback.
I cannt locate the problem in the crash stack, due to fail to reproduce crash.
 Can you help me about how tho reproduce this crash？

**Comment by linuxmyjob** [comment]
@eeliu what can i do netx? gdb my scripts of mysql ?

**Comment by linuxmyjob** [comment]
@eeliu when i test i find key problem  the php-fpm log :
![image](https://user-images.githubusercontent.com/8079815/63342574-69cf4e00-c37e-11e9-973e-369825757b84.png)
is it usefull ?

**Comment by linuxmyjob** [comment]
@eeliu 能加你qq或者微信吗，我特别想解决这个问题。您让我帮您重现这个crash ,我没明白您的意思

**Comment by eeliu** [comment]
@linuxmyjob 
I'm checking your PDO plugins, pls wait for some time.

**Comment by EyelynSu** [comment]
@linuxmyjob 
Could you send us all the files you use?
I have tried your plugin, no crash on our enviroment.

**Comment by linuxmyjob** [comment]
@eeliu 
how do you test ? 
my test method:
 for i in {1..500};do curl -I http://qa.megatron.baidu-shucheng.com/con_mysql.php;done
it will reports 502  after about on thousand request  . I found a situation that the interceptor  is sampled ,it needs reuested many times and can intercept the pdo function such as query. i guess it is not trigger the pdo plugins because of the little requests. 
the plugins_create.php：
[plugins_create.php.zip](https://github.com/naver/pinpoint-c-agent/files/3528693/plugins_create.php.zip)
the pinpoint_agent.conf:
[pinpoint_agent.conf 3.zip](https://github.com/naver/pinpoint-c-agent/files/3528702/pinpoint_agent.conf.3.zip)

[pinpoint_agent.conf 3.zip](https://github.com/naver/pinpoint-c-agent/files/3528697/pinpoint_agent.conf.3.zip)
the php.ini:
[php.ini 2.zip](https://github.com/naver/pinpoint-c-agent/files/3528715/php.ini.2.zip)
the pdo test script:
[con_mysql.php.zip](https://github.com/naver/pinpoint-c-agent/files/3528726/con_mysql.php.zip)
the pdo plugins:
[pdo_plugin_php.txt](https://github.com/naver/pinpoint-c-agent/files/3528731/pdo_plugin_php.txt)

the demesg log :
![image](https://user-images.githubusercontent.com/8079815/63493471-44615200-c4ee-11e9-9eda-733556830e38.png)
the php-fpm log:
![image](https://user-images.githubusercontent.com/8079815/63493512-6064f380-c4ee-11e9-9207-ec517aea50d3.png)

**Comment by eeliu** [comment]
@linuxmyjob 

You give us a difficult problem!

This our test result 

![image](https://user-images.githubusercontent.com/27064129/63503854-e0955400-c502-11e9-9332-0ab9c5dd7f7b.png)

php-fpm output

```
[test@pinpoint_alpha ~]$ php-fpm -F
[22-Aug-2019 05:21:09] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[22-Aug-2019 05:21:09] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[22-Aug-2019 05:21:09] NOTICE: fpm is running, pid 26857
[22-Aug-2019 05:21:09] NOTICE: ready to handle connections
[22-Aug-2019 05:21:18] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
```

I can't find any crash !

By the way, dose you php support zts?

**Comment by linuxmyjob** [comment]
@eeliu we do not support :
Thread Safety => disabled

**Comment by EyelynSu** [comment]
@linuxmyjob 
I tried with your script, still no crash.
![1566548169](https://user-images.githubusercontent.com/41946743/63577770-beaed680-c5c1-11e9-82c7-6ebdd8d3da45.png)
![1566548269](https://user-images.githubusercontent.com/41946743/63577771-beaed680-c5c1-11e9-8ea3-73a4150597f9.png)

**Comment by linuxmyjob** [comment]
@EyelynSu 
i change my enviornment but the it also 
reports 502 .Do you delete 'exit' in pdo_plugin_php.txt.you no crash because of the pdo_plugin_php  has 'exit'.please use the plugin:
[pdo_plugin.txt](https://github.com/naver/pinpoint-c-agent/files/3544695/pdo_plugin.txt)
@EyelynSu @eeliu  please help me, it had the crash problem indeed.

**Comment by eeliu** [comment]
@linuxmyjob 
Can you create a temporary repository about your code and share it to us. 
We tested it with your attachment.

**Comment by linuxmyjob** [comment]
@eeliu how do i share it to you ?

**Comment by eeliu** [comment]
@linuxmyjob 
By github

**Comment by linuxmyjob** [comment]
@eeliu  你好，请问能加您微信或qq 沟通下吗？我不太了解您的意思

**Comment by eeliu** [comment]
@linuxmyjob 
Comments history could help anyone who has the same problems.

**Comment by linuxmyjob** [comment]
我环境和代码没任何特殊，我将我php 版本，php.ini php-fpm.conf,pinpoint_agent.conf,pinpoint-c-agent 版本，pdo_plugin.php 插件，plugins_create.php 都打包发给您？

**Comment by eeliu** [comment]
@linuxmyjob 
Please attach these here!

**Comment by linuxmyjob** [comment]
@eeliu 
my test metod:
for i in {1..2000};do curl http://test.zongheng.com/con_mysql.php;done
the php version:
PHP 5.6.27 (cli) (built: Aug 26 2019 13:06:33) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
the nginx version:
nginx version: nginx/1.12.2
the pinpoint-c-agent version:
pinpoint-c-agent-0.1.1rc1
boost_1_63
thrift-0.11.0
my conf:
[pdo_502.tar.gz](https://github.com/naver/pinpoint-c-agent/files/3545305/pdo_502.tar.gz)

**Comment by linuxmyjob** [comment]
@eeliu it is ok that  the file i offered?

**Comment by eeliu** [comment]
@linuxmyjob 

You can enter this room!
https://gitter.im/naver/pinpoint-c-agent?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by EyelynSu** [comment]
@linuxmyjob @eeliu 

Using the script and config files in pdo_502.tar.gz, still no crash.
![1566972596](https://user-images.githubusercontent.com/41946743/63830027-a4983e00-c99d-11e9-82d7-701b20f83566.png)

**Comment by linuxmyjob** [comment]
@eeliu do you find the problem?

**Comment by eeliu** [comment]
not yet!
