### ISSUE TITLE
Building Pinpoint on centos6.9 and php 5.6.34

### ISSUE THREAD

**Issue by amangupta0297** [pinpoint-apm/pinpoint-c-agent#115]
Hi @ll,

has anyone build pinpoint on centos6 and php5.6.34 

I have update few packages automake-1.11 to 1.4, autoconf-2.63 to 2.69 and bison2.4 to 2.6

all other packages are already updated w.r.t centos6

but seems issue with compiling thrift, it gives below error 
>>>>>>>>>>>>>>>
 ./configure: line 17535: syntax error near unexpected token `QT,'
./configure: line 17535: `    PKG_CHECK_MODULES(QT, QtCore &gt;= 4.3, QtNetwork &gt;= 4.3, have_qt=yes, have_qt=no)'
>>>>>>>>>>>>>>>

If anyone has any idea how to build this, please suggest.

**Just an FYI: updated gcc4.7 to 4.9 and shell version from 4.1.2 to 4.2**
Thanks in advance.

**Comment by eeliu** [comment]
Hi, php 5.6 is end of it's life. If you use php7.1+, I recommended you use v0.2.0. More easy to use, debug and deployment.

 https://www.php.net/supported-versions.php

**Comment by amangupta0297** [comment]
Hi @eeliu, thanks for quick revert.

But my concern is centos6 not php5.6
As i have build the pinpoint for centos7 and php5.6.34. Which is suucessful.
But issue seems with centos6. 
Any help would be highly appreciated.

**Comment by eeliu** [comment]
@amangupta0297

From my experience , you can check the gcc and QT version.  
The more, disabled QT is a choise.

**Comment by eeliu** [comment]
@amangupta0297

Hi,did you application use composer?

**Comment by amangupta0297** [comment]
No.
