### ISSUE TITLE
Warning: PHP Startup : Unable to load dynamic library /../pinpoint.so: undefined symbol: ....

### ISSUE THREAD

**Issue by pin4562** [pinpoint-apm/pinpoint-c-agent#140]
# Expected Behavior

> start pinpoint_c_agent

# Current Behavior

> error when run './Build.sh' in '/pinpoint_c_agent/pinpoint_php'

# Failure Information (for bugs)

PHP Warning:  PHP Startup: Unable to load dynamic library '/pinpoint-c-agent/pinpoint_php/modules/pinpoint.so' - /pinpoint-c-agent/pinpoint_php/modules/pinpoint.so: undefined symbol: _ZN8Pinpoint5Agent13UdpDataSender16MAX_REFRESH_MSECE in Unknown on line 0

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1 Checking phpize path
 find / -name phpize
/usr/bin/phpize
export PATH=/usr/bin/phpize:$PATH)
 echo $PATH
/usr/bin/phpize:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

2. step 2 Specifying BOOST and THRIFT path
 find / -name boost
/usr/include/boost
 find / -name thrift
/usr/local/include/thrift

 export WITH_BOOST_PATH='/usr/include'
 export WITH_THRIFT_PATH='/usr/local/include'
 
3.step 3 Run ./Build.sh --enable-debug --always-make && make install
 cd /pinpoint-c-agent/pinpoint_php
./Build.sh --enable-debug --always-make && make install

result:

Build complete.
Don't forget to run 'make test'.

Installing shared extensions:     /usr/lib64/php/modules/

Build complete.
Don't forget to run 'make test'.

libgcc_s.so.1 must be installed for pthread_cancel to work
libgcc_s.so.1 must be installed for pthread_cancel to work
PHP Warning:  PHP Startup: Unable to load dynamic library '/pinpoint-c-agent/pinpoint_php/modules/pinpoint.so' - /pinpoint-c-agent/pinpoint_php/modules/pinpoint.so: undefined symbol: _ZN8Pinpoint5Agent13UdpDataSender16MAX_REFRESH_MSECE in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/pinpoint-c-agent/pinpoint_php/modules/pinpoint.so' - /pinpoint-c-agent/pinpoint_php/modules/pinpoint.so: undefined symbol: _ZN8Pinpoint5Agent13UdpDataSender16MAX_REFRESH_MSECE in Unknown on line 0

PHP         : /usr/bin/php 
Warning: PHP Startup: Unable to load dynamic library '/pinpoint-c-agent/pinpoint_php/modules/pinpoint.so' - /pinpoint-c-agent/pinpoint_php/modules/pinpoint.so: undefined symbol: _ZN8Pinpoint5Agent13UdpDataSender16MAX_REFRESH_MSECE in Unknown on line 0

PHP_SAPI    : cli
PHP_VERSION : 5.4.16
ZEND_VERSION: 2.4.0
PHP_OS      : Linux - Linux PHP 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64
INI actual  : /pinpoint-c-agent/pinpoint_php/tmp-php.ini
More .INIs  :  
CWD         : /pinpoint-c-agent/pinpoint_php
Extra dirs  : 
VALGRIND    : Not used

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: CentOS7.7.1908

* PHP Version: 5.4.16

* php.ini: 
[pinpoint]
extension=/usr/lib64/php/modules/pinpoint.so
pinpoint_agent.trace_exception=true
pinpoint_agent.config_full_name=/pinpoint-c-agent/quickstart/config/pinpoint_agent.conf:1

* php-fpm or apache:
php-fpm: unmodified
apache: 2.4.6

* pinpoint_agent.conf:
entID=php_pinpoint
ApplicationName=PHPApplication

 collector ip address
CollectorSpanIp=127.0.0.1
CollectorSpanPort=9996
CollectorStatIp=127.0.0.1
CollectorStatPort=9995
CollectorTcpIp=127.0.0.1
CollectorTcpPort=9994

TraceLimit = -1
SkipTraceTime = -1
 DEBUG|INFO|WARN|ERROR
PPLogLevel = DEBUG
LogFileRootPath = /data/log
 AgentType -> NGINX | APACHE |PHP |TEST
AgentType="PHP"

 plugin
 PhpInternalFunctionsPlugin
PluginExclude = ExcludePlugin
PluginInclude = PhpRequestPlugin;QuickStartPlugin  ; PhpInternalFunctionsPlugin ;ExcludePlugin ;PDOPlugin;CurlPlugin;

[PHP]
PluginEntryFile=plugins_create.php
PluginRootDir=/pinpoint-c-agent/quickstart/php/web/plugins

*boost 1.71.0

*thrift 0.11.0

*pinpoint_c_agent 0.1.0

How can I fix this error?

**Comment by eeliu** [comment]
I recommended you update to v0.2.0(easy to deployment and faster)

```
....
libgcc_s.so.1 must be installed for pthread_cancel to work
... 
```

You did not make it right.

**Comment by pin4562** [comment]
I already installed libgcc_s.so.1

find / -name libgcc_s.so.1

/usr/lib64/libgcc_s.so.1
/lib/libgcc_s.so.1

Do I have to change paths?
