### ISSUE TITLE
PHP agent not bind . undefined symbol: zval_used_for_init)) in Unknown

### ISSUE THREAD

**Issue by VidushaZ** [pinpoint-apm/pinpoint-c-agent#164]
Hi All, 

Version
-------
**PHP 5.4.16
Zend Engine v2.4.0
gcc version 4.8.5
pinpoint 2.0 RC3
php-agent 0.1.0**

I've tried to monitor my php application on apache2 (4) by using pinpoint C agent v0.1.0 since v0.2.0 not support to PHP 5.4.
I've clean built the agent and deployed the pinpoint.so. 
here is my php.ini and agent configuration 

php.ini
-------
**extension=pinpoint
pinpoint_agent.trace_exception=true
pinpoint_agent.config_full_name=/opt/pinpoint-php-5-agent/agent.conf
log_errors = On
error_log = "/opt/pinpoint-php-5-agent/logs/php.error.log"**

agent.conf
----------
**[common]
AgentID=test
ApplicationName=test
CollectorSpanIp=172.26.32.111
CollectorSpanPort=9996
CollectorStatIp=172.26.32.111
CollectorStatPort=9995
CollectorTcpIp=172.26.32.111
CollectorTcpPort=9994

TraceLimit = -1
SkipTraceTime = -1
PPLogLevel = DEBUG
LogFileRootPath = /opt/pinpoint-php-5-agent/logs
AgentType="PHP"
PluginExclude = ExcludePlugin
PluginInclude = PhpRequestPlugin;QuickStartPlugin  ; PhpInternalFunctionsPlugin ;ExcludePlugin ;PDOPlugin;CurlPlugin;

[PHP]
PluginEntryFile=plugins_create.php
PluginRootDir= /opt/pinpoint-php-5-agent/pinpoint_php/plugins/
;eg: PluginRootDir=/home/apps/php-7.1.0/pinpoint/web/php/plugins**

I'm able to see transaction log in php.error.log successfully but not able to see agent log and agent not shown in PINPOINT web.
also retrieve below error

**PHP Warning:  PHP Startup: Unable to load dynamic library 'pinpoint' (tried: /usr/local/apache2/php/lib/php/extensions/no-debug-non-zts-20180731/pinpoint (/usr/local/apache2/php/lib/php/extensions/no-debug-
non-zts-20180731/pinpoint: cannot open shared object file: No such file or directory), /usr/local/apache2/php/lib/php/extensions/no-debug-non-zts-20180731/pinpoint.so (/usr/local/apache2/php/lib/php/extensions/no-debug-non-zts-201807
31/pinpoint.so: undefined symbol: zval_used_for_init)) in Unknown on line 0**

Regards,
Vidusha

**Comment by eeliu** [comment]
@VidushaZ 

Are there many version of php in your environment?  pinpoint-c-agent does not use 'zval_used_for_init'

**Comment by VidushaZ** [comment]
@eeliu Yes I had more environments and got it fixed by building it with phize7.3. Thing is I built the older version of the code which is **dev-v0.1**. The node itself shows up in pinpoint fine but I still cannot see mysql databases connected to it. Is the older version not supporting for mysql and others?

**Comment by eeliu** [comment]
@VidushaZ 

Try our latest version. 

dev-v0.1. not support 7.3
