### ISSUE TITLE
unable to build collector-agent

### ISSUE THREAD

**Issue by pramodm1609** [pinpoint-apm/pinpoint-c-agent#167]
Hi,

I am trying to build collector agent but its not working.

I am installing it on the server where internet access in not available.

getting error while running pip3 command. It is not able to download requirements from requirement file due to this I am not able to proceed.

So can you please provide PHP agent and collector-agent which is already built as you provided the working java agent for Java application.

**Comment by eeliu** [comment]
@pramodm1609 

> PHP agent

PHP agent consists of three parts.
1. pinpoint.so:  not need internet
2. composer vendor:  packet them into your test env and copy them into your internet blocked env.
3. plugins,: as `1`: some php script files.

> collector-agent 

pip supports install the offline packet. 
Ref: https://www.ibm.com/support/knowledgecenter/bs/SSWTQQ_2.0.3/install/t_si_pythonpackagesoffline.html

**Comment by pramodm1609** [comment]
Hi,

can u pls tell me how to install dependency present on requirement.txt file from pip install command, when internet access is blocked on computer.
because of this I am not able to run init_python_env.sh file on server.

I run and install requirements.txt on other machine where internet is available and tried to move it on my server. I tried to run  init_python_env.sh command but getting error.

./init_python_env.sh: /opt/miniconda/bin/pip: /home/vagrant/rpmbuild/SOURCES/miniconda/bin/python: bad interpreter: No such file or directory
/usr/bin/python: No module named grpc_tools

my env directory has following files

bin  include  lib  lib64  pip-selfcheck.json  pyvenv.cfg

and lib64 has python dependency.

Also please tell me do we really need to startc collector-agent to get stats on pinpoint-collector which is already running.


Please provide me the proper steps.

**Comment by eeliu** [comment]
> /usr/bin/python: No module named grpc_tools 

grpc_tools not ready

Check [pip downloads packet](https://www.ibm.com/support/knowledgecenter/bs/SSWTQQ_2.0.3/install/t_si_pythonpackagesoffline.html)

**Comment by eeliu** [comment]
@pramodm1609 

Environmental problem, sometimes are annoying, try docker image

```
docker pull eeliu2020/pinpoint-collector-agent:latest
```
