### ISSUE TITLE
PHP application is not register with pinpoint 

### ISSUE THREAD

**Issue by snmsmanager** [pinpoint-apm/pinpoint-c-agent#198]
Hi All,

![one](https://user-images.githubusercontent.com/5483940/88689526-32cdf480-d118-11ea-98e0-b9c451edea6d.png)

I've compiled pinpoint-c-agent successfully and start the agent to monitor our php application (PHP_TEST)  which is running on Apache 2.4 and using php composer. Once I started the agent then I'm not able to see my application name (PHP_TEST) which is configured under "conf/collector.conf". But I'm able to see test application provide by Pinpoint is registered as "APP-2" and show all data properly on APM .

My application  (PHP_TEST)  is also on same document root and I'm able to see logs related to my application (PHP_TEST).

 
## Context
* Operating System: Centos 7

* PHP Version: PHP 7.3.11

* php.ini:
extension=pinpoint_php.so
pinpoint_php.CollectorHost=unix:/tmp/collector-agent.sock
pinpoint_php.SendSpanTimeOutMs=0
pinpoint_php.DebugReport=true
pinpoint_php.TraceLimit=-1
log_errors = On
error_log = "/apps/pinpoint-agent/logs/pinpoint_agent.error.log"

* php-fpm or apache: Apache 2.4

* pinpoint_agent.conf:
[Collector]
AgentID=PHP_TEST
ApplicationName=PHP_TEST
# 1500 is PHP
ServerType=1500

collector.grpc.agent.ip=192.126.32.211
collector.grpc.agent.port=9991
collector.grpc.stat.ip=192.126.32.211
collector.grpc.stat.port=9992
collector.grpc.span.ip=192.126.32.211
collector.grpc.span.port=9993
collector.grpc.discardpolicy.maxpendingthreshold=10000
[Common]
# your web server (nginx&apache) port
Web_Port=80
# debug in dev
Log_Level=DEBUG
LOG_DIR=/apps/pinpoint-agent/logs/
[Agent]
# the same as below "pinpoint_php.CollectorHost"

Address=/tmp/collector-agent.sock

## Failure Logs
/pinpoint_agent.error.log
---------------------------------
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]pinpoint_end_trace Done!
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]pinpoint_start start
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]agent try to connect:(unix:/tmp/collector-agent.sock)
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]connected to /tmp/collector-agent.sock
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]key:uri value:/sip_app/index.php?type=get_date
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]key:client value:10.0.50.78
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]key:server value:172.26.30.241
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]key:stp value:1500
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]key:name value:PHP Request
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]key:appname value:APP-2
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]key:appid value:app-2
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]key:tid value:app-2^1594030106959^800
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]key:sid value:1329080454
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]pinpoint_start start
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]key:name value:app\AppDate::outputDate
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]key:stp value:1501
[28-Jul-2020 14:49:46 UTC] [pinpoint] [25417] [25417]add clues:-1:Array

Regards,
Gunawardana.

**Comment by eeliu** [comment]
> Once I started the agent then I'm not able to see my application name (PHP_TEST) which is configured under "conf/collector.conf". 

pinpoint_c_agent is not support setting name in conf/collector.conf any more.

Define the name by 

https://github.com/naver/pinpoint-c-agent/blob/fb2adb66ad15b54615f2562f8ce4041456125057/Example/PHP/app/index.php#L10-L16

**Comment by snmsmanager** [comment]
Hi eeliu,

Thanks for the update.
I've created Cache and copied Plugins from example to my application working directory and updated my index.php as you explained.
But I'm not able to see it under APM and returned below errors .

**thrown in /apps/pinpoint-agent/Example/PHP/vendor/eeliu/php_simple_aop/auto_pinpointed.php on line 11
[29-Jul-2020 06:41:01 UTC] [pinpoint] [21199] [21199]catch an Error
[29-Jul-2020 06:41:01 UTC] [pinpoint] [21199] [21199]apm_error_cb called
[29-Jul-2020 06:41:01 UTC] PHP Fatal error:  Uncaught Error: Class '/apps/pinpoint-agent/Example/PHP/Plugins/ClassMapInFile' not found in /apps/pinpoint-agent/Example/PHP/vendor/eeliu/php_simple_aop/auto_pinpointed.php:11**

Regards,
Gunawardana

**Comment by eeliu** [comment]
> [29-Jul-2020 06:41:01 UTC] PHP Fatal error: Uncaught Error: Class '/apps/pinpoint-agent/Example/PHP/Plugins/ClassMapInFile'

https://github.com/naver/pinpoint-c-agent/blob/fb2adb66ad15b54615f2562f8ce4041456125057/Example/PHP/app/index.php#L12

Please check this setting, it should be `Plugins/ClassMapInFile` .

**Comment by snmsmanager** [comment]
Hi eeliu,
I’m able to see all transactions to registered node ( SCAPP_DEV) and not able to see any internal transactions like database and able to see span logs as in attached pinpoint_agent.error.

![image](https://user-images.githubusercontent.com/5483940/89267188-85496c80-d654-11ea-8949-6f1fd7b48882.png)


Do we need to call application composer autoload file located in  /opt/icapp/web/htdocs/scapp_test_backends/scapp_new/protected/vendor other than auto_pinpointed.php

When we configure new application  index page to register with PINPOINT , would you explan below stpes are correct or changes need?

![image](https://user-images.githubusercontent.com/5483940/89267078-621ebd00-d654-11ea-9683-54d6fd3afc68.png)

**Comment by eeliu** [comment]
@snmsmanager 

Which framework you used? If you use thinkphp6
https://github.com/naver/pinpoint-c-agent/blob/830b8c84f6be90120fbc63e48a16fee82a205f65/Example/PHP/demo/thinkphp6/Plugins/DBPlugin.php#L22

while if not, you should fellow the example (for PDO  native API)

https://github.com/naver/pinpoint-c-agent/blob/master/Example/PHP/Plugins/PDOCommonPlugin.php

BTW, those are only some examples for how to write  plugins for databases(mysql, mssql, oracle).

**Comment by snmsmanager** [comment]
Hi @eeliu ,

Thanks for the update.
We are using YII 2 framework.

Regards,
Gunawardana

**Comment by eeliu** [comment]
@snmsmanager 

https://github.com/naver/pinpoint-c-agent/tree/master/Example/PHP/demo/yii-demo 
Yii database plugins not support yet.

Don't hesitate to give us a PR when your Yii plugins are done, your kind heart could help everyone who use php-agent on Yii. 
Thanks

**Comment by snmsmanager** [comment]
@eeliu 

Sure we will look in to it with highest priority . 
BTW is it same with YII 1 ?

Thanks,

**Comment by eeliu** [comment]
@snmsmanager 

If you find some problems when use agent on YII 1, please share them to us by an issue. 
Thanks

**Comment by snmsmanager** [comment]
@eeliu 

I'm not able to find "web.php" file 
$config = require __DIR__ . '/../config/web.php';

**Comment by eeliu** [comment]
@snmsmanager 
https://github.com/naver/pinpoint-c-agent/blob/4e0dd306fef007b7fd313e748100c3cfc3aefda4/Example/PHP/demo/yii-demo/web/index.php#L39
Did you meaning this? 
This file belongs to Yii framework. if not found, 
please show us how does you project tree looks like.

**Comment by snmsmanager** [comment]
@eeliu 

I've craeted project called "demoapp" under "/opt/web/htdocs/"

Project structure as below.
![image](https://user-images.githubusercontent.com/5483940/89756635-c3390b80-db00-11ea-8004-04183674a353.png)

**Comment by eeliu** [comment]
Got it, 

Copy the pinpoint destination and pinpoint_user_class_loader_hook, keep `require_once __DIR__. .... auto_pinpointed.php;` before `app->run`. 

https://github.com/naver/pinpoint-c-agent/blob/4e0dd306fef007b7fd313e748100c3cfc3aefda4/Example/PHP/demo/yii-demo/web/index.php#L40-L43

if you still can not make it through, share your project to us.

**Comment by snmsmanager** [comment]
@eeliu 

Thanks a lot for quick response.
Here I've used "Yii::createWebApplication($config)->run();" instead of $app = new yii\web\Application($config);  and $app->run(); 
Please find the attached project as you requested.

[demoapp.tar.gz](https://github.com/naver/pinpoint-c-agent/files/5049432/demoapp.tar.gz)

**Comment by snmsmanager** [comment]
@eeliu 

When I debug pinpoint_user_class_loader_hook function then I found that no any class loader retun to match below    **if(is_array($loader) && is_string($loader[0]) && $loader[0] =='Yii')**

When I tried to reregister forcefully then I recieved below errors 
DEBUG: START CURRENT LOADERS
============================
Array ( [0] => 
Array ( [0] => pinpoint\Common\PinpointClassLoader Object ( [origin:pinpoint\Common\PinpointClassLoader:private] => Composer\Autoload\ClassLoader Object ( [prefixLengthsPsr4:Composer\Autoload\ClassLoader:private] => Array ( [p] => Array ( [pinpoint\] => 9 ) [P] => Array ( [Plugins\] => 8 [PhpParser\] => 10 ) ) [prefixDirsPsr4:Composer\Autoload\ClassLoader:private] => Array ( [pinpoint\] => 
Array ( [0] => /opt/web/htdocs/demoapp/vendor/composer/../naver/pinpoint-php-aop/lib/pinpoint ) [Plugins\] => 
Array ( [0] => /opt/web/htdocs/demoapp/vendor/composer/../../Plugins ) [PhpParser\] => 
Array ( [0] => /opt/web/htdocs/demoapp/vendor/composer/../nikic/php-parser/lib/PhpParser ) ) [fallbackDirsPsr4:Composer\Autoload\ClassLoader:private] => Array ( ) [prefixesPsr0:Composer\Autoload\ClassLoader:private] => Array ( ) [fallbackDirsPsr0:Composer\Autoload\ClassLoader:private] => Array ( ) [useIncludePath:Composer\Autoload\ClassLoader:private] => [classMap:Composer\Autoload\ClassLoader:private] => 
Array ( [Yii] => /opt/web/htdocs/demoapp/vendor/composer/../yiisoft/yii/framework/yii.php [YiiBase] => /opt/web/htdocs/demoapp/vendor/composer/../yiisoft/yii/framework/YiiBase.php ) [classMapAuthoritative:Composer\Autoload\ClassLoader:private] => [missingClasses:Composer\Autoload\ClassLoader:private] => Array ( ) [apcuPrefix:Composer\Autoload\ClassLoader:private] => ) [classMap:pinpoint\Common\PinpointClassLoader:private] => pinpoint\Common\AopClassMap Object ( [index_file_path:protected] => /opt/web/htdocs/demoapp/Cache/__class_index_table [cached:pinpoint\Common\AopClassMap:private] => 1 [classLoaderMap:pinpoint\Common\AopClassMap:private] => Array ( ) ) ) [1] => loadClass ) ) 
DEBUG: END CURRENT LOADERS
============================

Fatal error: Uncaught LogicException: Passed array does not specify an existing static method 
(class 'Plugins\PinpointYiiClassLoader' not found) in /opt/web/htdocs/demoapp/index.php:34 Stack trace: #0 /opt/web/htdocs/demoapp/index.php(34): spl_autoload_register(Array, true, false) #1 /opt/web/htdocs/demoapp/index.php(40): pinpoint_user_class_loader_hook() #2 {main} thrown in /opt/web/htdocs/demoapp/index.php on line 34

**Comment by eeliu** [comment]
@snmsmanager

Tell you  a good news, our member (@EyelynSu) is writing yii1.1 plugins for you. Just waiting for some time.

**Comment by EyelynSu** [comment]
@snmsmanager  @eeliu 
Here is the demo added ppt-agent which is based on your attachment, please have a try and help us check wheather it works well. 
And please tell us if there is any problem.
Thank you!
https://github.com/EyelynSu/demoapp

**Comment by snmsmanager** [comment]
@eeliu @EyelynSu 

highly appreciate your effort . 
I'll update you soon..

**Comment by EyelynSu** [comment]
@snmsmanager @eeliu 
Hi~I have updated a mysql  plugin.
https://github.com/EyelynSu/demoapp/blob/master/Plugins/PDOCommonPlugin.php
