### ISSUE TITLE
Using the agent properly

### ISSUE THREAD

**Issue by dv-morais** [pinpoint-apm/pinpoint-c-agent#223]
After I finally understood what I was doing wrong on #218 I finally had sucess in colleting something from the agent but... I think I dont know how to use it properly...

I read the [DOCS](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/DOC/PHP/User%20Manual.md) but, even after reading, I'm sure that I'm clueless.

Using this [project](https://github.com/glaucia86/projeto.crud.php) as an example I inserted these lines in banco.php:

```
			require_once __DIR__."/vendor/autoload.php";
		
			
			define('AOP_CACHE_DIR',__DIR__.'/Cache/');
			define('PLUGINS_DIR',__DIR__.'/Plugins/');
			define('APPLICATION_NAME','testegpdpinpoint');
			define('APPLICATION_ID','testegpdpinpoint');
			

			require_once __DIR__. '/vendor/naver/pinpoint-php-aop/auto_pinpointed.php';

```

I used composer.phar to install the AOP to the project.

so... I was hoping to see some classes and queries but isnt showing something relevant.

![image](https://user-images.githubusercontent.com/57958197/96489889-70718380-1216-11eb-96a4-682175bec114.png)

so... what am I missing?

**Comment by eeliu** [comment]
@dv-morais 

Please fellow our plugins example:  https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/Example/PHP/Plugins/

**Comment by dv-morais** [comment]
Tried my best with the examples but I dont think I got the hang of it... I think I'm not using the hook option properly. What am I doing wrong?



```
<?php


///@hook:Banco::conectar
///@hook:Banco::__construct
///@hook:Banco::desconectar
namespace Plugins;
use Plugins\Candy;

 class DvmPlugin extends Candy
 {
  
	///@hook:Banco::conectar
	///@hook:Banco::__construct
	///@hook:Banco::desconectar

	 public function onBefore(){
         pinpoint_add_clue("stp",PHP_METHOD);
         pinpoint_add_clues(PHP_ARGS,print_r($this->args,true));
     }

	///@hook:Banco::conectar
	///@hook:Banco::__construct
	///@hook:Banco::desconectar

     public function onEnd(&$ret){
         pinpoint_add_clues(PHP_RETURN,"ture");
     }


	///@hook:Banco::conectar
	///@hook:Banco::__construct
	///@hook:Banco::desconectar

     public function onException($e){
         pinpoint_add_clue("EXP",$e->getMessage());
     }
 }

?>
```

**Comment by eeliu** [comment]
@dv-morais 
check the readme https://github.com/pinpoint-apm/pinpoint-php-aop/tree/dev
