### ISSUE TITLE
No transactions in scatter chart 

### ISSUE THREAD

**Issue by snmsmanager** [pinpoint-apm/pinpoint-c-agent#227]
Hi All,

I have built the pinpoint-php-module and collector-agent successfully and updated my index.php as per given instructions to monitor PHP application running on YII.

**PHP: 7.3 , 
GCC: 4,8,5, 
Python: 3.4, 
pinpoint: 2.0.4; 
pinpoint-c-agent: 2**

I’m able to see Active Request chart properly, but not able to see transactions or response summary.

![image](https://user-images.githubusercontent.com/5483940/97479792-a3371c80-1978-11eb-970d-bd2cb51c0260.png)

**PHP.INI**
extension=pinpoint_php.so
pinpoint_php.CollectorHost=unix:/tmp/collector-agent.sock
pinpoint_php.SendSpanTimeOutMs=0
pinpoint_php.DebugReport=true
pinpoint_php.TraceLimit=-1
log_errors = On
error_log = "/opt / pinpoint-php-agent/logs/error.log"

**error.log** 
[28-Oct-2020 23:47:29  ] [pinpoint] [24983] [24983]agent status changed: 2 ->2 reason:checklimit pass
[error.log](https://github.com/pinpoint-apm/pinpoint-c-agent/files/5454080/error.log)

**collector.agent.log**
[2020-10-28 23:50:49,956] [16040] **[WARNING] [GrpcAgentImplement.py:131] interrupted by Parameter to MergeFrom() must be instance of same class: expected PSpan got PSpan. for field PSpanMessage.span**

[collector.agent.log](https://github.com/pinpoint-apm/pinpoint-c-agent/files/5454090/collector.agent.log)

Regards,
Pradeep.

**Comment by eeliu** [comment]
I tested the JsonSpan

`
'''{"E":2112,"FT":1500,"S":1603909247759,"appid":"MDA_SCAPP3_DEV","appname":"MDA_SCAPP3_DEV","client":"172.26.99.107","clues":["46:200"],"name":"PHP Request","server":"selfcare.demo","sid":"75245407","stp":"1500","tid":"MDA_SCAPP3_DEV^1603908366935^357192","uri":"/scapp_6_0_1/index.php?r=/scapp/DashBoardNew/getDashInfo"}'''
`

It's OK.

Did you modify the collect-agent  source code ? If not, clean the `Proto/grpc/*.py` and rerun `init_python_env.sh`.

**Comment by snmsmanager** [comment]
Thanks a lot @eeliu .

I did not change collect-agent source and it is clean compile as per document.
Now I have removed all .py from Proto and executed **init_python_env.sh** with bellow warning.
Did this due to Python 3.4 ?

(env) [root@p_demo]# ./init_python_env.sh
Requirement already satisfied: grpcio-tools in ./env/lib/python3.4/site-packages
Requirement already satisfied: protobuf<4.0dev,>=3.5.0.post1 in ./env/lib/python3.4/site-packages (from grpcio-tools)
Requirement already satisfied: grpcio>=1.33.1 in ./env/lib/python3.4/site-packages (from grpcio-tools)
  Ignoring futures: markers 'python_version < "3.2"' don't match your environment
  Ignoring enum34: markers 'python_version < "3.4"' don't match your environment
Requirement already satisfied: setuptools in ./env/lib/python3.4/site-packages (from protobuf<4.0dev,>=3.5.0.post1->grpcio-tools)
Requirement already satisfied: six>=1.9 in ./env/lib/python3.4/site-packages (from protobuf<4.0dev,>=3.5.0.post1->grpcio-tools)
You are using pip version 9.0.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ThreadDump.proto:4:1: warning: Import google/protobuf/wrappers.proto is unused.
ThreadDump.proto:3:1: warning: Import google/protobuf/empty.proto is unused.
Span.proto:3:1: warning: Import google/protobuf/empty.proto is unused.
Stat.proto:3:1: warning: Import google/protobuf/empty.proto is unused.
Service.proto:6:1: warning: Import ThreadDump.proto is unused.

Still same error in log and no transaction visible. 

[2020-10-29 08:54:02,757] [3656] [WARNING] [GrpcAgentImplement.py:131] interrupted by Parameter to MergeFrom() must be instance of same class: expected PSpan got PSpan. for field PSpanMessage.span
[2020-10-29 08:54:02,764] [3656] [WARNING] [GrpcAgentImplement.py:131] interrupted by Parameter to MergeFrom() must be instance of same class: expected PSpan got PSpan. for field PSpanMessage.span

Regards,
Pradeep

**Comment by eeliu** [comment]
@snmsmanager 

I did not get any progress on your problem.

We create a docker image for `collector-agent`, it will help to remove the some environmental issues.

>  docker pull eeliu2020/pinpoint-collector-agent

**Comment by eeliu** [comment]
@snmsmanager 

Feel free to reopen it if doesn't solve your problems.
