### ISSUE TITLE
Missing middle-ware id in `Common/PluginsDefines.php`

### ISSUE THREAD

**Issue by marty-macfly** [pinpoint-apm/pinpoint-c-agent#272]
# Expected Behavior

Add missing middle-ware ID in [Plugins/Common/PluginsDefines.php](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/plugins/PHP/Plugins/Common/PluginsDefines.php)  for:

* MSSQL_SERVER => 2200
* ORACLE => 2300
* CUBRID => 2400
* POSTGRESQL => 2500
* CASSANDRA => 2600
* MONGODB => 2651
* RABBITMQ => 8300
* ACTIVEMQ => 8310
* ARCUS => 8100

# Current Behavior

In version 4.0.0 of plugin package the previously listed middle-ware are not present. Wondering also if it doesn't make sence to rename `define("PP_HEADER_NGINX_PROXY","Pinpoint-ProxyNginx");` to `define("PP_HEADER_NGINX_PROXY","HTTP_PINPOINT_PROXYNGINX");` to make it consistent with others ?

## Context

* pinpoint-php: 0.4.0

**Comment by eeliu** [comment]
@marty-macfly 

> ServerType ID 

You can give up PR.

> Pinpoint-ProxyNginx

I found an issue on https://github.com/pinpoint-apm/pinpoint/issues/3252. it could help you use Proxy Header feature.

**Comment by marty-macfly** [comment]
Yep, I'll prepare that

**Comment by marty-macfly** [comment]
Here is the PR
