### ISSUE TITLE
How to monitor django deployed by uwsgi+nginx?

### ISSUE THREAD

**Issue by 373836411** [pinpoint-apm/pinpoint-c-agent#282]
I can monitor the project started with the httpserver that comes with django, but when I deploy the project with nginx+uwsgi, I encountered a permission problem, but I don't know how to solve it. The error message is as follows:

*MyMiddleware request
[pinpoint] [52739] [52739]#0 pinpoint_start start
[pinpoint] [52739] [52739]#128 add clue key:appname value:10.28.0.100-Django-8888
[pinpoint] [52739] [52739]#128 add clue key:appid value:APM-0100280001008888
[pinpoint] [52739] [52739]#128 add clue key:name value:BaseDjangoRequest request
[pinpoint] [52739] [52739]#128 add clue key:uri value:/favicon.ico
[pinpoint] [52739] [52739]#128 add clue key:client value:10.19.197.133
[pinpoint] [52739] [52739]#128 add clue key:server value:10.28.0.100
[pinpoint] [52739] [52739]#128 add clue key:stp value:1700
[pinpoint] [52739] [52739]pre_init_shared_object: open address with:Permission denied

uwsgi: /tmp/pip-install-gzeq51ez/pinpointpy_84ec1378330b4d799049fa3092f41d5d/common/src/Cache/SharedObj.c:196: fetch_shared_obj_addr: Assertion `object.region' failed.**

Can anyone help me? thank you very much!

**Comment by eeliu** [comment]
ho, nice catch!

Does it working when use "python manage.py runserver"?

**Comment by 373836411** [comment]
> ho, nice catch!
> 
> Does it working when use "python manage.py runserver"?

Yes, "python manage.py runserver" is OK!

**Comment by eeliu** [comment]
Grant the access to your uwsgi user to /dev/shm

[how to set user ?](https://uwsgi-docs.readthedocs.io/en/latest/Options.html#uid)

**Comment by 373836411** [comment]
> Grant the access to your uwsgi user to /dev/shm
> 
> [how to set user ?](https://uwsgi-docs.readthedocs.io/en/latest/Options.html#uid)

When I changed the permissions of /dev/shm/pinpoint-php.shm(from 640 to 646), uwsgi+nginx was OK. 

But pinpoint-web displays ‘’no data’’, but the graphics in REAL TIME has real-time data. It’s so strange. Let me see what the reason is. thank you very much!

**Comment by eeliu** [comment]
Hmm, shared your collector-agent log  to us?

**Comment by 373836411** [comment]
> Hmm, shared your collector-agent log to us?

Is it this one?    ↓↓↓↓↓

*****MyMiddleware request******
[pinpoint] [45085] [45085]#0 pinpoint_start start
[pinpoint] [45085] [45085]#128 add clue key:appname value:10.28.0.100-Django-8888
[pinpoint] [45085] [45085]#128 add clue key:appid value:APM-0100280001008888
[pinpoint] [45085] [45085]#128 add clue key:name value:BaseDjangoRequest request
[pinpoint] [45085] [45085]#128 add clue key:uri value:/
[pinpoint] [45085] [45085]#128 add clue key:client value:10.19.197.133
[pinpoint] [45085] [45085]#128 add clue key:server value:10.28.0.100
[pinpoint] [45085] [45085]#128 add clue key:stp value:1700
[pinpoint] [45085] [45085]#128 add clue key:tid value:APM-0100280001008888^1609314791099^231
[pinpoint] [45085] [45085]#128 add clue key:sid value:2079558357
[pinpoint] [45085] [45085]#128 add clues:206:GET
[pinpoint] [45085] [45085]#128 pinpoint_start start
[pinpoint] [45085] [45085]#127 add clue key:name value:Cursor.execute
[pinpoint] [45085] [45085]#127 add clue key:stp value:2101
[pinpoint] [45085] [45085]#127 add clue key:SQL value:SELECT COUNT(*) AS `__count` FROM `requirement_requirementquotation` WHERE (`requirement_requirementquotation`.`trade_status` = %s AND `requirement_requirementquotation`.`web_display` = %s)
[pinpoint] [45085] [45085]#127 add clue key:dst value:socket 127.0.0.1:3306
[pinpoint] [45085] [45085]#127 pinpoint_end_trace Done!
[pinpoint] [45085] [45085]#128 pinpoint_start start
[pinpoint] [45085] [45085]#126 add clue key:name value:Cursor.execute
[pinpoint] [45085] [45085]#126 add clue key:stp value:2101
[pinpoint] [45085] [45085]#126 add clue key:SQL value:SELECT COUNT(*) AS `__count` FROM `message_usermessage` WHERE (`message_usermessage`.`receiver` = %s AND `message_usermessage`.`state` = %s AND `message_usermessage`.`web_display` = %s)
[pinpoint] [45085] [45085]#126 add clue key:dst value:socket 127.0.0.1:3306
[pinpoint] [45085] [45085]#126 pinpoint_end_trace Done!
[pinpoint] [45085] [45085]#128 pinpoint_start start
[pinpoint] [45085] [45085]#125 add clue key:name value:Cursor.execute
[pinpoint] [45085] [45085]#125 add clue key:stp value:2101
[pinpoint] [45085] [45085]#125 add clue key:SQL value:SELECT `website_websiteinfo`.`id`, `website_websiteinfo`.`website_name`, `website_websiteinfo`.`short_name`, `website_websiteinfo`.`index_title`, `website_websiteinfo`.`index_state`, `website_websiteinfo`.`website_icon`, `website_websiteinfo`.`website_logo`, `website_websiteinfo`.`weixin_ewm`, `website_websiteinfo`.`website_description`, `website_websiteinfo`.`website_keywords`, `website_websiteinfo`.`service_TEL`, `website_websiteinfo`.`service_time`, `website_websiteinfo`.`company_email`, `website_websiteinfo`.`recruit_email`, `website_websiteinfo`.`email_banner`, `website_websiteinfo`.`office_short`, `website_websiteinfo`.`address_short`, `website_websiteinfo`.`detail_address`, `website_websiteinfo`.`address_dest`, `website_websiteinfo`.`website_time`, `website_websiteinfo`.`copyright_ownership`, `website_websiteinfo`.`copyright_hyperlink`, `website_websiteinfo`.`record_number`, `website_websiteinfo`.`record_hyperlink`, `website_websiteinfo`.`add_time`, `website_websiteinfo`.`update_time`, `website_websiteinfo`.`web_display` FROM `website_websiteinfo` WHERE `website_websiteinfo`.`web_display` = %s ORDER BY `website_websiteinfo`.`update_time` DESC LIMIT 1
[pinpoint] [45085] [45085]#125 add clue key:dst value:socket 127.0.0.1:3306
[pinpoint] [45085] [45085]#125 pinpoint_end_trace Done!
[pinpoint] [45085] [45085]#128 pinpoint_start start
[pinpoint] [45085] [45085]#124 add clue key:name value:Cursor.execute
[pinpoint] [45085] [45085]#124 add clue key:stp value:2101
[pinpoint] [45085] [45085]#124 add clue key:SQL value:SELECT `website_websiteseomate`.`id`, `website_websiteseomate`.`siteadmin_name`, `website_websiteseomate`.`meta_sign`, `website_websiteseomate`.`add_time`, `website_websiteseomate`.`update_time`, `website_websiteseomate`.`web_display` FROM `website_websiteseomate` WHERE `website_websiteseomate`.`web_display` = %s ORDER BY `website_websiteseomate`.`update_time` DESC
[pinpoint] [45085] [45085]#124 add clue key:dst value:socket 127.0.0.1:3306
[pinpoint] [45085] [45085]#124 pinpoint_end_trace Done!
[pinpoint] [45085] [45085]#128 pinpoint_start start
[pinpoint] [45085] [45085]#123 add clue key:name value:Cursor.execute
[pinpoint] [45085] [45085]#123 add clue key:stp value:2101
[pinpoint] [45085] [45085]#123 add clue key:SQL value:SELECT `website_indexslideshow`.`id`, `website_indexslideshow`.`title`, `website_indexslideshow`.`image`, `website_indexslideshow`.`priority_level`, `website_indexslideshow`.`hyperlink`, `website_indexslideshow`.`activity_id`, `website_indexslideshow`.`add_time`, `website_indexslideshow`.`update_time`, `website_indexslideshow`.`web_display` FROM `website_indexslideshow` WHERE `website_indexslideshow`.`web_display` = %s ORDER BY `website_indexslideshow`.`priority_level` ASC, `website_indexslideshow`.`update_time` DESC
[pinpoint] [45085] [45085]#123 add clue key:dst value:socket 127.0.0.1:3306
[pinpoint] [45085] [45085]#123 pinpoint_end_trace Done!
[pinpoint] [45085] [45085]#128 pinpoint_start start
[pinpoint] [45085] [45085]#122 add clue key:name value:Cursor.execute
[pinpoint] [45085] [45085]#122 add clue key:stp value:2101
[pinpoint] [45085] [45085]#122 add clue key:SQL value:SELECT `requirement_requirementquotation`.`id`, `requirement_requirementquotation`.`title_id`, `requirement_requirementquotation`.`appoint`, `requirement_requirementquotation`.`username_id`, `requirement_requirementquotation`.`price`, `requirement_requirementquotation`.`quote_time`, `requirement_requirementquotation`.`trade_status`, `requirement_requirementquotation`.`select`, `requirement_requirementquotation`.`select_time`, `requirement_requirementquotation`.`trade_time`, `requirement_requirementquotation`.`cancel_time`, `requirement_requirementquotation`.`outbid_time`, `requirement_requirementquotation`.`update_time`, `requirement_requirementquotation`.`web_display` FROM `requirement_requirementquotation` WHERE (`requirement_requirementquotation`.`trade_status` = %s AND `requirement_requirementquotation`.`web_display` = %s) ORDER BY `requirement_requirementquotation`.`trade_time` DESC LIMIT 25
[pinpoint] [45085] [45085]#122 add clue key:dst value:socket 127.0.0.1:3306
[pinpoint] [45085] [45085]#122 pinpoint_end_trace Done!
[pinpoint] [45085] [45085]#128 pinpoint_start start
[pinpoint] [45085] [45085]#121 add clue key:name value:Cursor.execute
[pinpoint] [45085] [45085]#121 add clue key:stp value:2101
[pinpoint] [45085] [45085]#121 add clue key:SQL value:SELECT `requirement_userrequirement`.`id`, `requirement_userrequirement`.`title`, `requirement_userrequirement`.`type_id`, `requirement_userrequirement`.`appoint`, `requirement_userrequirement`.`appoint_user_id`, `requirement_userrequirement`.`appoint_price`, `requirement_userrequirement`.`status`, `requirement_userrequirement`.`price_id`, `requirement_userrequirement`.`time_limit_id`, `requirement_userrequirement`.`user_qq`, `requirement_userrequirement`.`user_role`, `requirement_userrequirement`.`settlement_type_id`, `requirement_userrequirement`.`settlement_account`, `requirement_userrequirement`.`settlement_name`, `requirement_userrequirement`.`agency_fees`, `requirement_userrequirement`.`charge_rate`, `requirement_userrequirement`.`pay_amount`, `requirement_userrequirement`.`gain_amount`, `requirement_userrequirement`.`charge_amount`, `requirement_userrequirement`.`username_id`, `requirement_userrequirement`.`manager_qq`, `requirement_userrequirement`.`pub_time`, `requirement_userrequirement`.`cancel_time`, `requirement_userrequirement`.`details`, `requirement_userrequirement`.`audit_status`, `requirement_userrequirement`.`audit_time`, `requirement_userrequirement`.`audit_failure`, `requirement_userrequirement`.`collect_peoman`, `requirement_userrequirement`.`collect_number`, `requirement_userrequirement`.`browse_peoman`, `requirement_userrequirement`.`browse_number`, `requirement_userrequirement`.`quote_peoman`, `requirement_userrequirement`.`quote_number`, `requirement_userrequirement`.`quote_avg`, `requirement_userrequirement`.`trade_price`, `requirement_userrequirement`.`trade_time`, `requirement_userrequirement`.`update_time`, `requirement_userrequirement`.`web_display` FROM `requirement_userrequirement` WHERE (`requirement_userrequirement`.`appoint` = %s AND `requirement_userrequirement`.`status` = %s AND `requirement_userrequirement`.`audit_status` = %s AND `requirement_userrequirement`.`web_display` = %s) ORDER BY `requirement_userrequirement`.`collect_peoman` DESC, `requirement_userrequirement`.`browse_peoman` DESC, `requirement_userrequirement`.`pub_time` DESC LIMIT 25
[pinpoint] [45085] [45085]#121 add clue key:dst value:socket 127.0.0.1:3306
[pinpoint] [45085] [45085]#121 pinpoint_end_trace Done!
*****MyMiddleware response******
[pinpoint] [45085] [45085]#128 add clues:46:200
[pinpoint] [45085] [45085]this span:({"E":42,"FT":1700,"S":1609318386403,"appid":"APM-0100280001008888","appname":"10.28.0.100-Django-8888","calls":[{"E":1,"S":4,"SQL":"SELECT COUNT(*) AS `__count` FROM `requirement_requirementquotation` WHERE (`requirement_requirementquotation`.`trade_status` = %s AND `requirement_requirementquotation`.`web_display` = %s)","dst":"socket 127.0.0.1:3306","name":"Cursor.execute","stp":"2101"},{"E":1,"S":7,"SQL":"SELECT COUNT(*) AS `__count` FROM `message_usermessage` WHERE (`message_usermessage`.`receiver` = %s AND `message_usermessage`.`state` = %s AND `message_usermessage`.`web_display` = %s)","dst":"socket 127.0.0.1:3306","name":"Cursor.execute","stp":"2101"},{"E":2,"S":10,"SQL":"SELECT `website_websiteinfo`.`id`, `website_websiteinfo`.`website_name`, `website_websiteinfo`.`short_name`, `website_websiteinfo`.`index_title`, `website_websiteinfo`.`index_state`, `website_websiteinfo`.`website_icon`, `website_websiteinfo`.`website_logo`, `website_websiteinfo`.`weixin_ewm`, `website_websiteinfo`.`website_description`, `website_websiteinfo`.`website_keywords`, `website_websiteinfo`.`service_TEL`, `website_websiteinfo`.`service_time`, `website_websiteinfo`.`company_email`, `website_websiteinfo`.`recruit_email`, `website_websiteinfo`.`email_banner`, `website_websiteinfo`.`office_short`, `website_websiteinfo`.`address_short`, `website_websiteinfo`.`detail_address`, `website_websiteinfo`.`address_dest`, `website_websiteinfo`.`website_time`, `website_websiteinfo`.`copyright_ownership`, `website_websiteinfo`.`copyright_hyperlink`, `website_websiteinfo`.`record_number`, `website_websiteinfo`.`record_hyperlink`, `website_websiteinfo`.`add_time`, `website_websiteinfo`.`update_time`, `website_websiteinfo`.`web_display` FROM `website_websiteinfo` WHERE `website_websiteinfo`.`web_display` = %s ORDER BY `website_websiteinfo`.`update_time` DESC LIMIT 1","dst":"socket 127.0.0.1:3306","name":"Cursor.execute","stp":"2101"},{"E":2,"S":24,"SQL":"SELECT `website_websiteseomate`.`id`, `website_websiteseomate`.`siteadmin_name`, `website_websiteseomate`.`meta_sign`, `website_websiteseomate`.`add_time`, `website_websiteseomate`.`update_time`, `website_websiteseomate`.`web_display` FROM `website_websiteseomate` WHERE `website_websiteseomate`.`web_display` = %s ORDER BY `website_websiteseomate`.`update_time` DESC","dst":"socket 127.0.0.1:3306","name":"Cursor.execute","stp":"2101"},{"E":1,"S":29,"SQL":"SELECT `website_indexslideshow`.`id`, `website_indexslideshow`.`title`, `website_indexslideshow`.`image`, `website_indexslideshow`.`priority_level`, `website_indexslideshow`.`hyperlink`, `website_indexslideshow`.`activity_id`, `website_indexslideshow`.`add_time`, `website_indexslideshow`.`update_time`, `website_indexslideshow`.`web_display` FROM `website_indexslideshow` WHERE `website_indexslideshow`.`web_display` = %s ORDER BY `website_indexslideshow`.`priority_level` ASC, `website_indexslideshow`.`update_time` DESC","dst":"socket 127.0.0.1:3306","name":"Cursor.execute","stp":"2101"},{"E":2,"S":32,"SQL":"SELECT `requirement_requirementquotation`.`id`, `requirement_requirementquotation`.`title_id`, `requirement_requirementquotation`.`appoint`, `requirement_requirementquotation`.`username_id`, `requirement_requirementquotation`.`price`, `requirement_requirementquotation`.`quote_time`, `requirement_requirementquotation`.`trade_status`, `requirement_requirementquotation`.`select`, `requirement_requirementquotation`.`select_time`, `requirement_requirementquotation`.`trade_time`, `requirement_requirementquotation`.`cancel_time`, `requirement_requirementquotation`.`outbid_time`, `requirement_requirementquotation`.`update_time`, `requirement_requirementquotation`.`web_display` FROM `requirement_requirementquotation` WHERE (`requirement_requirementquotation`.`trade_status` = %s AND `requirement_requirementquotation`.`web_display` = %s) ORDER BY `requirement_requirementquotation`.`trade_time` DESC LIMIT 25","dst":"socket 127.0.0.1:3306","name":"Cursor.execute","stp":"2101"},{"E":3,"S":36,"SQL":"SELECT `requirement_userrequireme
[pinpoint] [45085] [45085]7 send size 4084
[pinpoint] [45085] [45085]7 send size 1012
[pinpoint] [45085] [45085]7 send size 1328
[pinpoint] [45085] [45085]#128 pinpoint_end_trace Done!
[pid: 45085|app: 0|req: 10/11] 10.19.197.133 () {48 vars in 1057 bytes} [Wed Dec 30 16:53:06 2020] GET / => generated 10683 bytes in 43 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
*****MyMiddleware request******
[pinpoint] [45085] [45085]#0 pinpoint_start start
[pinpoint] [45085] [45085]#128 add clue key:appname value:10.28.0.100-Django-8888
[pinpoint] [45085] [45085]#128 add clue key:appid value:APM-0100280001008888
[pinpoint] [45085] [45085]#128 add clue key:name value:BaseDjangoRequest request
[pinpoint] [45085] [45085]#128 add clue key:uri value:/favicon.ico
[pinpoint] [45085] [45085]#128 add clue key:client value:10.19.197.133
[pinpoint] [45085] [45085]#128 add clue key:server value:10.28.0.100
[pinpoint] [45085] [45085]#128 add clue key:stp value:1700
[pinpoint] [45085] [45085]#128 add clue key:tid value:APM-0100280001008888^1609314791099^232
[pinpoint] [45085] [45085]#128 add clue key:sid value:1122446265
[pinpoint] [45085] [45085]#128 add clues:206:GET
*****MyMiddleware response******
[pinpoint] [45085] [45085]#128 add clues:46:301
[pinpoint] [45085] [45085]this span:({"E":1,"FT":1700,"S":1609318386856,"appid":"APM-0100280001008888","appname":"10.28.0.100-Django-8888","client":"10.19.197.133","clues":["206:GET","46:301"],"name":"BaseDjangoRequest request","server":"10.28.0.100","sid":"1122446265","stp":"1700","tid":"APM-0100280001008888^1609314791099^232","uri":"/favicon.ico"})
[pinpoint] [45085] [45085]7 send size 322
[pinpoint] [45085] [45085]#128 pinpoint_end_trace Done!
[pid: 45085|app: 0|req: 11/12] 10.19.197.133 () {46 vars in 930 bytes} [Wed Dec 30 16:53:06 2020] GET /favicon.ico => generated 0 bytes in 2 msecs (HTTP/1.1 301) 4 headers in 162 bytes (1 switches on core 0)

**Comment by eeliu** [comment]
https://github.com/pinpoint-apm/pinpoint-c-agent/issues/282#issuecomment-752380794
Not these, from [collector-agent](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/DOC/PY/Readme.md#install-collector-agent)

**Comment by 373836411** [comment]
> Hmm, shared your collector-agent log to us?

I feel that the server side is very unstable!
I just tried to stop all dockers first, then start, and then the django project returned to normal, data can be received, and the topology diagram is also normal, like this:
![image](https://user-images.githubusercontent.com/23046994/103341065-c5f0c900-4ac0-11eb-96e0-efbaaeaa1d12.png)

**Comment by eeliu** [comment]
> > Hmm, shared your collector-agent log to us?
> 
> I feel that the server side is very unstable!
> I just tried to stop all dockers first, then start, and then the django project returned to normal, data can be received, and the topology diagram is also normal, like this:
> ![image](https://user-images.githubusercontent.com/23046994/103341065-c5f0c900-4ac0-11eb-96e0-efbaaeaa1d12.png)

hmm,  please let us know if the problem comes out again!

**Comment by 373836411** [comment]
> > > Hmm, shared your collector-agent log to us?
> > 
> > 
> > I feel that the server side is very unstable!
> > I just tried to stop all dockers first, then start, and then the django project returned to normal, data can be received, and the topology diagram is also normal, like this:
> > ![image](https://user-images.githubusercontent.com/23046994/103341065-c5f0c900-4ac0-11eb-96e0-efbaaeaa1d12.png)
> 
> hmm, please let us know if the problem comes out again!

Okay! Tks. The collector-agent log that may cause the error just now is as follows:

[2020-12-28 11:22:22,605] [61539] [ERROR] [GrpcAgent.py:116] handleCommand channel  <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Exception serializing request!"
        debug_error_string = "None"
> error
[2020-12-30 15:46:24,209] [3758] [ERROR] [GrpcAgent.py:116] handleCommand channel  <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Exception serializing request!"
        debug_error_string = "None"
> error
[2020-12-30 15:49:43,529] [41597] [ERROR] [GrpcAgent.py:116] handleCommand channel  <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Exception serializing request!"
        debug_error_string = "None"
> error
[2020-12-30 16:51:45,081] [42795] [ERROR] [GrpcAgent.py:192] ping response abort with exception: [hostname: "localhost.localdomain"
ip: "127.0.0.1"
ports: "80"
serviceType: 1700
pid: 42795
endTimestamp: -1
]  <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1609318305.080919174","description":"Error received from peer ipv4:10.27.0.80:9991","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>
[2020-12-30 16:51:45,082] [42795] [ERROR] [GrpcAgent.py:116] handleCommand channel  <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1609318305.080893075","description":"Error received from peer ipv4:10.27.0.80:9991","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
> error

  ...
  ...
  ...

[2020-12-30 16:56:05,127] [42795] [ERROR] [GrpcAgent.py:116] handleCommand channel  <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1609318565.126249174","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1609318479.578852258","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
> error
[2020-12-30 16:56:15,129] [42795] [ERROR] [GrpcAgent.py:116] handleCommand channel  <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1609318575.128495046","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1609318479.578852258","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
> error
[2020-12-30 16:56:25,130] [42795] [ERROR] [GrpcAgent.py:116] handleCommand channel  <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1609318585.130018647","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1609318479.578852258","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
> error
[2020-12-30 16:56:35,132] [42795] [ERROR] [GrpcAgent.py:116] handleCommand channel  <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1609318595.131493850","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1609318479.578852258","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
> error

**Comment by eeliu** [comment]
https://github.com/pinpoint-apm/pinpoint-c-agent/issues/282#issuecomment-752386546

It looks the network unavailable !

How about now?

**Comment by 373836411** [comment]
> [#282 (comment)](https://github.com/pinpoint-apm/pinpoint-c-agent/issues/282#issuecomment-752386546)
> 
> It looks the network unavailable !
> 
> How about now?

Since restarting the server, everything is normal, and the collector-agent log has no errors. I am worried that after adding a new app, if no data appears, the server may have to be restarted.  ^.^

**Comment by eeliu** [comment]
The collector-agent or the pinpoint ?

**Comment by 373836411** [comment]
> The collector-agent or the pinpoint ?

There is no error in both.

**Comment by eeliu** [comment]
collector-agent will automatic register new application. But you must choose the different applicationName and applicationID

**Comment by 373836411** [comment]
> collector-agent will automatic register new application. But you must choose the different applicationName and applicationID

We have paid attention to this. There are special naming rules to ensure that ID and NAME are unique.

**Comment by 373836411** [comment]
> collector-agent will automatic register new application. But you must choose the different applicationName and applicationID

Hi!
Excuse me, how to configure tomcat started with daemon.sh?

I know that in catalina.sh:

JAVA_OPTS="$JAVA_OPTS -javaagent:/usr/local/pinpoint-agent/pinpoint-bootstrap-1.8.0.jar"
JAVA_OPTS="$JAVA_OPTS -Dpinpoint.agentId=APM-01002800806880"
JAVA_OPTS="$JAVA_OPTS -Dpinpoint.applicationName=10.28.8.68-tomcat8-80"

But after copying to daemon.sh, pinpoint-web still reports the error "There are no running agents.". Try to modify several parameters by yourself, and the problem remains.

**Comment by eeliu** [comment]
@373836411 
I'm confusing, if no running agents, why?

![image](https://user-images.githubusercontent.com/23046994/103341065-c5f0c900-4ac0-11eb-96e0-efbaaeaa1d12.png)

**Comment by 373836411** [comment]
> @373836411
> I'm confusing, if no running agents, why?
> 
> ![image](https://user-images.githubusercontent.com/23046994/103341065-c5f0c900-4ac0-11eb-96e0-efbaaeaa1d12.png)

Sorry, the tomcat problem should not be asked here, because it has nothing to do with Django (Python).

In addition, I have solved the above problem:

↓↓↓  daemon.sh   ↓↓↓

# Pinpoint 20201231
JAVA_OPTS="-javaagent:/usr/local/pinpoint-agent/pinpoint-bootstrap-1.8.0.jar \
     -Dpinpoint.agentId=APM-01002800806880 \
     -Dpinpoint.applicationName=10.28.8.68-tomcat8-80"


But when monitoring tomcat started in daemon mode, I encountered the "No data" problem. Restarting the server this time did not help. I am still looking for a solution.

**Comment by eeliu** [comment]
Glad to hear that !!!

**Comment by eeliu** [comment]
It's looks done
