### ISSUE TITLE
[pinpoint-collector-agent] Support of pinpoint.container option

### ISSUE THREAD

**Issue by marty-macfly** [pinpoint-apm/pinpoint-c-agent#293]
Hello,

On the Java agent there is a flag [-Dpinpoint.container](https://pinpoint-apm.github.io/pinpoint/2.2.0/installation.html#quick-overview-of-installation) so when in a container context agent are not duplicate when having different id.

In the case of a dockerize collector agent for python or php the option doesn't exist and agent name is hostname of the container. Workaround for the moment to avoid duplicating agent is to for hostname of container to be sure name is consistent upon restart. And avoiding polluting the UI with many agents.

Is there the same kind of option on the python collector agent ? Or is it plan to add it ?

Thanks,

**Comment by eeliu** [comment]
@marty-macfly 


>If you’re launching the agent in a containerized environment,  **_you might have set your agent id to be auto-generated every time the container is launched._** With frequent deployment and auto-scaling, this will lead to the Web UI being cluttered with all the list of agents that were launched and destroyed previously. For such cases, you might want to add -Dpinpoint.container in addition to the 2 required command-line arguments above when launching the agent.


Thanks， pinpoint-c-agent dose not support `-Dpinpoint.container` current.  I will support this feature in next version.

**Comment by marty-macfly** [comment]
Related to that I've got a question, I've got 2 web servers containers (`web-225-cpx2c` and `web-225-tk44l`) that both have local collector agent: php extension using socket to send data to python collector agent version 0.4.0 that send to pinpoint collector on UI side.

On pinpoint UI (v 2.2.0) side, I see only one agent:

![image](https://user-images.githubusercontent.com/12715929/104715232-d78cce80-5758-11eb-9d62-7d68412b7b44.png)

But I can see trace of request coming from both web servers so both agent. Both agent have the same *Agent Id: sid.web*

**Comment by eeliu** [comment]
@marty-macfly 

Please use https://github.com/pinpoint-apm/pinpoint-c-agent/releases/tag/v0.4.2 

update the docker images for collector-agent

**Comment by marty-macfly** [comment]
It's good for me thanks.
