### ISSUE TITLE
pinpoint-c-agent is working well but server-map doesn't draw communication line between flask app and mariadb

### ISSUE THREAD

**Issue by parkeunsoo** [pinpoint-apm/pinpoint-c-agent#321]
# Expected Behavior

> server-map draw communication between Flask and MariaDB 

# Current Behavior

> What is the current behavior?
   server-map doesn't draw communication between Flask and MariaDB

# Failure Information (for bugs)
it dosen't have failure information

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:  (AWS ECS - flask app (debian-buster based image), pinpoint-c-agent)

* PHP Version: no php

* php.ini: no php

* php-fpm or apache: no php

* pinpoint_agent.conf:

PP_ADDRESS | 0.0.0.0@9999
PP_COLLECTOR_AGENT_AGENT_IP | 10.0.**.**
PP_COLLECTOR_AGENT_AGENT_PORT | 9991
PP_COLLECTOR_AGENT_ISDOCKER | true
PP_COLLECTOR_AGENT_SPAN_IP | 10.0.**.**
PP_COLLECTOR_AGENT_SPAN_PORT | 9993
PP_COLLECTOR_AGENT_STAT_IP | 10.0.**.**
PP_COLLECTOR_AGENT_STAT_PORT | 9992
PP_LOG_DIR | /tmp/
PP_Log_Level | ERROR

## Failure Logs

Please include any relevant log snippets or files here.

> no failure pinpoint-c-agent works well but it doesn't draw connection line between flask application and mariadb
![스크린샷 2021-03-15 오후 5 45 54](https://user-images.githubusercontent.com/32799518/111127666-6bdbac00-85b7-11eb-8f6e-eb6340728d65.png)

**Comment by EyelynSu** [comment]
@parkeunsoo

**Comment by EyelynSu** [comment]
@parkeunsoo 
Hello!
Which ORM do you use?  SQLAlchemy or other one?

**Comment by parkeunsoo** [comment]
@EyelynSu 
Hello!
I use SQLAlchemy

**Comment by EyelynSu** [comment]
@parkeunsoo 
Would you please show us your code?
For I can't reproduce the problem. I used flask_sqlalchemy, ref to https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart/
![28P JEJMN GO59`S6XYX$N](https://user-images.githubusercontent.com/41946743/111249919-6ded4b80-8647-11eb-928f-96c015c1ee17.png)

**Comment by parkeunsoo** [comment]
@EyelynSu 

Thank you for your kind answer.
This code is excluding private sources.

`

    from sqlalchemy import create_engine, pool
    from sqlalchemy.pool import QueuePool
    from env import Environment
    from .util_main import gVariables
    
    import mysql.connector as mariadb
    
    class DBManager(object):

      def __init__(self):
          self.dbConnection = None
          self.cursor = None
  
          if gVariables.db_pool is None:
              environment = Environment()
              self.HOST = environment.database_config.host
              self.DB = environment.database_config.db
              self.USER = environment.database_config.user
              self.PASSWORD = environment.database_config.password
              self.PORT = environment.database_config.port
  
      def open_db(self):
          try:
              # private source
  
          except Exception as e:
              raise e
  
      def get_connection(self):
          db_connection = mariadb.connect(host=self.HOST,
                                          port=self.PORT,
                                          user=self.USER,
                                          passwd=self.PASSWORD,
                                          db=self.DB)
          return db_connection
  
      def close_db(self):
          if self.dbConnection is not None:
              self.dbConnection.close()
  
      def commit_db(self):
          if self.dbConnection is not None:
              self.dbConnection.commit()`

**Comment by EyelynSu** [comment]
@parkeunsoo 
Hello!
We have add plugin for mysql-connector, please checkout branch [dev](https://github.com/pinpoint-apm/pinpoint-c-agent/tree/dev) and try it again. 
Please feel free to tell us if there is still any problem.

**Comment by parkeunsoo** [comment]
@EyelynSu 
Hello! Thanks so much  
I added plugin directory in dev branch to my code
but, it doesn't still draw connection line between flask server and maria db
