### ISSUE TITLE
Unable to enable log on console

### ISSUE THREAD

**Issue by marty-macfly** [pinpoint-apm/pinpoint-c-agent#324]
# Expected Behavior

When `LOG_DIR` is not set in configuration file and the environement variable `PP_LOG_DIR` is not define log_dir is by default `/tmp`, instead to be console.

# Current Behavior

In current behavior it seems not possible to enable the console log it's always go to file because fallback for configuration and env variable is `/tmp`and there is no way to make the condition define in [CollectorAgentConf.py#L149](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/collector-agent/CollectorAgentConf/CollectorAgentConf.py#L149) to be true.

If we replace `if dir is not None:` with `if dir:` we can set an empty log dir and it will by default enable log on console.

**Comment by marty-macfly** [comment]
Is it fixed in go version of the agent ? I didn't test it yet.

**Comment by marty-macfly** [comment]
I've push a PR to support logging on STDOUT with the new Go version of the collector agent. For the record also new version doesn't support socket anymore may be worst just not it into the doc or changelog ?

**Comment by eeliu** [comment]
Done
