### ISSUE TITLE
NotImplementedError when delay celery task

### ISSUE THREAD

**Issue by jobis-mincheol** [pinpoint-apm/pinpoint-c-agent#335]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I checked the [documentation](https://github.com/naver/pinpoint-c-agent/wiki),[issues](https://github.com/naver/pinpoint-c-agent/issues) and found no answer

# Expected Behavior

> logging behavior nomally

# Current Behavior

> I got NotImplementedError when delay celery task
<img width="1177" alt="스크린샷 2021-05-18 오후 1 29 45" src="https://user-images.githubusercontent.com/84366982/118590343-392f7900-b7dd-11eb-9636-b8a68da3d6cc.png">

<img width="1329" alt="스크린샷 2021-05-18 오후 1 38 09" src="https://user-images.githubusercontent.com/84366982/118590936-557fe580-b7de-11eb-81e1-a24df58b8be3.png">

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* pinpoint-c-agent: 0.4.2
* Operating System: Ubuntu 16.04
* Python Version: 3.7.4
* Django Version : 2.2
* celery : 4.4.0
* channels : 2.4.0
* channels-redis : 2.4.1

## Failure Logs

Please include any relevant log snippets or files here.

> pinpoint_log.txt  php.log  php-fpm.log etc (Anything could help us )

**Comment by EyelynSu** [comment]
@jobis-mincheol @eeliu 
Hello!
 This is a bug, we have fixedit, please pull master branch and try it again.
PR: https://github.com/pinpoint-apm/pinpoint-c-agent/pull/337

**Comment by jobis-mincheol** [comment]
@EyelynSu working! thanks for fixing

**Comment by eeliu** [comment]
Done
