### ISSUE TITLE
Unable to build Collector-Agent for PHP

### ISSUE THREAD

**Issue by pradeepgunsgmail** [pinpoint-apm/pinpoint-c-agent#339]
Hi,

I have followed steps to build Collector-Agent to monitor PHP application but it return error while run “go build” as below. 
I have exported GOROOT and GOPATH as well. Don’t we need to build python agent ? Please help to resolve this

###############################
export GOROOT=/usr/local/go
export GOPATH = /backup/pinpoint-c-agent/collector-agent
export PATH=$PATH:/usr/local/go/bin
###############################

**[root@appsrv1_stg collector-agent]# go build
server.go:4:2: cannot find package "CollectorAgent/server" in any of:
        /usr/local/go/src/CollectorAgent/server (from $GOROOT)
        ($GOPATH not set)
server.go:9:2: cannot find package "github.com/sirupsen/logrus" in any of:
        /usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)
        ($GOPATH not set)
[root@appsrv1_stg collector-agent]#**

**Comment by eeliu** [comment]
@pradeepgunsgmail 

hello, here is the solution.

set $GOROOT

> https://stackoverflow.com/questions/20628918/cannot-download-gopath-not-set

**Comment by pradeepgunsgmail** [comment]
@eeliu,

Thanks. I have built Collector-Agent successfully after set the $GOPATH.  Would you please explain the steps and  how to set PP_ADDRESS?

Do we need to build Python-Agent as well ?

my old configuration is like below 

[Collector]
AgentID=dev-app-local
ApplicationName=dev-app-local
collector.grpc.agent.ip=172.26.32.111
collector.grpc.agent.port=9991
collector.grpc.stat.ip=172.26.32.111
collector.grpc.stat.port=9992
collector.grpc.span.ip=172.26.32.111
collector.grpc.span.port=9993
#collector.grpc.discardpolicy.maxpendingthreshold=10000
[Common]
Web_Port=8180
Log_Level=DEBUG
LOG_DIR=/opt/php-agent/log
[Agent]
Address=/tmp/collector-agent.sock

**Comment by eeliu** [comment]
> Python-Agent 

What's `Python-Agent ` , the  collector-agent write by python ?

No, just use the golang version you build.

Here is the `steps`

https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/DOC/PY/Readme.md#install-collector-agent

**Comment by eeliu** [comment]
@pradeepgunsgmail 

Try docker images
https://github.com/pinpoint-apm/pinpoint-c-agent/tree/master/DOC/collector-agent#use-docker-images
