### ISSUE TITLE
Pinpoint PHP Agent with YII framework.

### ISSUE THREAD

**Issue by snmsmanager** [pinpoint-apm/pinpoint-c-agent#363]
Hello,

Anyone successfully integrated PINPOINT PHP agent with YII framework version 1.x. It is working with  YII framework version 2.x perfectly but I’m not able to capture PDO or CURL or any other internal requests in YII framework version 1.x. I’ve already wrote plugins to capture PDO or CURL but still working up to the framework and not able to hook after framework.  

thanks,
Pradeep

**Comment by eeliu** [comment]
@snmsmanager 

Hmm, how about sharing your `project and plugins` to us? It would help us to address the problem.
