### ISSUE TITLE
 PHP 8.1: src/PHP/pinpoint_php.cpp:644:20: error: invalid conversion from 'void (*)(int, zend_string*, uint32_t, zend_string*)' {aka 'void (*)(int, _zend_string*, unsigned int, _zend_string*)'} to 'void (*)(int, const char*, uint32_t, zend_string*)' {aka 'void (*)(int, const char*, unsigned int, _zend_string*)'} [-fpermissive]

### ISSUE THREAD

**Issue by vleedev** [pinpoint-apm/pinpoint-c-agent#379]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
- [ x] I checked the [documentation](https://github.com/naver/pinpoint-c-agent/wiki),[issues](https://github.com/naver/pinpoint-c-agent/issues) and found no answer

# Expected Behavior

Build **pinpoint_php.so** extension for **PHP 8.1**

# Current Behavior

I've got an error with these messages

> /bin/bash /pinpoint-c-agent/libtool --mode=compile g++ -I. -I/pinpoint-c-agent -I/pinpoint-c-agent/include -I/pinpoint-c-agent/main -I/pinpoint-c-agent -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/pinpoint-c-agent/common/include -I/pinpoint-c-agent/src/PHP  -DHAVE_CONFIG_H  -g -O2    -DZEND_COMPILE_DL_EXT=1 -c /pinpoint-c-agent/src/PHP/pinpoint_php.cpp -o src/PHP/pinpoint_php.lo  -MMD -MF src/PHP/pinpoint_php.dep -MT src/PHP/pinpoint_php.lo
 g++ -I. -I/pinpoint-c-agent -I/pinpoint-c-agent/include -I/pinpoint-c-agent/main -I/pinpoint-c-agent -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/pinpoint-c-agent/common/include -I/pinpoint-c-agent/src/PHP -DHAVE_CONFIG_H -g -O2 -DZEND_COMPILE_DL_EXT=1 -c /pinpoint-c-agent/src/PHP/pinpoint_php.cpp -MMD -MF src/PHP/pinpoint_php.dep -MT src/PHP/pinpoint_php.lo  -fPIC -DPIC -o src/PHP/.libs/pinpoint_php.o
/pinpoint-c-agent/src/PHP/pinpoint_php.cpp: In function 'zend_result zm_startup_pinpoint_php(int, int)':
/pinpoint-c-agent/src/PHP/pinpoint_php.cpp:641:20: error: invalid conversion from 'void (*)(int, zend_string*, uint32_t, zend_string*)' {aka 'void (*)(int, _zend_string*, unsigned int, _zend_string*)'} to 'void (*)(int, const char*, uint32_t, zend_string*)' {aka 'void (*)(int, const char*, unsigned int, _zend_string*)'} [-fpermissive]
     old_error_cb = zend_error_cb;
                    ^~~~~~~~~~~~~
/pinpoint-c-agent/src/PHP/pinpoint_php.cpp:642:21: error: invalid conversion from 'void (*)(int, const char*, uint32_t, zend_string*)' {aka 'void (*)(int, const char*, unsigned int, _zend_string*)'} to 'void (*)(int, zend_string*, uint32_t, zend_string*)' {aka 'void (*)(int, _zend_string*, unsigned int, _zend_string*)'} [-fpermissive]
     zend_error_cb = apm_error_cb;
                     ^~~~~~~~~~~~
make: *** [Makefile:202: src/PHP/pinpoint_php.lo] Error 1

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Docker run php 8.1 apache buster image.
2. Git clone pinpoint git repo and checkout and get in the directory
3. Run cmd: "phpize"
4. Exec: "./configure"
5. Exec: "make"

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Debian buster
* PHP Version: 8.1
> Configuring for:
PHP Api Version:         20210902
Zend Module Api No:      20210902
Zend Extension Api No:   420210902
* Pinpoint version: 0.4.5 and  0.4.6  and dev branch (c6821e38081c68cdffb7778b8a61d5e159cd1025)

**Comment by eeliu** [comment]
@vleedev 
We will check it!

**Comment by eeliu** [comment]
@vleedev 

please use master

**Comment by vleedev** [comment]
> @vleedev
> 
> please use master

Thank you! It works well. I am also waiting for the new release version for that!
