### ISSUE TITLE
Nginx could not connect PHP

### ISSUE THREAD

**Issue by mayingping-Bella** [pinpoint-apm/pinpoint-c-agent#388]
**PHP version: 8.1.0**
1. After modifying **composer.json**, excute **composer update**, there is an error:

> .../apps/pinpoint/pinpoint-c-agent/testapps/PHP/app/index.php
> php: symbol lookup error: .../apps/php-8.1.0/lib/php/extensions/debug-non-zts-20210902/pinpoint_php.so: undefined syNSt12out_of_rangeC1EPKc

After installing **zlib** extension, the error disappear

2. Everything goes well, start nginx and php
![1641373285](https://user-images.githubusercontent.com/72844069/148191841-30e9b246-e219-4e6a-a3e9-a7c975acb726.png)

3. click on "click me", page jump
![1641373402](https://user-images.githubusercontent.com/72844069/148191896-e9daa0ed-94c4-486a-9b74-1b3dbffa1dbe.png)

4. check nginx error.log

> 2022/01/05 11:22:22 [error] 17211#0: *123 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: xx.xx.xx.xxx, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xx.xx.xx.xx:xxxx"

**Comment by eeliu** [comment]
Done
