### ISSUE TITLE
invalid python plugins

### ISSUE THREAD

**Issue by pipasugar** [pinpoint-apm/pinpoint-c-agent#390]
It seems the python plugins are invalid on this page:
https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/DOC/PY/Readme.md
![image](https://user-images.githubusercontent.com/22242014/149154642-bdbcc6c2-73b8-4452-a5c7-081fb36b2e98.png)

1,my pinpoint version is v2.3.3
2,I use flask,so I follow the link above and download pinpoint-python-plugins
3,It dosen't show call chain map,every service just show itself alone.
4,I download pinpoint-c-agent-0.4.6.tar.gz and decompress it ,replace python plugin with pinpoint-c-agent-0.4.6/plugins/PY/pinpoint(much appreciate to Evelyn)
5,finally,it works ok,the relationship with each service is showing.

**Comment by EyelynSu** [comment]
Doc Fixed!
https://github.com/pinpoint-apm/pinpoint-c-agent/pull/391

The latest plugin: https://github.com/pinpoint-apm/pinpoint-c-agent/releases/download/V2020.12.17/pinpoint-python-plugins.tar.gz
