### ISSUE TITLE
Commonly used synchronization libraries:`pymongo,requests...`,asynchronous libraries:`aiohttp,motor...`

### ISSUE THREAD

**Issue by eeliu** [pinpoint-apm/pinpoint-c-agent#465]
Commonly used synchronization libraries:`pymongo,requests...`,asynchronous libraries:`aiohttp,motor...`
The latest version should be fine.
Both synchronous and asynchronous libraries are required.
Does the sync library also need to be refactored? I can't use monkey_patch_for_pinpoint directly just for `requests`, right?

Sincere thanks

_Originally posted by @521bibi in https://github.com/pinpoint-apm/pinpoint-c-agent/issues/462#issuecomment-1169653489_

> Commonly used synchronization libraries:`pymongo,requests...`,asynchronous libraries:`aiohttp,motor...` The latest version should be fine. Both synchronous and asynchronous libraries are required. Does the sync library also need to be refactored? I can't use monkey_patch_for_pinpoint directly just for `requests`, right?
> 
> Sincere thanks

Please watch this issue, we will update it when done

**Comment by 521bibi** [comment]
It's cool! Thanks for your support. I can also try to help if you need it.
