### ISSUE TITLE
Pinpoint PHP 8.2 compatibility

### ISSUE THREAD

**Issue by ctykhoa** [pinpoint-apm/pinpoint-c-agent#502]
Hello,

I have an issue while compiling Pinpoint on PHP 8.2:

<pre> /pinpoint-c-agent/src/PHP/pinpoint_php.cpp: In function &apos;void zif_pinpoint_get_func_ref_args(zend_execute_data*, zval*)&apos;:
 /pinpoint-c-agent/src/PHP/pinpoint_php.cpp:559:64: error: too many arguments to function &apos;zend_result zend_forbid_dynamic_call()&apos;
   559 |     if (zend_forbid_dynamic_call(&quot;pinpoint_get_func_ref_args()&quot;) == FAILURE)
       |                                                                ^
 In file included from /usr/local/include/php/main/php.h:35,
                  from /pinpoint-c-agent/src/PHP/pinpoint_php.cpp:40:
 /usr/local/include/php/Zend/zend_API.h:782:39: note: declared here
   782 | static zend_always_inline zend_result zend_forbid_dynamic_call(void)
       |                                       ^~~~~~~~~~~~~~~~~~~~~~~~
</pre>

I see that function `zend_forbid_dynamic_call` is no longer need param from PHP 8.2 (changed in [commit](https://github.com/php/php-src/commit/a13730c5e465b3c349a7970d15a49e4e132d4e07#diff-bb1285146d0d0b77580bccc637afc7da6446eb0d3ad06925cc3a056c53de8a98)).

May I get any help or a new release for this issue to support PHP 8.2?

Thank you.

**Comment by eeliu** [comment]
@ctykhoa 

Please check the latest version of pinpoint-php ,
https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/DOC/PHP/Readme.md
