### ISSUE TITLE
While installing agent for php application, I am getting some error.

### ISSUE THREAD

**Issue by PIYUSHRAJ24** [pinpoint-apm/pinpoint-c-agent#504]
I have followed the steps:-
1.)phpize
2.)./configure
3.)after running the command "**make**" It is showing error ----->

/bin/sh /opt/pinpoint-c-agent/libtool --mode=compile g++  -I. -I/opt/pinpoint-c-agent -DPHP_ATOM_INC -I/opt/pinpoint-c-agent/include -I/opt/pinpoint-c-agent/main -I/opt/pinpoint-c-agent -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/opt/pinpoint-c-agent/common/include -I/opt/pinpoint-c-agent/src/PHP  -DHAVE_CONFIG_H  -g -O2   -c /opt/pinpoint-c-agent/src/PHP/pinpoint_php.cpp -o src/PHP/pinpoint_php.lo 
libtool: compile:  g++ -I. -I/opt/pinpoint-c-agent -DPHP_ATOM_INC -I/opt/pinpoint-c-agent/include -I/opt/pinpoint-c-agent/main -I/opt/pinpoint-c-agent -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/opt/pinpoint-c-agent/common/include -I/opt/pinpoint-c-agent/src/PHP -DHAVE_CONFIG_H -g -O2 -c /opt/pinpoint-c-agent/src/PHP/pinpoint_php.cpp  -fPIC -DPIC -o src/PHP/.libs/pinpoint_php.o
In file included from /opt/pinpoint-c-agent/src/PHP/pinpoint_php.cpp:45:0:
/opt/pinpoint-c-agent/src/PHP/php_pinpoint_php.h:19:10: fatal error: common.h: No such file or directory
 #include "common.h"
          ^~~~~~~~~~
compilation terminated.
make: *** [src/PHP/pinpoint_php.lo] Error 1

Please provide the solution. It would be very helpful.

**Comment by PIYUSHRAJ24** [comment]
After resolving the above error now I am facing this issue. Please provide the appropriate solution.
**ERROR--->**
make
/bin/sh /opt/pinpoint-c-agent/libtool --mode=link cc -DPHP_ATOM_INC -I/opt/pinpoint-c-agent/include -I/opt/pinpoint-c-agent/main -I/opt/pinpoint-c-agent -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/opt/pinpoint-c-agent/common/include -I/opt/pinpoint-c-agent/src/PHP  -DHAVE_CONFIG_H  -g -O2    -o pinpoint_php.la -export-dynamic -avoid-version -prefer-pic -module -rpath /opt/pinpoint-c-agent/modules  src/PHP/pinpoint_php.lo -l:libpinpoint_common.a -lstdc++ -L/opt/pinpoint-c-agent/build/lib -lrt
libtool: link: cc -shared  -fPIC -DPIC  src/PHP/.libs/pinpoint_php.o   -l:libpinpoint_common.a -lstdc++ -L/opt/pinpoint-c-agent/build/lib -lrt  -O2   -Wl,-soname -Wl,pinpoint_php.so -o .libs/pinpoint_php.so
/bin/ld: cannot find -l:libpinpoint_common.a
collect2: error: ld returned 1 exit status
make: *** [pinpoint_php.la] Error 1

**Comment by PIYUSHRAJ24** [comment]
Tried what you suggested but still got the same error.

**Comment by PIYUSHRAJ24** [comment]
# phpize
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902

# ./configure 
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for pkg-config... /bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... gawk
checking for pinpoint_php support... yes, shared
checking whether to enable pinpoint_php support... yes, shared
checking support test... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
------Build common libraries------------
./configure: line 4554: cmake: command not found
make: *** No targets specified and no makefile found.  Stop.
----------------------------------------
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /bin/ld
checking if the linker (/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /bin/nm -B
checking the name lister (/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /bin/ld -m elf_x86_64
checking if the linker (/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands

# make
/bin/sh /opt/pinpoint-c-agent/libtool --mode=compile g++  -I. -I/opt/pinpoint-c-agent -DPHP_ATOM_INC -I/opt/pinpoint-c-agent/include -I/opt/pinpoint-c-agent/main -I/opt/pinpoint-c-agent -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/opt/pinpoint-c-agent/common/include -I/opt/pinpoint-c-agent/src/PHP  -DHAVE_CONFIG_H  -g -O2   -c /opt/pinpoint-c-agent/src/PHP/pinpoint_php.cpp -o src/PHP/pinpoint_php.lo 
libtool: compile:  g++ -I. -I/opt/pinpoint-c-agent -DPHP_ATOM_INC -I/opt/pinpoint-c-agent/include -I/opt/pinpoint-c-agent/main -I/opt/pinpoint-c-agent -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/opt/pinpoint-c-agent/common/include -I/opt/pinpoint-c-agent/src/PHP -DHAVE_CONFIG_H -g -O2 -c /opt/pinpoint-c-agent/src/PHP/pinpoint_php.cpp  -fPIC -DPIC -o src/PHP/.libs/pinpoint_php.o
/bin/sh /opt/pinpoint-c-agent/libtool --mode=link cc -DPHP_ATOM_INC -I/opt/pinpoint-c-agent/include -I/opt/pinpoint-c-agent/main -I/opt/pinpoint-c-agent -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/opt/pinpoint-c-agent/common/include -I/opt/pinpoint-c-agent/src/PHP  -DHAVE_CONFIG_H  -g -O2    -o pinpoint_php.la -export-dynamic -avoid-version -prefer-pic -module -rpath /opt/pinpoint-c-agent/modules  src/PHP/pinpoint_php.lo -l:libpinpoint_common.a -lstdc++ -L/opt/pinpoint-c-agent/build/lib -lrt

libtool: link: cc -shared  -fPIC -DPIC  src/PHP/.libs/pinpoint_php.o   -l:libpinpoint_common.a -lstdc++ -L/opt/pinpoint-c-agent/build/lib -lrt  -O2   -Wl,-soname -Wl,pinpoint_php.so -o .libs/pinpoint_php.so
/bin/ld: cannot find -l:libpinpoint_common.a
collect2: error: ld returned 1 exit status
make: *** [pinpoint_php.la] Error 1


These are the full logs. Thankyou for cooperating.

**Comment by PIYUSHRAJ24** [comment]
visited this URL-https://github.com/pinpoint-apm/pinpoint-c-agent/actions/runs/3738897426
It is not helping me at all. Please provide a better solution. It would be very helpful for me.

**Comment by eeliu** [comment]
already fixed by v0.4.12

**Comment by eeliu** [comment]
Please try the latest version 
 https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/DOC/PHP/Readme.md
