### ISSUE TITLE
Need Clarification on Alarm and Alert features of Pinpoint

### ISSUE THREAD

**Issue by Cloud-DevOps-24** [pinpoint-apm/pinpoint-c-agent#505]
All my pinpoint-apm infrastructure is dockerized and I want to use Alarm and Alert features. Still, after setting up all the configurations (user group and alarm), I am not getting alerts even if the threshold value exceeds. Please tell me if I need to do some other configuration or how I can access this feature.
Server Ports are open for all TCP protocols.

**Comment by PIYUSHRAJ24** [comment]
Please provide the solution. I am configuring it for production.

**Comment by Cloud-DevOps-24** [comment]
Can you please tell me that after dockerized pinpoint-apm still need to do any configuration in pinpoint-docker for using alarm features?

**Comment by EyelynSu** [comment]
Hello~

**Comment by EyelynSu** [comment]
Hello~
To set alarm, please ref to https://pinpoint-apm.gitbook.io/pinpoint/documents/alarm
And BTW, dockerized pinpoint, please ref to https://github.com/pinpoint-apm/pinpoint-docker
