### ISSUE TITLE
pinpoint_force_end_trace() will stuck in infinite loop if node is E_INVALID_NODE

### ISSUE THREAD

**Issue by sillidev** [pinpoint-apm/pinpoint-c-agent#511]
**Describe the bug**
Function `pinpoint_force_end_trace()` defined [here](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/62559d4224a4ebc74d66a21a1fe8b6cbead4bd14/common/src/common.cpp#L248) keep calling `pinpoint_end_trace()` until `E_ROOT_NODE` is received. The logic doesn't consider that `pinpoint_end_trace()` can also output `E_INVALID_NODE` and make `pinpoint_force_end_trace()` stuck in infinite loop.

**To Reproduce**
1. Execute `pinpoint_force_end_trace()` for invalid node

**Actual behavior**
* Agent stuck in infinite loop

**Expected behavior**
* Output failure and agent should not stuck

**Agent Version:**
v0.4.11

**Comment by eeliu** [comment]
fixed by v0.4.12
