### ISSUE TITLE
Pinpoint PHP, no call tree

### ISSUE THREAD

**Issue by CanzumDemir** [pinpoint-apm/pinpoint-c-agent#513]
Hello Pinpoint Team.

I use Pinpoint-Docker, have installed the pinpoint-c-agent and the pinpoint-php-agent.

Im not using a Framework, i have a simple Class with 1 function which does a curl oparation.

This is my index.php:
```
<?php
    namespace index;
    
    use test;

    require_once __DIR__.'/vendor/autoload.php';
    define('APPLICATION_NAME','TestApp-1');
    define('APPLICATION_ID','test');
    define('AOP_CACHE_DIR',__DIR__.'/Cache/');
    define('PLUGINS_DIR',__DIR__.'/Plugins/');
    define('PINPOINT_USE_CACHE','YES');
    require_once __DIR__.'/vendor/pinpoint-apm/pinpoint-php-aop/auto_pinpointed.php';
    
    require_once __DIR__.'/Test.php';

    $test = new \test\Test();
    $test->doCurl();
    
?>
```

And this is my Class with 1 function:
```
<?php
namespace test;
class Test {
    public function doCurl() {
        $url = "https://example.com";

        $data = array(
            'param1' => 'value1',
            'param2' => 'value2'
        );

        $ch = curl_init();

        // cURL-Optionen festlegen
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

        $response = curl_exec($ch);

        if(curl_errno($ch)) {
            $error = curl_error($ch);
        } else {
            $decodedResponse = json_decode($response, true);
        }

        curl_close($ch);
    }
}
```

I made a copy of the CommonPlugin of the PHP TestApp and pasted it in my Plugins Dir. 
I changed the "///@hook" with my Test Class and added the function "doCurl" in "hook".
The Plugin looks like:
```
<?php

namespace Plugins;
use Pinpoint\Plugins\Common\PinTrace;

///@hook:test\Test::doCurl
class CommonPlugin extends PinTrace
{
    ///@hook:test\Test::doCurl
    public function onBefore(){
        pinpoint_add_clue("stp",PP_PHP_METHOD);
        pinpoint_add_clues(PP_PHP_ARGS,print_r($this->args,true));
    }

    ///@hook:test\Test::doCurl
    public function onEnd(&$ret){
        pinpoint_add_clues(PP_PHP_RETURN,print_r($ret,true));
    }

    ///@hook:test\Test::doCurl
    public function onException($e){
        pinpoint_add_clue("EXP",$e->getMessage());
    }
}
```
I also added in Composer.json:
```
 "autoload": {
        "psr-4": {
	    "Plugins\\": "Plugins"
        }
 }
```

In PinPoin Ui, i see following:
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/83336656/2225afef-e178-46ee-81f2-44d593516093)

I can not see the curl functions.

Am I doing something wrong or is it even possible to do what I want to do?

I use apache2 webserver and php-fpm.
Before every test i deleted the Cache file: "__class_index_table"

Here is my full Project:

[PPphpTestWithCurl.zip](https://github.com/pinpoint-apm/pinpoint-c-agent/files/11610759/PPphpTestWithCurl.zip)

**Comment by CanzumDemir** [comment]
Hello eeliu, thank you for your help.

I have been able to fix the problem with the psr4. If i launch the php project a new test.php is created and modified in the cache folder. Now Test.php in Cache/app folder looks like:

```
<?php

namespace app;

class Test
{
    public function doCurl()
    {
        $url = "https://example.com";
        $data = array('param1' => 'value1', 'param2' => 'value2');
        $ch = \Pinpoint\Plugins\Sys\curl\curl_init();
        // cURL-Optionen festlegen
        \Pinpoint\Plugins\Sys\curl\curl_setopt($ch, CURLOPT_URL, $url);
        \Pinpoint\Plugins\Sys\curl\curl_setopt($ch, CURLOPT_POST, true);
        \Pinpoint\Plugins\Sys\curl\curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));
        \Pinpoint\Plugins\Sys\curl\curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $response = \Pinpoint\Plugins\Sys\curl\curl_exec($ch);
        if (curl_errno($ch)) {
            $error = curl_error($ch);
        } else {
            $decodedResponse = json_decode($response, true);
        }
        \Pinpoint\Plugins\Sys\curl\curl_close($ch);
    }
}
```

But unfortunately it still looks the same in the UI. You can't see the curl functions that are called in the Test.php. 

Could you possibly help me further?

My project now looks like this, if you want to have a look:
[test2.zip](https://github.com/pinpoint-apm/pinpoint-c-agent/files/11625702/test2.zip)

**Comment by eeliu** [comment]
remove this line 

```
   ...
    //require_once __DIR__.'/application/Test.php';~

    $test = new \app\Test();
    $test->doCurl();
```

**Comment by CanzumDemir** [comment]
removed, but still not working...

Log shows:
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/83336656/fdd1e1e2-a75b-43c9-b27b-2ba6ec67c110)

I think it is not adding clue of the test.php. But why i added "///@hook:app\Test::doCurl". 

Do you have an idea?

**Comment by CanzumDemir** [comment]
Oh sorry my mistake. Thank you so much have commented out the line 
`    require_once __DIR__.'/application/Test.php';
`
and now it works.

Thank you for your time invested!
