### ISSUE TITLE
Docker Image of php-testapp, c-agent and php-agent

### ISSUE THREAD

**Issue by CanzumDemir** [pinpoint-apm/pinpoint-c-agent#514]
Hello Pinpoint team
i dare to write this now because i am not sure if this is an embarrassing idea :D. First of all I am pretty new to Docker and PHP.
I created myself a Docker image with your PHP testapp, in which the collector-agent and php-agent are already installed. I had problems to set up the testapp normally on my pc, therefore this idea. It works in conjunction with pinpoint-docker. It may not be the most effective option. Still, I thought someone new to PHP, like me, might want to use it . If you agree, I would push the docker image in the Docker hub and link it here. However, you would then need to do some configuration if you wanted to use the image. You would have to go into the container once and adjust the IP in RunServer.php in the Php-TestApp. I have also already created a instruction that would look like this:
Maybe it's also possible to automate the steps, I haven't had time to look for it yet
<br><br><br>

# With this Docker image, you can run PinPoint's PHP test app (https://github.com/pinpoint-apm) with a few light configurations. This image is using  pinpoint docker, pinpoint-collector-agent and pinpoint-php-agent.

https://github.com/pinpoint-apm/pinpoint-docker <br>
https://github.com/pinpoint-apm/pinpoint-c-agent/tree/master <br>
https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/DOC/PHP/Readme.md

### Step 1: Get PinPoint Docker
```
git clone https://github.com/pinpoint-apm/pinpoint-docker.git
cd pinpoint-docker
docker-compose pull && docker-compose up -d
```
Now you can browse into the PinPoint web User Interface. Just type "127.0.0.1:8080" in Browser.
### Step 2: Get PinPoint-Php-Testapp
```
docker pull ...
docker run -itd -p 8000:8000 --name pinpoint-php-testapp --network pinpoint-docker_pinpoint ...
```
### Step 3: Going in the pinpoint-php-testapp container
```
docker exec -it pinpoint-php-testapp bash
```
### Step 4 (Optional): Collector Agent (if you want to have a look or configure the environment variables, you can do it in "~/.bashrc", so for example ```cat ~/.bashrc``` ).
If you have followed the last steps as before without changing anything you can skip this step because then you do not need to change the environment variables.
However, if you change the variables and save, then you must also run<br>
```source ~/.bashrc```
<br>or<br> 
```exit``` and then <br>```docker exec -it pinpoint-php-testapp bash``` for the change to take effect.

### Step 5: Start the Collector Agent:
```
cd /pinpoint-c-agent/collector-agent/
./collector-agent &
```
The above ``&`` means that the collector agent is running in the background. Thus we can continue to work in this terminal.

### Step 6: Get Host IP of the container we are in:<br>
Run
<br>```hostname -I```<br>
and remember the IP which is output

### Step 7: Changing the IP for the pinpoint-php-testapp:
```
cd /pinpoint-c-agent/testapps/PHP/thinkphp/library/think/console/command
nano RunServer.php
``` 
Change in line 25 the IP "172.24.0.12" with the IP of Step 6. If it is the same u can let it.
save and exit by typing "Ctrl+X" and then type "y" and hit the "enter" button.

### Step 8: Finally start the pinpoint-php-Testapp:
```
cd /pinpoint-c-agent/testapps/PHP/
php think run
```
Done

**Comment by eeliu** [comment]
Please create a pull request, thanks again !

**Comment by eeliu** [comment]
fixed by https://github.com/pinpoint-apm/pinpoint-c-agent/tree/dev/testapps#how-to-use-testappsplayground
