### ISSUE TITLE
PHP custom Plugin problem

### ISSUE THREAD

**Issue by CanzumDemir** [pinpoint-apm/pinpoint-c-agent#516]
Hello pinpoint team.
If I add my TestPlugin in the index.php defined plugins folder like this: 
`define('PLUGINS_DIR',__DIR__.'/Plugins/'); `
my plugin does not work. 

But if I create another folder called AutoGen in the Plugins folder like in the testapp and insert my test plugin in the AutoGen folder it works. 

Is this normal or have I misunderstood something because here https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/plugins/PHP/Readme.md in step 5 it just says paste plugin in Plugins source tree and not in Plugins/AutoGen?

**Comment by eeliu** [comment]
please shared your project files.

BYW，if you use tp5, follow https://github.com/pinpoint-apm/pinpoint-c-agent/tree/master/plugins/PHP/Framework/ThinkPHP5

**Comment by CanzumDemir** [comment]
I don't use any framework in my PHP project. I instrument the functions I want to instrument with "///hook...". But the plugin only works if I put it in the /Plugins/AutoGen folder instead of directly in /Plugin.

Here is my example project: 
[test.zip](https://github.com/pinpoint-apm/pinpoint-c-agent/files/11732537/test.zip)
The Plugin is in "application/Plugins/AutoGen" (MyPlugin.php)
and if you move it to
"application/Plugins" and customize the namespace, delete Cache then it is not working

Do I have to use a framework which is supported or have I configured something wrong?

**Comment by eeliu** [comment]
Yes, pinpoint-aop-php does only scan XXXPlugin.php within `AutoGen` folder.  

![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/27064129/1c807f06-814a-417f-b34f-95680be62548)

Sorry, I will update the guide.
