### ISSUE TITLE
php 5.3.3 설치가능한 agent 문의

### ISSUE THREAD

**Issue by pjb1979** [pinpoint-apm/pinpoint-c-agent#521]
php5.3.3

does pinpoint-c-agent 0.1.x  support php5.3.3???

**Comment by eeliu** [comment]
I did not test in php 5.3.3, we are discussing the plan for older version.

**Comment by emeroad** [comment]
https://kinsta.com/blog/php-versions/#php-56-70-71-72-73-and-74-end-of-life

> As of December 31st, 2018, PHP 5.6 also reached its end of life. This officially marks the end of an era for PHP 5, as the first version, 5.0 was launched 14 years ago.

PHP5 has already reached the end of its lifespan in 2018.
We have no plans to support php5.
