### ISSUE TITLE
Hope you can give an example of the usage process

### ISSUE THREAD

**Issue by YZF-Myself** [pinpoint-apm/pinpoint-c-agent#522]
install Pinpoint：
**********
git clone https://github.com/pinpoint-apm/pinpoint-docker.git
cd pinpoint-docker
docker-compose pull && docker-compose up -d
***********

Install Collector Agent
***********
docker run -itd -p 9999:9999  --env-file ./env.list ghcr.io/pinpoint-apm/pinpoint-c-agent/collector-agent:latest
***********
Then I want to monitor the c++ program.
***********
$ mkdir build
$ cd build
$ cmake .. && make 
$ ./test_pinpoint.cpp
***********
I did not modify test_pinpoint.cpp, but I did not find any application on the 8080 page.
Can you give the complete instructions for using the monitoring C++ program started with docker?

**Comment by eeliu** [comment]
please enable agent into debug mode. Set agent_info.inter_flag = 1
```
    PPAgentT agent_info = {
        "tcp:127.0.0.1:9999", 1000, -1, 1700, 1, NULL, NULL, NULL};  
``` 

then, share the output to me.

**Comment by YZF-Myself** [comment]
#include"common.h"
#include"pinpoint_define.h"
#include<iostream>
#include<string>
#include<time.h>
#include<stdlib.h>
#include<unistd.h>


thread_localNodeIDid=E_ROOT_NODE;
constchar*app_id="cpp_test_app";
constchar*app_name="cpp_test_name";


std::stringget_sid()
{
returnstd::to_string(rand() %100000000l);
}


std::stringget_tid()
{
std::stringsid="";
returnsid+app_id+"^"+std::to_string(pinpoint_start_time()) +"^"+std::to_string(generate_unique_id());
}


voidrandom_sleep()
{
int32_tdelay=rand() %10;
usleep(delay*1000);
}


// void test_httpclient()
// {
// id = pinpoint_start_trace(id);
// pinpoint_add_clue(id, PP_INTERCEPTOR_NAME, "httpclient", E_LOC_CURRENT);
// pinpoint_add_clue(id, PP_DESTINATION, "www.pinpoint-wonderful.com", E_LOC_CURRENT);
// pinpoint_add_clue(id, PP_SERVER_TYPE, PP_C_CPP_REMOTE_METHOD, E_LOC_CURRENT);
// pinpoint_add_clue(id, PP_NEXT_SPAN_ID, get_sid().c_str(), E_LOC_CURRENT);
// pinpoint_add_clues(id, PP_HTTP_URL, "/support/c-cpp-php-python", E_LOC_CURRENT);
// pinpoint_add_clue(id, PP_ADD_EXCEPTION, "test this exception", E_LOC_CURRENT);
// pinpoint_add_clues(id, PP_HTTP_STATUS_CODE, "300", E_LOC_CURRENT);


// random_sleep();


// id = pinpoint_end_trace(id);
// }


voidtest_mysql()
{
id=pinpoint_start_trace(id);
pinpoint_add_clue(id, PP_INTERCEPTOR_NAME, "mysql::execute", E_LOC_CURRENT);
pinpoint_add_clue(id, PP_SERVER_TYPE, PP_MYSQL, E_LOC_CURRENT);
//pinpoint_add_clue(id, PP_SQL_FORMAT, "select 1*3;", E_LOC_CURRENT);
pinpoint_add_clue(id, PP_DESTINATION, "127.0.0.1:3306", E_LOC_CURRENT);
random_sleep();
id=pinpoint_end_trace(id);
}


voidtest_req()
{
id=pinpoint_start_trace(id);
pinpoint_add_clue(id, PP_REQ_URI, "test_url", E_LOC_CURRENT);
pinpoint_add_clue(id, PP_REQ_CLIENT, "127.0.0.1", E_LOC_CURRENT);
pinpoint_add_clue(id, PP_REQ_SERVER, "HTTP_HOST", E_LOC_CURRENT);
pinpoint_add_clue(id, PP_SERVER_TYPE, PP_C_CPP, E_LOC_CURRENT);
pinpoint_add_clue(id, PP_INTERCEPTOR_NAME, "C_CPP Request", E_LOC_CURRENT);
pinpoint_add_clue(id, PP_APP_NAME, "cpp_app", E_LOC_CURRENT);
pinpoint_add_clue(id, PP_APP_ID, "CPP_APP", E_LOC_CURRENT);


random_sleep();


test_mysql();
pinpoint_add_clue(id, PP_TRANSCATION_ID, get_tid().c_str(), E_LOC_CURRENT);
pinpoint_add_clue(id, PP_SPAN_ID, get_sid().c_str(), E_LOC_CURRENT);
pinpoint_add_clues(id, PP_HTTP_STATUS_CODE, "200", E_LOC_CURRENT);
catch_error(id, "msg", __FILE__, 100);
id=pinpoint_end_trace(id);
}


intmain(intargc, charconst*argv[])
{
PPAgentTagent_info= {
"tcp:127.0.0.1:19999", 1000, -1, 1700, 1, NULL, NULL, NULL};
global_agent_info=agent_info;
srand(time(nullptr));
inti=0;
for (; i<3; i++)
{
test_req();
sleep(1);
}
return0;
}


log:
pinpoint] [1170125] [1170125] [expandOnce] it's take [0] miliseconds
[pinpoint] [1170125] [1170125]#0 pinpoint_start child #128
[pinpoint] [1170125] [1170125]#128 add clue key:uri value:test_url
[pinpoint] [1170125] [1170125]#128 add clue key:client value:127.0.0.1
[pinpoint] [1170125] [1170125]#128 add clue key:server value:HTTP_HOST
[pinpoint] [1170125] [1170125]#128 add clue key:stp value:1300
[pinpoint] [1170125] [1170125]#128 add clue key:name value:C_CPP Request
[pinpoint] [1170125] [1170125]#128 add clue key:appname value:cpp_app
[pinpoint] [1170125] [1170125]#128 add clue key:appid value:CPP_APP
[pinpoint] [1170125] [1170125]#128 pinpoint_start child #127
[pinpoint] [1170125] [1170125]#127 add clue key:name value:mysql::execute
[pinpoint] [1170125] [1170125]#127 add clue key:stp value:2101
[pinpoint] [1170125] [1170125]#127 add clue key:dst value:127.0.0.1:3306
[pinpoint] [1170125] [1170125]#127 pinpoint_end_trace Done!
[pinpoint] [1170125] [1170125]#128 add clue key:tid value:cpp_test_app^1694051999^51
[pinpoint] [1170125] [1170125]#128 add clue key:sid value:26721516
[pinpoint] [1170125] [1170125]#128 add clues:46:200
[pinpoint] [1170125] [1170125]this span:({"E":5,"ERR":{"file":"/data/pinpoint/pinpoint-c-agent/src/CPP/test_pinpoint.cpp","line":100,"msg":"msg"},"FT":1700,"S":1694158240531,"appid":"CPP_APP","appname":"cpp_app","calls":[{"E":0,"S":5,"dst":"127.0.0.1:3306","name":"mysql::execute","stp":"2101"}],"client":"127.0.0.1","clues":["46:200"],"name":"C_CPP Request","server":"HTTP_HOST","sid":"26721516","stp":"1300","tid":"cpp_test_app^1694051999^51","uri":"test_url"})
[pinpoint] [1170125] [1170125]agent try to connect:(tcp:127.0.0.1:19999)
[pinpoint] [1170125] [1170125]fd 4 send size 429
[pinpoint] [1170125] [1170125]#128 pinpoint_end_trace Done!
[pinpoint] [1170125] [1170125]#0 pinpoint_start child #127
[pinpoint] [1170125] [1170125]#127 add clue key:uri value:test_url
[pinpoint] [1170125] [1170125]#127 add clue key:client value:127.0.0.1
[pinpoint] [1170125] [1170125]#127 add clue key:server value:HTTP_HOST
[pinpoint] [1170125] [1170125]#127 add clue key:stp value:1300
[pinpoint] [1170125] [1170125]#127 add clue key:name value:C_CPP Request
[pinpoint] [1170125] [1170125]#127 add clue key:appname value:cpp_app
[pinpoint] [1170125] [1170125]#127 add clue key:appid value:CPP_APP
[pinpoint] [1170125] [1170125]#127 pinpoint_start child #128
[pinpoint] [1170125] [1170125]#128 add clue key:name value:mysql::execute
[pinpoint] [1170125] [1170125]#128 add clue key:stp value:2101
[pinpoint] [1170125] [1170125]#128 add clue key:dst value:127.0.0.1:3306
[pinpoint] [1170125] [1170125]#128 pinpoint_end_trace Done!
[pinpoint] [1170125] [1170125]#127 add clue key:tid value:cpp_test_app^1694051999^52
[pinpoint] [1170125] [1170125]#127 add clue key:sid value:70359081
[pinpoint] [1170125] [1170125]#127 add clues:46:200
[pinpoint] [1170125] [1170125]this span:({"E":4,"ERR":{"file":"/data/pinpoint/pinpoint-c-agent/src/CPP/test_pinpoint.cpp","line":100,"msg":"msg"},"FT":1700,"S":1694158241536,"appid":"CPP_APP","appname":"cpp_app","calls":[{"E":3,"S":1,"dst":"127.0.0.1:3306","name":"mysql::execute","stp":"2101"}],"client":"127.0.0.1","clues":["46:200"],"name":"C_CPP Request","server":"HTTP_HOST","sid":"70359081","stp":"1300","tid":"cpp_test_app^1694051999^52","uri":"test_url"})
[pinpoint] [1170125] ***@***.*** send data error:(Connection reset by peer) fd:(4)
[pinpoint] [1170125] [1170125]reset peer:4
[pinpoint] [1170125] [1170125]#127 pinpoint_end_trace Done!
[pinpoint] [1170125] [1170125]#0 pinpoint_start child #128
[pinpoint] [1170125] [1170125]#128 add clue key:uri value:test_url
[pinpoint] [1170125] [1170125]#128 add clue key:client value:127.0.0.1
[pinpoint] [1170125] [1170125]#128 add clue key:server value:HTTP_HOST
[pinpoint] [1170125] [1170125]#128 add clue key:stp value:1300
[pinpoint] [1170125] [1170125]#128 add clue key:name value:C_CPP Request
[pinpoint] [1170125] [1170125]#128 add clue key:appname value:cpp_app
[pinpoint] [1170125] [1170125]#128 add clue key:appid value:CPP_APP
[pinpoint] [1170125] [1170125]#128 pinpoint_start child #127
[pinpoint] [1170125] [1170125]#127 add clue key:name value:mysql::execute
[pinpoint] [1170125] [1170125]#127 add clue key:stp value:2101
[pinpoint] [1170125] [1170125]#127 add clue key:dst value:127.0.0.1:3306
[pinpoint] [1170125] [1170125]#127 pinpoint_end_trace Done!
[pinpoint] [1170125] [1170125]#128 add clue key:tid value:cpp_test_app^1694051999^53
[pinpoint] [1170125] [1170125]#128 add clue key:sid value:60580014
[pinpoint] [1170125] [1170125]#128 add clues:46:200
[pinpoint] [1170125] [1170125]this span:({"E":7,"ERR":{"file":"/data/pinpoint/pinpoint-c-agent/src/CPP/test_pinpoint.cpp","line":100,"msg":"msg"},"FT":1700,"S":1694158242540,"appid":"CPP_APP","appname":"cpp_app","calls":[{"E":3,"S":4,"dst":"127.0.0.1:3306","name":"mysql::execute","stp":"2101"}],"client":"127.0.0.1","clues":["46:200"],"name":"C_CPP Request","server":"HTTP_HOST","sid":"60580014","stp":"1300","tid":"cpp_test_app^1694051999^53","uri":"test_url"})
[pinpoint] [1170125] [1170125]agent try to connect:(tcp:127.0.0.1:19999)
[pinpoint] [1170125] [1170125]#128 pinpoint_end_trace Done!


port 3306:
COMMAND       PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
docker-pr 4164915 root    4u  IPv4 401640678      0t0  TCP *:mysql (LISTEN)
docker-pr 4164922 root    4u  IPv6 401643608      0t0  TCP *:mysql (LISTEN)


port 19999:
COMMAND       PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
docker-pr 1159639 root    4u  IPv4 415618227      0t0  TCP *:dnp-sec (LISTEN)
docker-pr 1159646 root    4u  IPv6 415610170      0t0  TCP *:dnp-sec (LISTEN)







在 2023-09-08 14:32:08，"eeliu" ***@***.***> 写道：

please enable agent into debug mode. Set agent_info.inter_flag = 1

    PPAgentT agent_info = {
        "tcp:127.0.0.1:9999", 1000, -1, 1700, 1, NULL, NULL, NULL};  


then, share the output to me.

**Comment by eeliu** [comment]
have you check `127.0.0.1:19999`, was it open ?

```
send data error:(Connection reset by peer) fd:(4) 
``` 

your collect-agent is run by `docker run -itd -p 9999:9999 `, so try 9999

**Comment by YZF-Myself** [comment]
yes , 19999 is opend.I set the port to 19999. Before the modification, the port was 9999, but it was the same error.









在 2023-09-08 15:47:54，"eeliu" ***@***.***> 写道：

have you check 127.0.0.1:19999, was it open ?

send data error:(Connection reset by peer) fd:(4) 


your collect-agent is run by docker run -itd -p 9999:9999 , so try 9999

**Comment by eeliu** [comment]
show docker ps | grep collector-agent

**Comment by YZF-Myself** [comment]
ef718fd3ef88   ghcr.io/pinpoint-apm/pinpoint-c-agent/collector-agent:latest   "CollectorAgent"         49 minutes ago   Up 49 minutes   0.0.0.0:19999->9999/tcp, :::19999->9999/tcp                                                                                                                                                  vigorous_brattain


I also tested to turn off the original agent, and it didn't work.


docker ps:
ef718fd3ef88   ghcr.io/pinpoint-apm/pinpoint-c-agent/collector-agent:latest   "CollectorAgent"         51 minutes ago   Up 51 minutes   0.0.0.0:19999->9999/tcp, :::19999->9999/tcp                                                                                                                                                  vigorous_brattain
301e6430c44d   pinpointdocker/pinpoint-quickstart                             "catalina.sh run"        2 days ago       Up 30 hours     0.0.0.0:8085->8080/tcp, :::8085->8080/tcp                                                                                                                                                    pinpoint-quickstart
699e4f117fd6   pinpointdocker/pinpoint-agent:2.5.2                            "/usr/local/bin/conf…"   2 days ago       Up 2 minutes                                                                                                                                                                                                 pinpoint-agent
06e439817c7a   pinpointdocker/pinpoint-batch:2.5.2                            "sh /pinpoint/script…"   2 days ago       Up 30 hours                                                                                                                                                                                                  pinpoint-batch
58a28dfa1c8e   pinpointdocker/pinpoint-web:2.5.2                              "sh /pinpoint/script…"   2 days ago       Up 30 hours     0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:9997->9997/tcp, :::9997->9997/tcp                                                                                                         pinpoint-web
2cd3372dfeae   pinpointdocker/pinpoint-collector:2.5.2                        "sh /pinpoint/script…"   2 days ago       Up 30 hours     0.0.0.0:9991-9996->9991-9996/tcp, :::9991-9996->9991-9996/tcp, 0.0.0.0:9995-9996->9995-9996/udp, :::9995-9996->9995-9996/udp                                                                 pinpoint-collector
d86ddc10a385   pinpointdocker/pinpoint-flink:2.5.2                            "/docker-bin/docker-…"   2 days ago       Up 30 hours     6123/tcp, 0.0.0.0:6121-6122->6121-6122/tcp, :::6121-6122->6121-6122/tcp, 0.0.0.0:19994->19994/tcp, :::19994->19994/tcp, 8081/tcp                                                             pinpoint-flink-taskmanager
6fc47e5d6033   pinpointdocker/pinpoint-flink:2.5.2                            "/docker-bin/docker-…"   2 days ago       Up 30 hours     6123/tcp, 0.0.0.0:8081->8081/tcp, :::8081->8081/tcp                                                                                                                                          pinpoint-flink-jobmanager
c38715c1ba2b   pinpointdocker/pinpoint-hbase:2.5.2                            "/bin/sh -c '/usr/lo…"   2 days ago       Up 30 hours     0.0.0.0:16010->16010/tcp, :::16010->16010/tcp, 0.0.0.0:16030->16030/tcp, :::16030->16030/tcp, 0.0.0.0:60000->60000/tcp, :::60000->60000/tcp, 0.0.0.0:60020->60020/tcp, :::60020->60020/tcp   pinpoint-hbase
b8529063bc3a   zookeeper:3.4.13                                               "/docker-entrypoint.…"   2 days ago       Up 30 hours     2888/tcp, 3888/tcp, 0.0.0.0:32774->2181/tcp, :::32774->2181/tcp                                                                                                                              pinpoint-docker-zoo3-1
b745dc25cb49   zookeeper:3.4.13                                               "/docker-entrypoint.…"   2 days ago       Up 30 hours     2888/tcp, 3888/tcp, 0.0.0.0:32775->2181/tcp, :::32775->2181/tcp                                                                                                                              pinpoint-docker-zoo1-1
c06215334500   pinpointdocker/pinpoint-mysql:2.5.2                            "docker-entrypoint.s…"   2 days ago       Up 30 hours     0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp                                                                                                                                         pinpoint-mysql
738db9d7ffd6   zookeeper:3.4.13                                               "/docker-entrypoint.…"   2 days ago       Up 30 hours     2888/tcp, 3888/tcp, 0.0.0.0:32776->2181/tcp, :::32776->2181/tcp                                                                                                                              pinpoint-docker-zoo2-1





在 2023-09-08 16:07:42，"eeliu" ***@***.***> 写道：

show docker ps | grep collector-agent

**Comment by eeliu** [comment]
hmm, please show me the log of collector-agent, it locates into /tjmp

![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/27064129/b5e0a2df-05db-4600-a23d-a4e6f8e7c742)

**Comment by YZF-Myself** [comment]
[2023-09-08 07:19:56.457027286]  INFO SocketType:tcp Address:0.0.0.0:19999  StatAddress:dev-pinpoint:9992 SpanAddress:dev-pinpoint:9993 AgentAddressdev-pinpoint:9991 WebPorts:80  LoggerLevel:DEBUG LoggerDir:/tmp/ AgentChannelSize:1000 SpanStreamParallelismSize:2 AgentReTryTimeout:10ns PingInterval:300 StatInterval:5 SpanTimeWaitSec:10 MetaDataTimeWaitSec:10 Pid:0 StartTime:1694157596 ServerType:1700 Container:false
[2023-09-08 07:19:56.458081963] DEBUG listen: tcp address: 0.0.0.0:19999











在 2023-09-08 16:22:20，"eeliu" ***@***.***> 写道：

hmm, please show me the log of collector-agent, it locates into /tmp

**Comment by YZF-Myself** [comment]
port is 9999's result:


[pinpoint] [1211607] [1211607] [expandOnce] it's take [0] miliseconds
[pinpoint] [1211607] [1211607]#0 pinpoint_start child #128
[pinpoint] [1211607] [1211607]#128 add clue key:uri value:test_url
[pinpoint] [1211607] [1211607]#128 add clue key:client value:127.0.0.1
[pinpoint] [1211607] [1211607]#128 add clue key:server value:HTTP_HOST
[pinpoint] [1211607] [1211607]#128 add clue key:stp value:1300
[pinpoint] [1211607] [1211607]#128 add clue key:name value:C_CPP Request
[pinpoint] [1211607] [1211607]#128 add clue key:appname value:cpp_app
[pinpoint] [1211607] [1211607]#128 add clue key:appid value:CPP_APP
[pinpoint] [1211607] [1211607]#128 pinpoint_start child #127
[pinpoint] [1211607] [1211607]#127 add clue key:name value:mysql::execute
[pinpoint] [1211607] [1211607]#127 add clue key:stp value:2101
[pinpoint] [1211607] [1211607]#127 add clue key:dst value:127.0.0.1:3306
[pinpoint] [1211607] [1211607]#127 pinpoint_end_trace Done!
[pinpoint] [1211607] [1211607]#128 add clue key:tid value:cpp_test_app^1694051999^60
[pinpoint] [1211607] [1211607]#128 add clue key:sid value:77923607
[pinpoint] [1211607] [1211607]#128 add clues:46:200
[pinpoint] [1211607] [1211607]this span:({"E":10,"ERR":{"file":"/data/pinpoint/pinpoint-c-agent/src/CPP/test_pinpoint.cpp","line":100,"msg":"msg"},"FT":1700,"S":1694161946996,"appid":"CPP_APP","appname":"cpp_app","calls":[{"E":7,"S":3,"dst":"127.0.0.1:3306","name":"mysql::execute","stp":"2101"}],"client":"127.0.0.1","clues":["46:200"],"name":"C_CPP Request","server":"HTTP_HOST","sid":"77923607","stp":"1300","tid":"cpp_test_app^1694051999^60","uri":"test_url"})
[pinpoint] [1211607] [1211607]agent try to connect:(tcp:127.0.0.1:9999)
[pinpoint] [1211607] [1211607]fd 4 send size 430
[pinpoint] [1211607] [1211607]#128 pinpoint_end_trace Done!
[pinpoint] [1211607] [1211607]#0 pinpoint_start child #127
[pinpoint] [1211607] [1211607]#127 add clue key:uri value:test_url
[pinpoint] [1211607] [1211607]#127 add clue key:client value:127.0.0.1
[pinpoint] [1211607] [1211607]#127 add clue key:server value:HTTP_HOST
[pinpoint] [1211607] [1211607]#127 add clue key:stp value:1300
[pinpoint] [1211607] [1211607]#127 add clue key:name value:C_CPP Request
[pinpoint] [1211607] [1211607]#127 add clue key:appname value:cpp_app
[pinpoint] [1211607] [1211607]#127 add clue key:appid value:CPP_APP
[pinpoint] [1211607] [1211607]#127 pinpoint_start child #128
[pinpoint] [1211607] [1211607]#128 add clue key:name value:mysql::execute
[pinpoint] [1211607] [1211607]#128 add clue key:stp value:2101
[pinpoint] [1211607] [1211607]#128 add clue key:dst value:127.0.0.1:3306
[pinpoint] [1211607] [1211607]#128 pinpoint_end_trace Done!
[pinpoint] [1211607] [1211607]#127 add clue key:tid value:cpp_test_app^1694051999^61
[pinpoint] [1211607] [1211607]#127 add clue key:sid value:87651197
[pinpoint] [1211607] [1211607]#127 add clues:46:200
[pinpoint] [1211607] [1211607]this span:({"E":19,"ERR":{"file":"/data/pinpoint/pinpoint-c-agent/src/CPP/test_pinpoint.cpp","line":100,"msg":"msg"},"FT":1700,"S":1694161948006,"appid":"CPP_APP","appname":"cpp_app","calls":[{"E":9,"S":9,"dst":"127.0.0.1:3306","name":"mysql::execute","stp":"2101"}],"client":"127.0.0.1","clues":["46:200"],"name":"C_CPP Request","server":"HTTP_HOST","sid":"87651197","stp":"1300","tid":"cpp_test_app^1694051999^61","uri":"test_url"})
[pinpoint] [1211607] [1211607]fd 4 send size 430
[pinpoint] [1211607] [1211607]#127 pinpoint_end_trace Done!
[pinpoint] [1211607] [1211607]#0 pinpoint_start child #128
[pinpoint] [1211607] [1211607]#128 add clue key:uri value:test_url
[pinpoint] [1211607] [1211607]#128 add clue key:client value:127.0.0.1
[pinpoint] [1211607] [1211607]#128 add clue key:server value:HTTP_HOST
[pinpoint] [1211607] [1211607]#128 add clue key:stp value:1300
[pinpoint] [1211607] [1211607]#128 add clue key:name value:C_CPP Request
[pinpoint] [1211607] [1211607]#128 add clue key:appname value:cpp_app
[pinpoint] [1211607] [1211607]#128 add clue key:appid value:CPP_APP
[pinpoint] [1211607] [1211607]#128 pinpoint_start child #127
[pinpoint] [1211607] [1211607]#127 add clue key:name value:mysql::execute
[pinpoint] [1211607] [1211607]#127 add clue key:stp value:2101
[pinpoint] [1211607] [1211607]#127 add clue key:dst value:127.0.0.1:3306
[pinpoint] [1211607] [1211607]#127 pinpoint_end_trace Done!
[pinpoint] [1211607] [1211607]#128 add clue key:tid value:cpp_test_app^1694051999^62
[pinpoint] [1211607] [1211607]#128 add clue key:sid value:9163264
[pinpoint] [1211607] [1211607]#128 add clues:46:200
[pinpoint] [1211607] [1211607]this span:({"E":5,"ERR":{"file":"/data/pinpoint/pinpoint-c-agent/src/CPP/test_pinpoint.cpp","line":100,"msg":"msg"},"FT":1700,"S":1694161949025,"appid":"CPP_APP","appname":"cpp_app","calls":[{"E":1,"S":4,"dst":"127.0.0.1:3306","name":"mysql::execute","stp":"2101"}],"client":"127.0.0.1","clues":["46:200"],"name":"C_CPP Request","server":"HTTP_HOST","sid":"9163264","stp":"1300","tid":"cpp_test_app^1694051999^62","uri":"test_url"})
[pinpoint] [1211607] [1211607]fd 4 send size 428
[pinpoint] [1211607] [1211607]#128 pinpoint_end_trace Done!









在 2023-09-08 16:22:20，"eeliu" ***@***.***> 写道：

hmm, please show me the log of collector-agent, it locates into /tmp

**Comment by eeliu** [comment]
From your https://github.com/pinpoint-apm/pinpoint-c-agent/issues/522#issuecomment-1711290974, agent to collector-agent container is ok. 

Please share the logging of  collector-agent. 

```
docker exec -it collector-agent-container /bin/sh
 # tail /tmp/collector.log 
```

**Comment by YZF-Myself** [comment]
[2023-09-08 09:01:12.938232788]  WARN Dail dev-pinpoint:9992 failed err:context deadline exceeded appid=CPP_APP
[2023-09-08 09:01:17.488914211]  WARN connect:dev-pinpoint:9993 failed. context deadline exceeded
[2023-09-08 09:01:17.488932647]  WARN connect:dev-pinpoint:9993 failed. context deadline exceeded
[2023-09-08 09:01:17.941590707] DEBUG connect StatAddress:dev-pinpoint:9992 appid=CPP_APP
[2023-09-08 09:01:22.945718275]  WARN Dail dev-pinpoint:9992 failed err:context deadline exceeded appid=CPP_APP
[2023-09-08 09:01:27.949675236] DEBUG connect StatAddress:dev-pinpoint:9992 appid=CPP_APP
[2023-09-08 09:01:32.491830988]  WARN connect:dev-pinpoint:9993 failed. context deadline exceeded
[2023-09-08 09:01:32.491841706]  WARN connect:dev-pinpoint:9993 failed. context deadline exceeded
[2023-09-08 09:01:32.953624042]  WARN Dail dev-pinpoint:9992 failed err:context deadline exceeded appid=CPP_APP
[2023-09-08 09:01:37.957679091] DEBUG connect StatAddress:dev-pinpoint:9992 appid=CPP_APP











在 2023-09-08 16:55:44，"eeliu" ***@***.***> 写道：

From your #522 (comment), agent to collector-agent container is ok.

Please share the logging of collector-agent.

docker exec -it collector-agent-container /bin/sh
 # tail /tmp/collector.log

**Comment by eeliu** [comment]
dev-pinpoint should be your pinpointdocker/pinpoint-collector:2.5.2 network address. eg: host ip address (192.168.5.3).

Then , restart `collector-agent:latest`

**Comment by YZF-Myself** [comment]
Thanks, it worked！！！











在 2023-09-08 17:16:36，"eeliu" ***@***.***> 写道：

dev-pinpoint should be your pinpointdocker/pinpoint-collector:2.5.2 network address. eg: host ip address (192.168.5.3).

Then , restart collector-agent:latest

**Comment by eeliu** [comment]
close as done
