### ISSUE TITLE
Could this agent support C#/.NET? 

### ISSUE THREAD

**Issue by yaohaizh** [pinpoint-apm/pinpoint-c-agent#564]
Could this agent support C#/.NET platform?  If so, how much cost it would take? Where I can find the starting tech documents if I would like to contribute for .NET platform. 

Thanks for your help a lot.

**Comment by eeliu** [comment]
@yaohaizh 

Hi, I'm glad to hear that you want to contribute for .NET. 
This is the data flow map for pinpoint-c-agent. 
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/27064129/a7a3876b-7e97-441d-8035-d7ad0404a898)
First, understanding the pinpoint-c-agent can help you how to add a new language for pinpoint.  [here is the playground](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/testapps/readme.md).
Second, pinpoint-apm is a distributed, non-intrusive(or less intrusive) and per-request related monitor system. 
So,
- how to support distributed? 
   - https://pinpoint-apm.github.io/pinpoint/1.7.3/techdetail.html#how-traceid-works
-  non-intrusive(or less intrusive)
   - Aspect-oriented programming in c#(.net)
   - libraries: db, mysql, http ......
   - test case: how to verify you intercept works fine
- per-request
  - Binding call trace tree on every request
  - how to handle asynchronous framework ?

Last (but not least), 
- ~pinpoint-c-agent does not fully support windows at this version.( Already in plan )~ supported
- No agent type for C# ( please create a request on [pinppoint-apm/pinpoint](https://github.com/pinpoint-apm/pinpoint/issues/new?assignees=&labels=&projects=&template=feature_request.md )


If you have more questions, please tell us !

Thanks

**Comment by yaohaizh** [comment]
Thanks a lot. This is very helpful and will take a look.
