### ISSUE TITLE
Problem install collector Agent

### ISSUE THREAD

**Issue by CanzumDemir** [pinpoint-apm/pinpoint-c-agent#576]
Hello,
i just tried to install the collector agent.

I did it like explained: https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/DOC/collector-agent/readme.md

1: ```git clone pinpoint-c-agent``` and ```cd collector-agent```
2: next step is command ```make```

Error output after ```make```:
![grafik](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/83336656/6fbe1445-dc91-4f50-96d0-96d3e3b1d76a)

**Comment by eeliu** [comment]
Try this 
`git clone --recurse-submodules https://github.com/pinpoint-apm/pinpoint-c-agent.git `

**Comment by CanzumDemir** [comment]
works now thx

**Comment by CanzumDemir** [comment]
Maybe it helps for other people. Before `make` i did `go build`. Otherwise I get the same error
