### ISSUE TITLE
go build fail

### ISSUE THREAD

**Issue by killen9** [pinpoint-apm/pinpoint-c-agent#579]
[pin@Zenius collector-agent]$ go build
common/config.go:9:2: no required module provides package github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/pinpoint-grpc-idl/proto/v1; to add it:
        go get github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/pinpoint-grpc-idl/proto/v1

build fail

**Comment by eeliu** [comment]
try `git clone --recurse-submodules https://github.com/pinpoint-apm/pinpoint-c-agent.git `

here is the dockerfile for building collector-agent
https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/collector-agent/Dockerfile

**Comment by killen9** [comment]
i'm try git clone --recurse-submodules https://github.com/pinpoint-apm/pinpoint-c-agent.git and go build.
but build fail with same message.
i don't use docker.

**Comment by eeliu** [comment]
try `make`
