### ISSUE TITLE
Anyone available for consultation work for Pinpoint python agent for monitoring Django application

### ISSUE THREAD

**Issue by sanatan90** [pinpoint-apm/pinpoint-c-agent#580]
We are looking for people who can work as consultant for Pinpoint python agent to monitor django application on contract basis. please respond.

**Comment by eeliu** [comment]
Hello, what can I do for you ,just leave the problem. 

I created a gitter room for django; https://matrix.to/#/!kPbsvHFQsaZBNDtlcO:gitter.im?via=gitter.im

**Comment by eeliu** [comment]
ping @sanatan90
