### ISSUE TITLE
send data error:(Broken pipe) fd:(16)

### ISSUE THREAD

**Issue by CanzumDemir** [pinpoint-apm/pinpoint-c-agent#582]
Hello, 
i use "pinpoint-apm/pinpoint-php-aop": "dev-master"
and pinpoint-c-agent v0.4.12.

Im getting this error in pp error log:
`
[27-Feb-2024 15:18:26 Europe/Berlin] [pinpoint] [475017] [475017]_do_write_data@198 send data error:(Broken pipe) fd:(16)
`
I use `@hook` to instrument my functions.

I only get this error for some processes in the project, so not always. For example, I get the error when more than a thousand php methods are called in a request

Collecor Agent config:
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/83336656/dd3c12fb-03ac-4c30-a533-b99faa0677f6)

PHP-Agent:
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/83336656/62739f97-108d-4859-8384-b1bb853ecee4)

pp_error:
it calls add_clue very often and pinpoint_end_trace Done!
this are the last lines of error log
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/83336656/0ee7435e-4bd8-4ff3-b60b-5e6d0382365c)

Is this section enough to possibly find out the problem? I don't know if I am allowed to show the whole pp_error log because of my work.
I can't find anything about this trace in the web UI either, because it's probably not being sent?

**Comment by CanzumDemir** [comment]
This is collector log if i just do the request which cause the error
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/83336656/03208177-547d-4b35-af53-8d669f917bb3)

**Comment by eeliu** [comment]
Thanks your report, I will check this problem.

**Comment by eeliu** [comment]
It was caused from large Span. 

You can add span limitation at collector-agent side by  `collector-agent -RecvBufSize=1048576` (1048576 = 1M)
https://github.com/pinpoint-apm/pinpoint-c-agent/blob/9f3ba08b50a9078b8bb4a5ffe08de585df108e51/DOC/collector-agent/readme.md?plain=1#L38-L39

BTW, we recommend to remove some unimportant traces, a large span leads pinpoint-web very slow.

**Comment by CanzumDemir** [comment]
Hello, i have again a question about this topic. I use the release binary file collector-agent. the newest Version. Is there a way to change the "RecvBufSize" value if i start the c-agent or do i need to modify it in source version and then compile?

For example would this work?:

`./collector-agent.sh -RecvBufSize=<biggerValue> &`

**Comment by eeliu** [comment]
what's "./collector-agent.sh " ? 

```
pinpoint@pinpoint:/workspace$ ./collector-agent --help
Usage of ./collector-agent:
  -RecvBufSize int
        Set recv buf; eg: -RecvBufSize=409600 (default 409600)
```

./collector-agent -RecvBufSize=409600
