### ISSUE TITLE
Is there a thrift version for collector agent

### ISSUE THREAD

**Issue by car1000** [pinpoint-apm/pinpoint-c-agent#587]
The pinpoint protocol we use is thrift, but I see that collector agent uses grpc protocol. What should I do? Is there a thrift protocol version of collect agent

**Comment by eeliu** [comment]
Not support any more 

 https://github.com/pinpoint-apm/pinpoint/issues/9932

**Comment by car1000** [comment]
can you email me your contact details
1548374712@qq.com
