### ISSUE TITLE
[BUG] No call chain when python application call MySql

### ISSUE THREAD

**Issue by mayingping-Bella** [pinpoint-apm/pinpoint-c-agent#589]
## Bug

> what is it ?

 No call chain when python application call MySql

> how to reproduce 

1. call Mysql
2. check Pinpoint Web

![1711530110](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/72844069/f47d73aa-5a12-49b2-b4f3-91fd79192c51)

![1711529667](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/72844069/a753cf55-f39b-47ec-afea-81ff1ac6bbcc)
  
> expected result:

![1711528190](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/72844069/9ad6ff8b-e687-49eb-a626-6d7d3d85e4bc)

**Comment by eeliu** [comment]
fixed
