### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by killen9** [pinpoint-apm/pinpoint-c-agent#596]
> I need some help ...

##############PINPOINT###########################
require_once __DIR__.'/../vendor/autoload.php';
define('APPLICATION_NAME','php');
define('APPLICATION_ID','2');
define('AOP_CACHE_DIR',__DIR__.'/../Cache/');
define('PLUGINS_DIR',__DIR__.'/../Plugins/');
define('PINPOINT_USE_CACHE','YES');
require_once __DIR__.'/../vendor/pinpoint-apm/pinpoint-php-aop/auto_pinpointed.php';
#################################################

collector.log

[2024-04-15 13:56:50.024840042]  INFO client:10.0.0.167:35716 is online
[2024-04-15 13:56:50.024928028]  INFO send handshake msg:{"appid":"no","appname":"no","time":"1713141240"}

 why "appid":"no","appname":"no ?

**Comment by eeliu** [comment]
> why "appid":"no","appname":"no ?

it's an old setting, deprecated now. (agent information can be set at collector-agent side)

**Comment by killen9** [comment]
how setting?

**Comment by killen9** [comment]
Please tell me how to set up the collector-agent.

**Comment by eeliu** [comment]
### collector-agent 

https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/DOC/collector-agent/readme.md

###  php agent

```
define('APPLICATION_NAME','php');
define('APPLICATION_ID','2');
```

**Comment by killen9** [comment]
what?

**Comment by killen9** [comment]
.bash_profile

export PP_COLLECTOR_AGENT_SPAN_IP=127.0.0.1
export PP_COLLECTOR_AGENT_SPAN_PORT=9993
export PP_COLLECTOR_AGENT_AGENT_IP=127.0.0.1
export PP_COLLECTOR_AGENT_AGENT_PORT=9991
export PP_COLLECTOR_AGENT_STAT_IP=127.0.0.1
export PP_COLLECTOR_AGENT_STAT_PORT=9992
export PP_COLLECTOR_AGENT_ISDOCKER=false
export PP_LOG_DIR=/app/pinpoint/logs
export PP_Log_Level=INFO
export PP_ADDRESS=0.0.0.0@9999

php.ini

[pinpoint_php]
extension = pinpoint_php.so
pinpoint_php.CollectorHost = tcp:211.45.120.7:9999
pinpoint_php.SendSpanTimeOutMs = 0
pinpoint_php.TraceLimit = -1
pinpoint_php.DebugReport = true

[error_log]
error_reporting = E_ALL
#log_errors = On
error_log = /var/log/php/php-error.log

common.php

##############PINPOINT###########################
require_once __DIR__.'/../vendor/autoload.php';
define('APPLICATION_NAME','GNB');
define('APPLICATION_ID','2');
define('AOP_CACHE_DIR',__DIR__.'/../Cache/');
define('PLUGINS_DIR',__DIR__.'/../Plugins/');
define('PINPOINT_USE_CACHE','YES');
require_once __DIR__.'/../vendor/pinpoint-apm/pinpoint-php-aop/auto_pinpointed.php';
#################################################

Is it different?

It is not registered on the web and cannot be connected to pinpoint-collector.

**Comment by eeliu** [comment]
Please attach the output of php agent. 

https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/testapps/PHP/php.ini

Does your pinpoint-collector locate at  "PP_COLLECTOR_AGENT_SPAN_IP=127.0.0.1" ?

**Comment by killen9** [comment]
It is installed locally.

**Comment by killen9** [comment]
collector-agent  / pinpoint-collector is installed locally.

**Comment by eeliu** [comment]
> 
> collector.log
> 
> [2024-04-15 13:56:50.024840042] INFO client:10.0.0.167:35716 is online
> [2024-04-15 13:56:50.024928028] INFO send handshake msg:{"appid":"no","appname":"no","time":"1713141240"}
> 
> why "appid":"no","appname":"no ?




> Please tell me how to set up the collector-agent.


it looks collector-agent woks fine.

**Comment by killen9** [comment]
collector.log

[2024-04-15 17:10:43.110591367]  INFO client:127.0.0.1:50806 is online
[2024-04-15 17:10:43.110772605]  INFO send handshake msg:{"appid":"no","appname":"no","time":"1713165831"}
[2024-04-15 17:10:43.111114644]  WARN no FT
[2024-04-15 17:10:43.111140757]  WARN dispather packet with an exception: no FT
[2024-04-15 17:10:43.111154559]  WARN parseInComePacket catches error:no FT,client:127.0.0.1:50806
[2024-04-15 17:10:43.11116987]  INFO connection:127.0.0.1:50806 is shutdown

why isn't registered on the web?

**Comment by eeliu** [comment]
Enable  "log_errors= On " and share us the logging of your php application.
https://github.com/pinpoint-apm/pinpoint-c-agent/blob/1bdfc706adc9cd44e93a9e6b08bd32fe1c6f685b/testapps/PHP/php.ini#L9

**Comment by killen9** [comment]
no logging

**Comment by killen9** [comment]
collector.log

[2024-04-15 17:51:14.645184858]  INFO client:10.0.0.167:60632 is online
[2024-04-15 17:51:14.645371276]  INFO send handshake msg:{"appid":"no","appname":"no","time":"1713171031"}
[2024-04-15 17:51:14.64558775] DEBUG size: 275  packetType: 1 body:{":E":252,":FT":1500,":S":1713171074392,"appid":"php-1","appname":"GNB","client":"192.168.10.20","clues":["46:200"],"name":"PHP Request: fpm-fcgi","server":"10.0.0.167","sid":"1718730853","stp":"1500","tid":"php-1^1713171066709^0","uri":"/gnuboard/bbs/board.php?bo_table=qa"}
[2024-04-15 17:51:14.645708234]  WARN no FT
[2024-04-15 17:51:14.645762668]  WARN dispather packet with an exception: no FT
[2024-04-15 17:51:14.645790138]  WARN parseInComePacket catches error:no FT,client:10.0.0.167:60632
[2024-04-15 17:51:14.645831342]  INFO connection:10.0.0.167:60632 is shutdown

**Comment by eeliu** [comment]
which version you used for php-agent ? you can find it by this file

https://github.com/pinpoint-apm/pinpoint-c-agent/blob/1bdfc706adc9cd44e93a9e6b08bd32fe1c6f685b/src/PHP/php_pinpoint_php.h#L24-L25

**Comment by eeliu** [comment]
> collector.log
> 
> [2024-04-15 17:51:14.645184858] INFO client:10.0.0.167:60632 is online [2024-04-15 17:51:14.645371276] INFO send handshake msg:{"appid":"no","appname":"no","time":"1713171031"} [2024-04-15 17:51:14.64558775] DEBUG size: 275 packetType: 1 body:{":E":252,":FT":1500,":S":1713171074392,"appid":"php-1","appname":"GNB","client":"192.168.10.20","clues":["46:200"],"name":"PHP Request: fpm-fcgi","server":"10.0.0.167","sid":"1718730853","stp":"1500","tid":"php-1^1713171066709^0","uri":"/gnuboard/bbs/board.php?bo_table=qa"} [2024-04-15 17:51:14.645708234] WARN no FT [2024-04-15 17:51:14.645762668] WARN dispather packet with an exception: no FT [2024-04-15 17:51:14.645790138] WARN parseInComePacket catches error:no FT,client:10.0.0.167:60632 [2024-04-15 17:51:14.645831342] INFO connection:10.0.0.167:60632 is shutdown

Try the latest collector-agent .  
docker pull ghcr.io/pinpoint-apm/pinpoint-c-agent/collector-agent:0.5.0

**Comment by killen9** [comment]
#define PHP_PINPOINT_PHP_VERSION "0.2.1"

**Comment by eeliu** [comment]
please update the collector-agent

**Comment by killen9** [comment]
don't go build

[pin@Zenius collector-agent]$ go build
common/config.go:9:2: no required module provides package github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/pinpoint-grpc-idl/proto/v1; to add it:
        go get github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/pinpoint-grpc-idl/proto/v1

**Comment by killen9** [comment]
make error

[pin@Zenius collector-agent]$ make
protoc --go_out=pinpoint-grpc-idl/proto/ --go-grpc_out=pinpoint-grpc-idl/proto  --proto_path=pinpoint-grpc-idl/proto/ --go-grpc_opt=paths=source_relative v1/Annotation.proto v1/Cmd.proto v1/CustomMetric.proto v1/Service.proto v1/Span.proto v1/Stat.proto v1/ThreadDump.proto
google/protobuf/wrappers.proto: File not found.
v1/Annotation.proto: Import "google/protobuf/wrappers.proto" was not found or had errors.
v1/Annotation.proto:15:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:20:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:21:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:26:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:27:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:36:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:47:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:48:5: "google.protobuf.StringValue" is not defined.
make: *** [makefile:8: protoc] Error 1

**Comment by eeliu** [comment]
you missed the submodule

>  git clone --recurse-submodules https://github.com/pinpoint-apm/pinpoint-c-agent.git

**Comment by killen9** [comment]
fail

![사용자 지정 1](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/2e30dfc5-2e70-4cbe-89d0-d4f628ea42fa)

**Comment by eeliu** [comment]
please check the dockerfile of collector-agent
https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/collector-agent/Dockerfile

Script for compile collector-agent
```
...
apk add make protobuf-dev
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
...
```

**Comment by killen9** [comment]
what's mean?

i'm not use docker.

**Comment by killen9** [comment]
[root@Zenius collector-agent]# go build
common/config.go:9:2: no required module provides package github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/pinpoint-grpc-idl/proto/v1; to add it:
        go get github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/pinpoint-grpc-idl/proto/v1

![1](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/a16d8544-9deb-4465-bb20-be9bc16b276f)

**Comment by eeliu** [comment]
please check this https://github.com/pinpoint-apm/pinpoint-c-agent/issues/596#issuecomment-2058263607

**Comment by killen9** [comment]
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/0feb0f33-fdf2-409c-9389-26f06deba8a4)

Dockerfile?

apk?

[root@Zenius collector-agent]# apk add --no-cache make protobuf-dev
bash: apk: command not found...

????

**Comment by killen9** [comment]
I want to install it as server, not as docker

CentOS Linux release 8.5.2111

**Comment by eeliu** [comment]
I tried by docker of centos 8 ,while it's EOL. 

![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/27064129/3f827db0-9dc6-4ef2-ba15-446a12149c3f)

Here is checklist:

- [ ]  go version (1.18)
- [ ]  protoc version (3.6.1)

![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/27064129/52683cff-998e-45da-bc68-86c0ad1badac)

**Comment by killen9** [comment]
[root@Zenius pin]# go version
go version go1.22.0 linux/amd64
[root@Zenius pin]# protoc --version
libprotoc 3.5.0

**Comment by eeliu** [comment]
how about "go install" ? 

(venv) pinpoint@pinpoint:/workspace/collector-agent$ go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go: downloading google.golang.org/protobuf v1.33.0
go: downloading google.golang.org/grpc v1.63.2

**Comment by killen9** [comment]
[root@Zenius app]# go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go: downloading google.golang.org/protobuf v1.33.0
go: downloading google.golang.org/grpc/cmd/protoc-gen-go-grpc v1.3.0
go: downloading google.golang.org/grpc v1.63.2
go: downloading google.golang.org/protobuf v1.28.1

**Comment by killen9** [comment]
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/8e4054cf-ec36-4357-9edd-3062ebc3f4c2)

i think
this link is problem.

![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/9190059d-79ac-410d-b336-3f3f2109290d)

no required module provides package github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/pinpoint-grpc-idl/proto/v1

**Comment by eeliu** [comment]
hmm, how about this command ? 

protoc --go_out=pinpoint-grpc-idl/proto/ --go-grpc_out=pinpoint-grpc-idl/proto  --proto_path=pinpoint-grpc-idl/proto/ --go-grpc_opt=paths=source_relative v1/Annotation.proto v1/Cmd.proto v1/CustomMetric.proto v1/Service.proto v1/Span.proto v1/Stat.proto v1/ThreadDump.proto

**Comment by killen9** [comment]
[root@Zenius collector-agent]# protoc --go_out=pinpoint-grpc-idl/proto/ --go-grpc_out=pinpoint-grpc-idl/proto --proto_path=pinpoint-grpc-idl/proto/ --go-grpc_opt=paths=source_relative v1/Annotation.proto v1/Cmd.proto v1/CustomMetric.proto v1/Service.proto v1/Span.proto v1/Stat.proto v1/ThreadDump.proto
google/protobuf/wrappers.proto: File not found.
v1/Annotation.proto: Import "google/protobuf/wrappers.proto" was not found or had errors.
v1/Annotation.proto:15:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:20:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:21:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:26:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:27:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:36:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:47:5: "google.protobuf.StringValue" is not defined.
v1/Annotation.proto:48:5: "google.protobuf.StringValue" is not defined.

**Comment by eeliu** [comment]
try https://gist.github.com/olivoil/a2e0e4f3427db8b6ef4a6374f9c4cb32

> backup the old one, if you need

**Comment by killen9** [comment]
[root@Zenius collector-agent]# make
protoc --go_out=pinpoint-grpc-idl/proto/ --go-grpc_out=pinpoint-grpc-idl/proto  --proto_path=pinpoint-grpc-idl/proto/ --go-grpc_opt=paths=source_relative v1/Annotation.proto v1/Cmd.proto v1/CustomMetric.proto v1/Service.proto v1/Span.proto v1/Stat.proto v1/ThreadDump.proto
protoc-gen-go: program not found or is not executable
--go_out: protoc-gen-go: Plugin failed with status code 1.
make: *** [makefile:8: protoc] Error 1
[root@Zenius collector-agent]# go build
common/config.go:9:2: no required module provides package github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/pinpoint-grpc-idl/proto/v1; to add it:
        go get github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/pinpoint-grpc-idl/proto/v1
[root@Zenius collector-agent]# protoc --version
libprotoc 3.5.0
[root@Zenius collector-agent]#

**Comment by killen9** [comment]
.bash_profile add

export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOROOT:$GOPATH:$GOBIN

and compile success

**Comment by killen9** [comment]
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/d55c5d61-e20d-4436-9c1d-890293e98231)


![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/1b5359f4-4203-428a-9ddb-cec556d5b2ee)

DB information cannot be retrieved.

**Comment by eeliu** [comment]
which php framework you used ?

**Comment by killen9** [comment]
i'm not used framework.

**Comment by eeliu** [comment]
by the way, which mysql client used?  just pdo ? 

> php-agent does not support c-level plugins yet, if used yii, `\yii\db\Connection` is `JoinPoint`

**Comment by killen9** [comment]
[root@Zenius lib]# pwd
/app/mysql/lib
[root@Zenius lib]# ls
libmariadbclient.a  libmariadb.so  libmariadb.so.3  libmysqlclient.a  libmysqlclient_r.a  libmysqlclient_r.so  libmysqlclient.so  libmysqlservices.a  pkgconfig  plugin

**Comment by killen9** [comment]
why not call tree?

**Comment by killen9** [comment]
my project 
[html.zip](https://github.com/pinpoint-apm/pinpoint-c-agent/files/15019174/html.zip)

**Comment by eeliu** [comment]
As c-level function does not support yet, I will re-implement all plugins to support c-level in future.  

> sorry

**Comment by killen9** [comment]
I don't know how to create a custom plugin.
I'm just an operator, not a developer.
Can you tell me how to set it up?

**Comment by eeliu** [comment]
@killen9  

I find your project does not follow the `psr-4`, that means you can't use this version, even the custom plugin.

> Ref 

- psr-4 https://www.php-fig.org/psr/psr-4/

**Comment by eeliu** [comment]
I tag this issue into next major version.

**Comment by killen9** [comment]
In addition to db information, I also want to display call-tree (trace) information and mem information.
I would appreciate your help.

**Comment by killen9** [comment]
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/0aa0b0f6-3f72-496b-8b2b-5f54aef2ba32)

![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/3464b1b6-5191-4ad9-acf2-16c6b032c431)

![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/5ce682a6-3563-4606-864d-1affe66d1d53)

**Comment by eeliu** [comment]
@killen9  

you can use `Pinpoint\Plugins\Sys\PDO` as your PDO plugins on php. 

Supported list:  
https://github.com/pinpoint-apm/pinpoint-php-aop/tree/dev/lib/Pinpoint/Plugins/Sys

**Comment by killen9** [comment]
How should I apply it?

**Comment by eeliu** [comment]
hmm, I find your project use `mysql_connect` , it's not support any more. 

try use PDO, or mysqli

## Ref

- mysql_connect https://www.php.net/manual/en/function.mysql-connect.php

**Comment by killen9** [comment]
I don't know much about php.
I would appreciate it if you could tell me how to apply it to my project.

**Comment by eeliu** [comment]
OK, 

1. remove deprecated style for handle mysql, use [PDO_MYSQL](https://www.php.net/manual/en/ref.pdo-mysql.php) or [msyqli](https://www.php.net/manual/en/book.mysqli.php) instead.
2. After `1` is done, use pinpoint plugins class to replace PDO_MYSQL or msyqli
  - PDO -> Pinpoint\Plugins\Sys\PDO\PDO
  - mysqli=Pinpoint\Plugins\Sys\mysqli\mysqli

> this older file may help you https://github.com/pinpoint-apm/pinpoint-c-agent/blob/v0.4.10/testapps/PHP/Plugins/setting.ini

**Comment by killen9** [comment]
I deleted the DB and installed mariadb 10.11 using yum.

However, DB information and trace still do not appear.

**Comment by eeliu** [comment]
Which db extension you used ?  PDO or mysqli ?

I will post an example for you.

**Comment by eeliu** [comment]
@killen9 

 I created an example for you. It reveals how to use pinpoint-php

https://github.com/pinpoint-apm/pinpoint-c-agent/blob/2373d7be4dd84ce5fbac5c8bdf4946e8f4f31171/testapps/SimplePHP/run.php#L61-L66


> docker compose up   simple-php

**Comment by killen9** [comment]
sorry. My reply was late due to a business trip.

[root@Zenius ext]# pwd
/usr/include/php/ext
[root@Zenius ext]# ls
date  dom  filter  gd  gmp  hash  iconv  json  libxml  mbstring  mysqli  mysqlnd  pcre  pdo  phar  session  simplexml  sockets  spl  standard  xml

i used mysqli

**Comment by eeliu** [comment]
Please check the exmple in `run.php`.

https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/testapps/SimplePHP/run.php

**Comment by killen9** [comment]
[30-Apr-2024 13:03:57 Asia/Seoul] PHP Warning:  Use of undefined constant PLUGINS_DIR - assumed 'PLUGINS_DIR' (this will throw an Error in a future version of PHP) in /var/www/html/vendor/pinpoint-apm/pinpoint-php-aop/lib/Pinpoint/Common/PinpointDriver.php on line 37
[30-Apr-2024 13:03:57 Asia/Seoul] PHP Warning:  Use of undefined constant PLUGINS_DIR - assumed 'PLUGINS_DIR' (this will throw an Error in a future version of PHP) in /var/www/html/vendor/pinpoint-apm/pinpoint-php-aop/lib/Pinpoint/Common/PinpointDriver.php on line 37
[30-Apr-2024 13:03:57 Asia/Seoul] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'gnuboard'@'localhost' (using password: YES) in /var/www/html/run.php:22
Stack trace:
#0 /var/www/html/run.php(22): mysqli->__construct()
#1 /var/www/html/run.php(36): call_mysqli()
#2 /var/www/html/run.php(39): main()
#3 {main}
  thrown in /var/www/html/run.php on line 22

[run.zip](https://github.com/pinpoint-apm/pinpoint-c-agent/files/15182825/run.zip)

**Comment by eeliu** [comment]
I got your problem, try this version:

"pinpoint-apm/pinpoint-php-aop": "v2.2.0",

> https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/testapps/SimplePHP/composer.json

**Comment by killen9** [comment]
[2024-05-07 14:04:27.805790368]  INFO client:10.0.0.167:45674 is online
[2024-05-07 14:04:27.805922761]  INFO send handshake msg:{"appid":"no","appname":"no","time":"1715058267805","version":"v0.5.0"}
[2024-05-07 14:04:27.806853315] DEBUG size:150  packetType:1 body:{":E":1,":FT":1500,":S":1715058267805,"SQL":"SELECT * FROM g5_login WHERE lo_ip=?","dst":"127.0.0.1 via TCP/IP","name":"Mysqli::prepare","stp":"2101"}
[2024-05-07 14:04:27.806988765]  WARN tid in wrong format
[2024-05-07 14:04:27.807044482]  WARN no appid
[2024-05-07 14:04:27.807077759]  WARN dispatcher packet with an exception: no appid
[2024-05-07 14:04:27.807102949]  WARN parsePacket catches error:no appid,client:10.0.0.167:45674
[2024-05-07 14:04:27.807145559]  INFO connection:10.0.0.167:45674 is shutdown

**Comment by eeliu** [comment]
Did you foget this SimplePHP\RequestPlugin , it looks does not loading. 
Check this source tree : https://github.com/pinpoint-apm/pinpoint-c-agent/tree/dev/testapps/SimplePHP
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/27064129/987a2103-b23d-4b16-83ae-b84edcc3e45f)

**Comment by killen9** [comment]
It has been confirmed that DB information is displayed through SimplePHP.

![1](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/a66b37b6-015c-4f58-8270-e15b3b4e0bd3)
![2](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/af50fb92-200a-4d9f-8ef7-7c3561a30e4f)

But it doesn't appear in my project.
![3](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/160205404/744aeedd-8a72-4a05-a028-c3a843127228)

Do I need other settings?

**Comment by eeliu** [comment]
@killen9 

Hello, `use` is just namespace aliasing. It should be placed at the file which that namespace was used.

```
use_mysqli_file.php
<?php

use Pinpoint\Plugins\Sys\mysqli\Mysqli;

.....

```

### Reference

- Using namespaces: Aliasing/Importing https://www.php.net/manual/en/language.namespaces.importing.php#language.namespaces.importing

**Comment by eeliu** [comment]
ping , please keep it open

**Comment by killen9** [comment]
Sorry, but I'm giving up.

**Comment by eeliu** [comment]
@killen9 

We find a new way to support none framework project by php.it will released it in next month,  please watch this repo.

**Comment by eeliu** [comment]
@killen9  

Hello, the v0.6.0 php agent released. It can support the project without any framework, please have a try. 

## Reference 
- https://github.com/pinpoint-apm/pinpoint-c-agent/releases/tag/v0.6.0
- https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/DOC/PHP/Readme.md

**Comment by eeliu** [comment]
we added an example for pinpoint_php: https://github.com/pinpoint-apm/pinpoint-c-agent/wiki/pinpoint-in-phpmyadmin
