### ISSUE TITLE
need some help. I use pinpointPy==1.2.0, found this: NotImplementedError("set_parent_id")

### ISSUE THREAD

**Issue by wuhaocode** [pinpoint-apm/pinpoint-c-agent#597]
[](url)## Bug

> what is it ?
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/50686070/85e24953-9444-4048-aac0-fc2959fa90
![Snipaste_2024-04-16_15-11-31](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/50686070/d1c5b8bb-03a9-47c8-a3ab-da8fadbc3a12)
e2)

**Comment by eeliu** [comment]
Did you forget set context ?
> if sync python, use  `use_thread_local_context() `

https://github.com/pinpoint-apm/pinpoint-c-agent/blob/1bdfc706adc9cd44e93a9e6b08bd32fe1c6f685b/testapps/PY/app.py#L52-L61

**Comment by wuhaocode** [comment]
ok，thanks
