### ISSUE TITLE
[BUG] PinpointPy error handling

### ISSUE THREAD

**Issue by HJinS** [pinpoint-apm/pinpoint-c-agent#601]
## Bug

> what is it ?
PinpointPy Capture Error(500, 400) as normal request

> how to reproduce 
Rasie Interneal Server Error or another Error at API server with pinpointPy apm

> logging file  attach 
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/33213467/980e85f3-d66c-47de-9ad0-b6aef69786fb)
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/33213467/9b4f1f74-6ef9-45ea-aa52-7070e18cc88a)

**Comment by eeliu** [comment]
Thanks your report, I will fix it.

**Comment by eeliu** [comment]
@HJinS  

If you have any question, feel free to reopen this.

**Comment by eeliu** [comment]
@HJinS 

try `pip install -i https://test.pypi.org/simple/ pinpointPy==1.3.2`
