### ISSUE TITLE
[FEATURE] Support for psycopg2-binary

### ISSUE THREAD

**Issue by HJinS** [pinpoint-apm/pinpoint-c-agent#602]
## Feature
Now I'm using Django, postgreSQL, psycopg2-binary
I have problem using pinpointPy
Can I get support for psycopg2-binary?

> why we need this 

## Discuss 

> I need some help ...

**Comment by eeliu** [comment]
psycopg2-binary already supported,

https://github.com/pinpoint-apm/pinpoint-c-agent/issues/598#issuecomment-2060896810

https://github.com/pinpoint-apm/pinpoint-c-agent/blob/2373d7be4dd84ce5fbac5c8bdf4946e8f4f31171/testapps/django/mysite/polls/views.py#L21C1-L23C56

**Comment by eeliu** [comment]
Can you help me ? 

https://github.com/pinpoint-apm/pinpoint-c-agent/pull/603#pullrequestreview-2024233255

**Comment by HJinS** [comment]
> Can you help me ?
> 
> [#603 (review)](https://github.com/pinpoint-apm/pinpoint-c-agent/pull/603#pullrequestreview-2024233255)

Oh, I'll check again and create new issue if there's problem with it
Thanks for support:)
