### ISSUE TITLE
pinpoint-c-agent arm build

### ISSUE THREAD

**Issue by HJinS** [pinpoint-apm/pinpoint-c-agent#604]
**Is your feature request related to a problem? Please describe.**
I want to run "ghcr.io/pinpoint-apm/pinpoint-c-agent/collector-agent:latest" this image on arm based machine, is there any arm image?

**Describe the solution you'd like**
Support for arm base machine

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by eeliu** [comment]
Got it, I will check the `arm`.

**Comment by eeliu** [comment]
@HJinS 
please try this image

> docker pull ghcr.io/pinpoint-apm/pinpoint-c-agent/collector-agent:dev

**Comment by HJinS** [comment]
> @HJinS 
> 
> please try this image
> 
> 
> 
> > docker pull ghcr.io/pinpoint-apm/pinpoint-c-agent/collector-agent:dev

Thanks:)
