### ISSUE TITLE
How Get TraceId And SpanId In Flask

### ISSUE THREAD

**Issue by quicksandznzn** [pinpoint-apm/pinpoint-c-agent#607]
As title

I want print trace_id in my log

**Comment by quicksandznzn** [comment]
`status, trace_id = get_trace_context().get_parent_id()` right?

**Comment by eeliu** [comment]
> `status, trace_id = get_trace_context().get_parent_id()` right?

`trace_id` will be reused in next span.

You can use below

```
status, trace_id = get_trace_context().get_parent_id()
print( f'transaction id:{pinpoint.get_context(Defines.PP_TRANSCATION_ID,traceId)}') 
```

BUT, watch out the `middleware lifecycle`.

**Comment by quicksandznzn** [comment]
thanks ,
