### ISSUE TITLE
[Python] trace exclude url

### ISSUE THREAD

**Issue by HJinS** [pinpoint-apm/pinpoint-c-agent#609]
**Is your feature request related to a problem? Please describe.**
- health check request uses too many storage of pinpoint server
- If exclude url setting exists, please tell me how

**Describe the solution you'd like**
- Add trace exclude url list(regex or something...)

**Describe alternatives you've considered**
- N/A

**Additional context**
- N/A

Thanks for support:)

**Comment by eeliu** [comment]
hmm, which framework you used ?

**Comment by HJinS** [comment]
> hmm, which framework you used ?

Django

**Comment by eeliu** [comment]
@HJinS 

You can make it by adding a middleware. 

Check changes into this PR: https://github.com/pinpoint-apm/pinpoint-c-agent/pull/610

**Comment by HJinS** [comment]
> @HJinS
> 
> You can make it by adding a middleware.
> 
> Check changes into this PR: #610

Thanks:)
