### ISSUE TITLE
Redis Collections Not release

### ISSUE THREAD

**Issue by quicksandznzn** [pinpoint-apm/pinpoint-c-agent#612]
https://github.com/pinpoint-apm/pinpoint-c-agent/blob/d42524d2b51b9d7de080133b75b7de28c14d81fc/plugins/PY/pinpointPy/libs/_pyRedis/PyRedisPlugins.py#L63

when i use redis pipeline function, this code **pipeLine.connection_pool.get_connection('')** will make new connection, but not release

i change the code to **str(pipeLine)** it's ok

my code 
```

redis_client = redis.Redis(host='127.0.0.1', port=6379,password='123456', db=0)
pipe = redis_client.pipeline(transaction=True)
pipe.get('test_key')
values = pipe.execute()
```

**Comment by eeliu** [comment]
@quicksandznzn 

Thanks your report, we will check this problem.

**Comment by quicksandznzn** [comment]
When will pinpointPy 1.2.1 be released? @eeliu

**Comment by eeliu** [comment]
@quicksandznzn  

Can you help us test it ? 

pip install -i https://test.pypi.org/simple/ pinpointPy==1.3.3

**Comment by quicksandznzn** [comment]
> @quicksandznzn
> 
> Can you help us test it ?
> 
> pip install -i https://test.pypi.org/simple/ pinpointPy==1.3.3

https://github.com/pinpoint-apm/pinpoint-c-agent/blob/469dc3c353d803acc63b3c3955a41dd13521c70c/plugins/PY/pinpointPy/libs/_pyRedis/PyRedisPlugins.py#L65

**pipeLine.connection** is none , because **pipeline.execute** function will releases the connection

https://github.com/redis/redis-py/blob/de8b5709a7d2022deff55034fe7dabc5770225a2/redis/client.py#L1529

maybe use this code
**str(pipeLine.connection_pool)** 
**or**
**str(pipeLine.connection_pool._available_connections[0])**

**Comment by quicksandznzn** [comment]
> > @quicksandznzn
> > Can you help us test it ?
> > pip install -i https://test.pypi.org/simple/ pinpointPy==1.3.3
> 
> https://github.com/pinpoint-apm/pinpoint-c-agent/blob/469dc3c353d803acc63b3c3955a41dd13521c70c/plugins/PY/pinpointPy/libs/_pyRedis/PyRedisPlugins.py#L65
> 
> **pipeLine.connection** is none , because **pipeline.execute** function will releases the connection
> 
> https://github.com/redis/redis-py/blob/de8b5709a7d2022deff55034fe7dabc5770225a2/redis/client.py#L1529
> 
> maybe use this code **str(pipeLine.connection_pool)** **or** **str(pipeLine.connection_pool._available_connections[0])**

i think **str(pipeLine.connection_pool)** is good for me

debug log is 
`add clue key:dst value:ConnectionPool<Connection<host=127.0.0.1,port=6379,db=0>>`

@eeliu

**Comment by eeliu** [comment]
Thanks again, I will dig the source code  more deep.

**Comment by quicksandznzn** [comment]
> Thanks again, I will dig the source code more deep.

Please @ me, if you have any progress .

**Comment by eeliu** [comment]
@quicksandznzn  

please check this https://github.com/pinpoint-apm/pinpoint-c-agent/pull/617

**Comment by eeliu** [comment]
@quicksandznzn 


> @quicksandznzn
> 
> please check this #617

Test version released 

pip install -i https://test.pypi.org/simple/ pinpointPy==1.3.4

**Comment by eeliu** [comment]
Released 

> pip install pinpointPy==1.2.1
