### ISSUE TITLE
PHP Custom/Test Plugin Question

### ISSUE THREAD

**Issue by CanzumDemir** [pinpoint-apm/pinpoint-c-agent#624]
Hello I wanted to ask how to monitor self-defined PHP functions with the current php-aop. 
so far I still know it from the old version as follows, that you write a plugin class,, which is in the defined folder where you save the plugins, e.g. like this
```
///@hook:app\Class:function
 use Pinpoint\Plugins\Common\PinTrace;
 class XXXPlugins extends PinTrace
 {
     public function onBefore(){
         pinpoint_add_clue("stp",PHP_METHOD);
         pinpoint_add_clues(PHP_ARGS,"fetch data from $this->args");
     }

     public function onEnd(&$ret){
         pinpoint_add_clues(PHP_RETURN,"parse data from $ret");
     }

     public function onException($e){
         pinpoint_add_clue("EXP",$e->getMessage());
     }
 }
```

My plugin class looked similar, except that I just collected all my functions that I want to instrument with "///hook...". There must have been over 1000 "///hook" in the class.

I am currently trying to familiarize myself with the new principle like here explained: https://github.com/pinpoint-apm/pinpoint-php-aop?tab=readme-ov-file#2-write-your-plugins

My question is whether this can also be implemented with the new version so that I can instrument all my custom functions as before.
I see that you can no longer use "///hook..."?

**Comment by eeliu** [comment]
hello, `@hook` styled plugin was replaced by  API style.  As a `PP_REQ_PLUGINS` class is a must, we want to make it easy.

https://github.com/pinpoint-apm/pinpoint-php-aop/blob/dcebf0aac0002d7a91f090e5e7bd780c591414cc/lib/Pinpoint/Plugins/Yii2PerRequestPlugins.php#L70-L85

**Comment by eeliu** [comment]
@CanzumDemir  

Hello, please check  [DefaultRequestPlugin.php](https://github.com/pinpoint-apm/pinpoint-php-aop/blob/dev/lib/Pinpoint/Plugins/DefaultRequestPlugin.php) and  [_GuzzleHttp](https://github.com/pinpoint-apm/pinpoint-php-aop/blob/dev/lib/Pinpoint/Plugins/autoload/_GuzzleHttp/__init__.php) for the latest version of pinpoint-php plugins style.

**Comment by CanzumDemir** [comment]
👍

**Comment by CanzumDemir** [comment]
Thanks
