### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by chimaera-code** [pinpoint-apm/pinpoint-c-agent#625]
> what is it ?
cannot connect pinpoint apm to the collector
> how to reproduce 
in an ubuntu ec2 instance I am trying to connect the pinpoint php agent to the pinpoint collector which is also installed in the same ec2 instance, here are the steps taken to install the web and collector to the ec2:

===Update and Install Java 8

sudo apt update
sudo apt-get install openjdk-8-jdk

Verify the installation and set the JAVA_HOME environment variable:

which readlink
java -version
ls -l /usr/lib/jvm/java-8-openjdk-amd64
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
echo $JAVA_HOME
export PATH=$PATH:$JAVA_HOME/bin
echo $PATH
java -version

===Install HBase

Download and extract HBase:

wget https://archive.apache.org/dist/hbase/1.2.7/hbase-1.2.7-bin.tar.gz
tar xzvf hbase-1.2.7-bin.tar.gz

# Link to the extracted directory for convenience
ln -s hbase-1.2.7 hbase

Configure HBase:

vi hbase/conf/hbase-env.sh

# Add the following line:
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

# Comment out the following lines to avoid warnings:
# export HBASE_MASTER_OPTS="$HBASE_MASTER_OPTS -XX:PermSize=128m -XX:MaxPermSize=128m ..."
# export HBASE_REGIONSERVER_OPTS="$HBASE_REGIONSERVER_OPTS -XX:PermSize=128m -XX:MaxPermSize=128m ..."

Start HBase:

hbase/bin/start-hbase.sh

Create a table for Pinpoint data:

# Download script
wget https://raw.githubusercontent.com/pinpoint-apm/pinpoint/master/hbase/scripts/hbase-create.hbase

# Run script
hbase/bin/hbase shell ./hbase-create.hbase

===Install Java 11

Since Pinpoint Agent 2.5.x requires Java 11, install it:

sudo apt install openjdk-11-jdk

# Check installation
java -version

Verify Java 11 installation:

openjdk version "11.0.23" 2024-04-16
OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Ubuntu-1ubuntu1, mixed mode, sharing)

Set the JAVA_HOME environment variable for Java 11 if necessary:

export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
echo $JAVA_HOME

===Install Pinpoint Collector

Download, grant execution permission, and run the Pinpoint Collector:

wget https://github.com/pinpoint-apm/pinpoint/releases/download/v2.5.1/pinpoint-collector-boot-2.5.1.jar
chmod +x pinpoint-collector-boot-2.5.1.jar
nohup java -jar -Dpinpoint.zookeeper.address=localhost pinpoint-collector-boot-2.5.1.jar >/dev/null 2>&1 &

===Install Pinpoint Web

Download, grant execution permission, and run the Pinpoint Web:

wget https://github.com/pinpoint-apm/pinpoint/releases/download/v2.5.1/pinpoint-web-boot-2.5.1.jar
chmod +x pinpoint-web-boot-2.5.1.jar
nohup java -jar -Dpinpoint.zookeeper.address=localhost pinpoint-web-boot-2.5.1.jar >/dev/null 2>&1 &

=========================
and in the same ec2 instance I created a hello world php, here are the steps taken:
sudo apt update
sudo apt install -y nginx php-fpm php-cli composer

===Step 2: Configure Nginx to Use Port 1234

Create a new Nginx server block configuration file:

sudo nano /etc/nginx/sites-available/hello_world

Add the following configuration to the file:

server {
    listen 1234;
    server_name x.x.x.x;

    root /var/www/hello_world/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }
}

Enable the configuration by creating a symbolic link to `sites-enabled`:

sudo ln -s /etc/nginx/sites-available/hello_world /etc/nginx/sites-enabled/

===Step 3: Set Up PHP Project with Composer

Create the project directory and navigate to it:

sudo mkdir -p /var/www/hello_world
cd /var/www/hello_world

Initialize a new Composer project:

composer init --name="hello/world" --description="A simple Hello World app" --require="php:>=8.0" --no-interaction

===Step 4: Create the PHP Application

Create the necessary directories and files:

sudo mkdir -p /var/www/hello_world/public
sudo nano /var/www/hello_world/public/index.php

Add the following PHP code to `index.php`:

php
<?php
echo "Hello, World!";
?>

===Step 5: Adjust Permissions

Ensure that Nginx has the necessary permissions to serve the files:

sudo chown -R www-data:www-data /var/www/hello_world
sudo chmod -R 755 /var/www/hello_world

===Step 6: Restart Nginx

Restart Nginx to apply the changes:

sudo systemctl restart nginx

=========================
and here are the steps taken in installing the pinpoint collector agent also in the same ec2 instance:
#install golang:
sudo apt  install -y golang-go

#install GCC:
sudo apt install gcc

Install the Collector Agent:
export GOBIN=/usr/local/bin/
go install github.com/pinpoint-apm/pinpoint-c-agent/collector-agent@dev

#Set up environment variables: replace 0.0.0.0 with the public IP address of your collector/web EC2 instance. manually pasting or by editing the ~/.bashrc

export PP_COLLECTOR_AGENT_SPAN_IP=0.0.0.0
export PP_COLLECTOR_AGENT_SPAN_PORT=9993
export PP_COLLECTOR_AGENT_AGENT_IP=0.0.0.0
export PP_COLLECTOR_AGENT_AGENT_PORT=9991
export PP_COLLECTOR_AGENT_STAT_IP=0.0.0.0
export PP_COLLECTOR_AGENT_STAT_PORT=9992
export PP_COLLECTOR_AGENT_ISDOCKER=false
export PP_LOG_DIR=/tmp/
export PP_Log_Level=INFO
export PP_ADDRESS=0.0.0.0@9999

#Run the Collector Agent:
/usr/local/bin/collector-agent

#Install the Pinpoint PHP Module, Clone the Pinpoint C Agent repository:
git clone https://github.com/pinpoint-apm/pinpoint-c-agent.git
cd pinpoint-c-agent

## Edit the source file:
nano /opt/pinpoint-c-agent/src/PHP/pinpoint_php.cpp

## Change from:
if (zend_forbid_dynamic_call("pinpoint_get_func_ref_args()") == FAILURE) {

## Change to:
if (zend_forbid_dynamic_call() == FAILURE) {

#Build the pinpoint_php module:
phpize
./configure
make
sudo make install

#Activate the pinpoint_php module in your php.ini file(php version might differ):
sudo nano /etc/php/8.1/fpm/php.ini

#Add the following lines in the end:
extension=pinpoint_php.so
pinpoint_php.CollectorHost=Tcp:0.0.0.0:9999
pinpoint_php.SendSpanTimeOutMs=0
pinpoint_php.TraceLimit=-1
;pinpoint_php.DebugReport=true
;error_reporting = E_ALL
;log_errors = On
;error_log = /tmp/php_fpm_error.log

#Restart PHP-FPM and Nginx(php version might be different):
sudo systemctl restart php8.1-fpm
sudo systemctl restart nginx

#Use Pinpoint PHP Agent
#Add the 'Pinpoint-php-aop' requirement to composer.json:
#change directory to the project first
sudo nano composer.json

#Add the following line under the "require" section:
"pinpoint-apm/pinpoint-php-aop": "v2.1.0"

#it should look something like this:
"require": {
    "php": "^8.1",
    "pinpoint-apm/pinpoint-php-aop": "v2.1.0"
}

#Update Composer dependencies using command:
composer update

#Create the Cache Directory:
sudo mkdir -p /var/www/html/hello-world/Cache

#Assuming that the web server user is www-data, you need to set the ownership of the newly created directory:
sudo chown -R www-data:www-data /var/www/html/hello-world/Cache

#Set Proper Permissions:
sudo chmod -R 755 /var/www/html/hello-world/Cache

#Edit the public/index.php file to add the necessary constants and require the Pinpoint auto script:
nano public/index.php

#Add the following lines at the beginning of the file:
define('APPLICATION_NAME', 'APP-2');
define('APPLICATION_ID', 'app-2');
define('AOP_CACHE_DIR', __DIR__ . '/../Cache/');
require_once __DIR__ . '/../vendor/pinpoint-apm/pinpoint-php-aop/auto_pinpointed.php';

> I need some help ...
I need help/guidance in installing pinpoint apm properly and in connecting the various parts together

**Comment by eeliu** [comment]
@chimaera-code  

 PP_COLLECTOR_AGENT*  should be the address of pinpoint-collector.
