### ISSUE TITLE
<built-in function add_clue> returned a result with an error set

### ISSUE THREAD

**Issue by HJinS** [pinpoint-apm/pinpoint-c-agent#626]
**Describe the bug**
Sometimes, API faile with an error "<built-in function add_clue> returned a result with an error set"
No additional error message or stack trace
Plz help me

Location
**pinpointPy/pinpoint.py in add_trace_header at line 78**
```Python
def end_trace(trace_id: int) -> int:  # -> Any:
    return _pinpointPy.end_trace(trace_id)
def add_trace_header(key: str, value: str, trace_id: int, location: int = 0):
    _pinpointPy.add_clue(key, value, trace_id, location)
def add_trace_header_v2(key: str, value: str, trace_id: int, location: int = 0):
    _pinpointPy.add_clues(key, value, trace_id, location)
```

**To Reproduce**
Steps to reproduce the behavior
No specific reproduce behavior.
- API uses Python requests library(Send Post message)

**Expected behavior**
Successful API request

**Screenshots**
<img width="967" alt="image" src="https://github.com/pinpoint-apm/pinpoint-c-agent/assets/33213467/47f9eb8e-2648-49bb-b67e-1a2e13e042ba">

**Comment by eeliu** [comment]
@HJinS 

Do you know which plugin ?  requests 

Can you share more frames ? 

![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/27064129/d481d17f-5751-4402-8554-441a8a73a776)

**Comment by HJinS** [comment]
> @HJinS
> 
> Do you know which plugin ? requests
> 
> Can you share more frames ?
> 
> ![image](https://private-user-images.githubusercontent.com/27064129/343691612-d481d17f-5751-4402-8554-441a8a73a776.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0Nzc0MzEsIm5iZiI6MTcxOTQ3NzEzMSwicGF0aCI6Ii8yNzA2NDEyOS8zNDM2OTE2MTItZDQ4MWQxN2YtNTc1MS00NDAyLTg1NTQtNDQxYThhNzNhNzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA4MzIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OTViOWMwNjE3Njc0MDRmMGEzNmI4MjhjOTkzYjkzZTM1MWQ4ODIwNTBlMzBmYWEyN2ZiNzI3ZmRjYjlmMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.syRJff-yNGYuN703osy1JkZ1uFjP3gWaNkcM1GpV-3c)

I'm not 100% sure
I think that's RequestPlugin
- My server sends several requests to another server in Loop
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/33213467/834368d4-daea-4a4e-be98-1c917cb4e5c8)

**Comment by eeliu** [comment]
I want to know python server, run in asynchronously or synchronously ? 

PS: do you use aio ?

**Comment by HJinS** [comment]
> I want to know python server, run in asynchronously or synchronously ?
> 
> PS: do you use aio ?

No, uses sync requests library
---
requests==2.32.3

**Comment by eeliu** [comment]
> > I want to know python server, run in asynchronously or synchronously ?
> > PS: do you use aio ?
> 
> ## No, uses sync requests library
> requests==2.32.3

Thanks, 

Can you enable `logging.DEBUG` and share us the logging file. 

>BYW, please remove private information in logging file

```
        set_agent("cd.dev.test.py", "cd.dev.test.py",
                  'tcp:localhost:9999', -1, log_level=logging.DEBUG)
```

>> requests==2.32.3  it's the same in our env

**Comment by HJinS** [comment]
Okay, I need a few days for DEBUG log

+
Here is another trace information
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/33213467/41b1cfba-9676-4788-ba47-50fc641b86ae)

![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/33213467/4a032c19-aeb2-4274-84b0-814067949932)

**Comment by HJinS** [comment]
> > > I want to know python server, run in asynchronously or synchronously ?
> > > PS: do you use aio ?
> > 
> > 
> > ## No, uses sync requests library
> > requests==2.32.3
> 
> Thanks,
> 
> Can you enable `logging.DEBUG` and share us the logging file.
> 
> > BYW, please remove private information in logging file
> 
> ```
>         set_agent("cd.dev.test.py", "cd.dev.test.py",
>                   'tcp:localhost:9999', -1, log_level=logging.DEBUG)
> ```
> 
> > > requests==2.32.3  it's the same in our env

Okay, I need a few days for DEBUG log

+
Here is another trace information
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/33213467/41b1cfba-9676-4788-ba47-50fc641b86ae)

![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/33213467/ec81afd1-868b-4001-b5a7-d2ac1ac73c73)

![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/33213467/4a032c19-aeb2-4274-84b0-814067949932)

![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/33213467/72e51007-4726-4b03-be73-d693e68555cc)

**Comment by eeliu** [comment]
Thanks  @HJinS

**Comment by eeliu** [comment]
@HJinS  which pinpointPy you used ? 

`pip list | grep pinpointPy`

**Comment by HJinS** [comment]
> @HJinS which pinpointPy you used ?
> 
> `pip list | grep pinpointPy`

pinpointPy==1.2.1
Sry for late :)

**Comment by eeliu** [comment]
@HJinS 

Sorry, I did not reproduce this bug in my env. While, I create a patch for you, try to avoiding `sample` and `trace_id` problem. 

> pip install -i https://test.pypi.org/simple/ pinpointPy==1.3.6

Any question, please share to me.

**Comment by HJinS** [comment]
> @HJinS 
> 
> 
> 
> Sorry, I did not reproduce this bug in my env. While, I create a patch for you, try to avoiding `sample` and `trace_id` problem. 
> 
> 
> 
> > pip install -i https://test.pypi.org/simple/ pinpointPy==1.3.6
> 
> 
> 
> Any question, please share to me. 

Thanks for your help😊
I'll test that patch on my env

**Comment by HJinS** [comment]
> Sorry, I did not reproduce this bug in my env. While, I create a patch for you, try to avoiding `sample` and `trace_id` problem.
> 
> > pip install -i https://test.pypi.org/simple/ pinpointPy==1.3.6
> 
> Any question, please share to me.

@eeliu  Is there any plan for releasing this PR?

**Comment by eeliu** [comment]
@HJinS  

I will release `1.3.1` to `pypi` today.

**Comment by HJinS** [comment]
> @HJinS
> 
> I will release `1.3.1` to `pypi` today.

Thanks:)
BWY, I reproduced the bug at my test env.
![image](https://github.com/pinpoint-apm/pinpoint-c-agent/assets/33213467/e75b762b-ce0e-448a-9fb5-17c1d5eff991)

And now I'm testing patch version at my test env.
I'll share the result soon with you

**Comment by eeliu** [comment]
@HJinS  

Can you share your test code ?  

Here is an example for flask, https://github.com/pinpoint-apm/pinpoint-c-agent/tree/dev/testapps/PY

**Comment by HJinS** [comment]
> @HJinS
> 
> Can you share your test code ?
> 
> Here is an example for flask, https://github.com/pinpoint-apm/pinpoint-c-agent/tree/dev/testapps/PY

- Actually, I reproduced End-To-End way. Not a unit test
- I checked no more bug with your test build

**Comment by HJinS** [comment]
> > @HJinS
> > Can you share your test code ?
> > Here is an example for flask, https://github.com/pinpoint-apm/pinpoint-c-agent/tree/dev/testapps/PY
> 
> * Actually, I reproduced End-To-End way. Not a unit test
> * I checked no more bug with your test build

I'll try to write test code, give me a second

**Comment by eeliu** [comment]
Thanks your quickly response !

**Comment by HJinS** [comment]
> Thanks your quickly response !

I couldn't reproduce the error at test env.
I think that's from the complex use of django serializer, transaction, DB query, requests

Actual flow
--> All flows run as sync
> Serializer
>> transaction
>>> child Serailzier(for loop iteration)
>>>> DB query
>>>>> try, except
>>>>> second transaction
>>>>>> DB query
>>>>>> API call(using requests)
>>>>>> some other DB query

**Comment by HJinS** [comment]
> Thanks your quickly response !

@eeliu where can I get change logs or release notes for pinpointPy?

**Comment by eeliu** [comment]
@HJinS 

I already released to pipy. Just re-install pinpointpy

> pip install pinpointPy==1.3.1

**Comment by eeliu** [comment]
@HJinS  

Does your project use Process ?

```
from multiprocessing import Process

def f(name):
    print('hello', name)

if __name__ == '__main__':
    p = Process(target=f, args=('bob',))
    p.start()
    p.join()
```

Hmm, I added more, 

>  I will keep watch this problem in our env. If the `1.3.1` not pass or reproduce again, please share to us.

**Comment by HJinS** [comment]
> @HJinS
> 
> Does your project use Process ?
> 
> ```
> from multiprocessing import Process
> 
> def f(name):
>     print('hello', name)
> 
> if __name__ == '__main__':
>     p = Process(target=f, args=('bob',))
>     p.start()
>     p.join()
> ```
> 
> Hmm, I added more,
> 
> > I will keep watch this problem in our env. If the `1.3.1` not pass or reproduce again, please share to us.

Actually, run API server with process manager(AKA, supervisord)
>>> Thanks

**Comment by eeliu** [comment]
@HJinS 

yes, the pinpointpy is not `fork` safe, we will add more test.

**Comment by HJinS** [comment]
> @HJinS
> 
> I will keep watch this problem in our env. If the 1.3.1 not pass or reproduce again, please share to us.

I checked pinpointPy==1.3.1 does not reproduce the bug at our dev server.
Thanks for your support
