### ISSUE TITLE
[Support] The collector version is 2.5.2 and the protocol is thrift. However, I find that the gRPC protocol is used.

### ISSUE THREAD

**Issue by car1000** [pinpoint-apm/pinpoint-c-agent#631]
The collector uses the 2.5.2 version. The original protocol thrift is still used.

The agent version 0.5.0 uses gRPC. Is there any reference example or the version is changed to the thrift protocol. 0.5.0 this version to change the protocol can still be used after thrift?

**Comment by car1000** [comment]
Which version of pinpoint-c-agent is thrift?

**Comment by car1000** [comment]
pinpoint-c-agent can you give an example of thrift?

**Comment by eeliu** [comment]
@car1000  

https://github.com/pinpoint-apm/pinpoint/issues/9932

**Comment by car1000** [comment]
> @car1000
> 
> [pinpoint-apm/pinpoint#9932](https://github.com/pinpoint-apm/pinpoint/issues/9932)
I understand this 9932, this is to remove the thrift protocol and use gRPC, but we are still using thrift, want to use pinpoint-c-agent this project, currently 0.5.0 can support the thrift protocol, what is the reference, I change the protocol, to make it thrift compatible?

**Comment by car1000** [comment]
I understand this 9932, this is to remove the thrift protocol and use gRPC, but we are still using thrift, want to use pinpoint-c-agent this project, currently 0.5.0 can support the thrift protocol, what is the reference, I change the protocol, to make it thrift compatible?
@eeliu

**Comment by eeliu** [comment]
As for pinpoint-c-agent, we add a protocol adapter (collector-agent).  You do not need to care about  thrift or gprc, it does. 

BYW, pinpoint-c-agent only for python/php, not java.

**Comment by car1000** [comment]
> As for pinpoint-c-agent, we add a protocol adapter (collector-agent). You do not need to care about thrift or gprc, it does.
> 
> BYW, pinpoint-c-agent only for python/php, not java.

Yes, because we were monitoring java projects, now enhance monitoring python projects so use pinpoint-c-agent, a protocol adapter (collector-agent) how is this compatible with thrift protocol in 0.5.0? Can I get a demo?

@eeliu

**Comment by car1000** [comment]
Yes, because we were monitoring java projects, now enhance monitoring python projects so use pinpoint-c-agent, a protocol adapter (collector-agent) how is this compatible with thrift protocol in 0.5.0? Can I get a demo?

@eeliu

**Comment by eeliu** [comment]
@car1000  which framework you use ?


You can get some demo at  https://github.com/pinpoint-apm/pinpoint-c-agent/tree/dev/testapps

**Comment by car1000** [comment]
Sorry, you may have misunderstood. The demo I'm talking about is the 0.5.0 version of pinpoint-c-agent changed to the thrift protocol. I'd like to have an example of this.

@eeliu

**Comment by eeliu** [comment]
Sorry, not support any more

**Comment by car1000** [comment]
Can't the current 0.5.0 be changed to be compatible with thrift protocol?

@eeliu
