### ISSUE TITLE
[SimplePhp] error "Undefined index: weight"

### ISSUE THREAD

**Issue by mayingping-Bella** [pinpoint-apm/pinpoint-c-agent#652]
## Bug

> error "Undefined index: weight"

> start "simple-php "

> `simple-php  | [pinpoint] [1] [1]this span:({":E":2250,":FT":1500,":S":1720752740997,"ERR":{"file":"/workspace/vendor/pinpoint-apm/pinpoint-php-aop/lib/Pinpoint/Plugins/SysV2/_memcached/memcached.php","line":38,"msg":"Undefined index: weight"},"appid":"cd.dev.test.run","appname":"cd.dev.test.php.myp","calls":[{":E":0,":S":95,"SQL":"SELECT * FROM `dept_emp_latest_date` LIMIT 1000;","dst":"dev-mysql","name":"PDO::prepare","stp":"2101"},{":E":397,":S":95,"name":"PDOStatement::execute","stp":"1501"},{":E":0,":S":492,"name":"PDOStatement::fetchAll","stp":"1501"},{":E":0,":S":493,"name":"PDOStatement::fetch","stp":"1501"},{":E":0,":S":493,"SQL":"SELECT dept_no, dept_name FROM departments ORDER BY dept_name LIMIT 5","dst":"dev-mysql","name":"PDO::query","stp":"2101"},{":E":403,":S":495,"SQL":"SELECT * FROM `dept_emp_latest_date` LIMIT 1000;","dst":"dev-mysql via TCP/IP","name":"mysqli::query","stp":"2101"},{":E":1,":S":898,"SQL":"SELECT * FROM employees WHERE emp_no=?","dst":"dev-mysql via TCP/IP","name":"mysqli::prepare","stp":"2101"},{":E":0,":S":899,"name":"mysqli_stmt::execute","stp":"1501"},{":E":0,":S":899,"name":"mysqli_stmt::fetch","stp":"1501"},{":E":386,":S":899,"SQL":"SELECT * FROM `dept_emp_latest_date` LIMIT 1000;","dst":"dev-mysql via TCP/IP","name":"mysqli_query","stp":"2101"},{":E":0,":S":1285,"SQL":"SELECT * FROM employees WHERE emp_no=?","dst":"dev-mysql via TCP/IP","name":"mysqli_prepare","stp":"2101"},{":E":0,":S":1285,"name":"mysqli_stmt_bind_param","stp":"1501"},{":E":0,":S":1285,"name":"mysqli_stmt_execute","stp":"1501"},{":E":1,":S":1287,"SQL":"SELECT * FROM `contacts` LIMIT 1000;","dst":"dev-mariadb via TCP/IP","name":"mysqli::query","stp":"2101"},{":E":0,":S":1288,"SQL":"INSERT INTO contacts (name,age,email) VALUES(?, ?, ?)","dst":"dev-mariadb via TCP/IP","name":"mysqli::prepare","stp":"2101"},{":E":2,":S":1288,"name":"mysqli_stmt::execute","stp":"1501"},{":E":13,":S":1315,"dst":"m","name":"MongoDB\\Client::__construct","stp":"2651"},{":E":16,":S":1347,"clues":["dst:{\"foo\":\"bar\"}"],"name":"MongoDB\\Collection::insertOne","stp":"2651"},{":E":578,":S":1395,"clues":["40:http://httpbin.org/anything","-1:http://httpbin.org/anything","46:200"],"dst":"httpbin.org","name":"curl_exec","nsid":"1370603461","stp":"9700"},{":E":267,":S":1973,"clues":["40:http://httpbin.org/get","-1:http://httpbin.org/get","46:200"],"dst":"httpbin.org","name":"curl_exec","nsid":"1370603461","stp":"9700"},{":E":0,":S":2240,"name":"curl_close","stp":"1501"},{":E":1,":S":2243,"clues":["-1:a"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::get","stp":"8200"},{":E":0,":S":2244,"clues":["-1:a"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::set","stp":"8200"},{":E":0,":S":2244,"clues":["-1:a"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::setNx","stp":"8200"},{":E":1,":S":2244,"clues":["-1:ar"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::append","stp":"8200"},{":E":0,":S":2245,"clues":["-1:ar"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::setRange","stp":"8200"},{":E":0,":S":2245,"clues":["-1:ar"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::get","stp":"8200"},{":E":0,":S":2245,"clues":["-1:ar"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::getRange","stp":"8200"},{":E":0,":S":2245,"clues":["-1:ar"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::strlen","stp":"8200"},{":E":1,":S":2245,"clues":["-1:ar"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::getBit","stp":"8200"},{":E":0,":S":2246,"clues":["-1:ar"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::setBit","stp":"8200"},{":E":0,":S":2246,"clues":["-1:ar"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::get","stp":"8200"},{":E":0,":S":2246,"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::mSet","stp":"8200"},{":E":1,":S":2246,"clues":["-1:key1"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::set","stp":"8200"},{":E":0,":S":2247,"clues":["-1:key1"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::get","stp":"8200"},{":E":0,":S":2247,"clues":["-1:key2"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::set","stp":"8200"},{":E":0,":S":2247,"clues":["-1:key2"],"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::get","stp":"8200"},{":E":0,":S":2247,"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::exec","stp":"8200"},{":E":1,":S":2247,"dst":"redis(host=redis,port=6379,db=0)","name":"Redis::exists","stp":"8200"},{":E":1,":S":2248,"clues":["-1:key"],"dst":"memcached(host=memcached,port=11211,weight=)","name":"Memcached::set","stp":"8050"},{":E":0,":S":2249,"clues":["-1:key"],"dst":"memcached(host=memcached,port=11211,weight=)","name":"Memcached::get","stp":"8050"},{":E":1,":S":2249,"clues":["-1:test_add"],"dst":"memcached(host=memcached,port=11211,weight=)","name":"Memcached::add","stp":"8050"},{":E":0,":S":2250,"dst":"memcached(host=memcached,port=11211,weight=)","name":"Memcached::deleteMulti","stp":"8050"}],"name":"PHP Request: cli","server":"ece5b0230f55[pid:1]","sid":"1763287142","stp":"1500","tid":"cd.dev.test.run^1720752740856^0","uri":"/workspace/run.php"})`
## Feature

> 
![1721004535](https://github.com/user-attachments/assets/395bc190-6e64-4938-addd-55a156e85a1a)
![1721004554](https://github.com/user-attachments/assets/f11d06f8-b594-4482-9f15-06dae94e9d1d)

## Discuss 

> I need some help ...

**Comment by eeliu** [comment]
fixed by https://github.com/pinpoint-apm/pinpoint-php-aop/releases/tag/v3.0.6

**Comment by mayingping-Bella** [comment]
test passed
![1721008739](https://github.com/user-attachments/assets/29571fba-7247-46cc-ad99-b833987240f2)
