### ISSUE TITLE
[Support] Does pinpoint-c-agent 0.6.0 support pinpoint 2.5.2?

### ISSUE THREAD

**Issue by car1000** [pinpoint-apm/pinpoint-c-agent#654]
I see a lot of difference in changes between pinpoint-c-agent 0.6.0 and 0.5.0. We are using pinpoint 2.5.2. Which version of pinpoint-c-agent should I use?

**Comment by eeliu** [comment]
@car1000  

Hello, sorry to late response.

pinpoint-c-agent is a collection of agents, including c/cpp, php, py,pinpoint-collector agent. `0.6.0` is the name for all. 

eg: 
- If your agent is py, the latest is `1.3.1` (https://pypi.org/project/pinpointPy/) 
- if php, try https://pecl.php.net/package/pinpoint_php (in progress, while you can get by [install_ext-pinpoint_php](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/DOC/PHP/Readme.md#steps) ) 

As for pinpoint version, we will keep peace with pinpoint release. While some metric are not support, py/php agent does not implemented. 

> if you find some compatible problems, feel free to open an issue.

**Comment by car1000** [comment]
ttps://github.com/pinpoint-apm/pinpoint-c-agent/tree/v0.6.0
https://github.com/pinpoint-apm/pinpoint-c-agent/tree/v0.5.0
I mean do both of the above support pinpoint 2.5.2?

https://github.com/pinpoint-apm/pinpoint/tree/v2.5.2

Thank you.
@eeliu

**Comment by car1000** [comment]
@eeliu hello

**Comment by eeliu** [comment]
hi @car1000  
which agent (php,python ) used ?

**Comment by car1000** [comment]
@eeliu we use python

**Comment by car1000** [comment]
> @eeliu we use python

@eeliu hello, Help me see.

**Comment by car1000** [comment]
@eeliu hello, Can you give me an answer?
thanks

**Comment by eeliu** [comment]
Sorry for late response,

In python, `pip install pinpointPy` .

https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/DOC/PY/Readme.md

As you pointed the version v0.5 and v0.6: no need to care about it, just `pinpointPy` version.   (https://pypi.org/project/pinpointPy/)

> v0.6.x : big changes in PHP. 



------------------------------------
> @car1000
> 
> Hello, sorry to late response.
> 
> pinpoint-c-agent is a collection of agents, including c/cpp, php, py,pinpoint-collector agent. `0.6.0` is the name for all.
> 
> eg:
> 
> * If your agent is py, the latest is `1.3.1` (https://pypi.org/project/pinpointPy/)
> * if php, try https://pecl.php.net/package/pinpoint_php (in progress, while you can get by [install_ext-pinpoint_php](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/DOC/PHP/Readme.md#steps) )
> 
> As for pinpoint version, we will keep peace with pinpoint release. While some metric are not support, py/php agent does not implemented.
> 
> > if you find some compatible problems, feel free to open an issue.
