### ISSUE TITLE
PHP: bad License in package.xml

### ISSUE THREAD

**Issue by remicollet** [pinpoint-apm/pinpoint-c-agent#656]
package.xml states 

`<license uri="http://www.php.net/license">PHP</license>`

LICENSE file is "Apache-2.0"

Please fix package.xml for consistency

**Comment by remicollet** [comment]
Notice: it will be nice to have the package.xml file stored in git repository so we can open PR for it

Also nice a have changelog inside the package.xml
so useful information will be found at https://pecl.php.net/package-changelog.php?package=pinpoint_php

**Comment by eeliu** [comment]
@remicollet 

 Got it, I will change them.

**Comment by eeliu** [comment]
@remicollet 

Can you help me , how to upload windows .dll into pecl.php.net ?  

https://github.com/eeliu/pinpoint-c-agent/actions/runs/10141196543#artifacts


![image](https://github.com/user-attachments/assets/97ef27d4-8092-4105-b128-c0e9c4ab039e)


## For `pecl`, only a `upload` button for these files 

![image](https://github.com/user-attachments/assets/702d4cc0-fa16-42af-827d-406ac479137c)
## But I want to release these .dll as [redis](https://pecl.php.net/package/redis)
![image](https://github.com/user-attachments/assets/0febb53a-02b7-4b40-9efe-0aee23c4f41a)

**Comment by remicollet** [comment]
> Can you help me , how to upload windows .dll into pecl.php.net ?

Sorry, no, I don't know anything about Windows

Perhaps @cmb69 may help

**Comment by eeliu** [comment]
@remicollet  

Thanks all the same

**Comment by cmb69** [comment]
See https://news-web.php.net/php.pecl.dev/17597.

**Comment by eeliu** [comment]
@cmb69  Thanks 

But my problems is how to upload these compiled binary package into  `pecl.php.net` like `phpredis dll`.

> I already got an account.

**Comment by cmb69** [comment]
> But my problems is how to upload these compiled binary package into `pecl.php.net` like `phpredis dll`.

You are not supposed to do this. Instead, make that package buildable on Windows first. While there is a config.m4, there is no config.w32, which is a first requirement to build the extension on Windows.

**Comment by cmb69** [comment]
Ah, I've just noticed that there is a config.w32 in the PECL package (but apparently that is missing from this repo), and did a quick test build without any issues. Therefore I requested https://github.com/php/php-windows-builder/issues/3#issuecomment-2260279730, so that the DLLs can be built, and uploaded.

**Comment by cmb69** [comment]
The [DLLs are available now](https://pecl.php.net/package/pinpoint_php), thanks to @shivammathur.

**Comment by eeliu** [comment]
@cmb69  @smalltangcai @remicollet 

Thanks your help !

I have another question: can those .dll be uploaded automatically, what should I do when create a new release ?

**Comment by shivammathur** [comment]
@eeliu We are doing PECL builds for Windows currently, so when you add a new release, the DLLs will be added. Feel free to reach out if there is a delay.

**Comment by eeliu** [comment]
it looks ok to close 

thanks again
