### ISSUE TITLE
[Support]  About postgresql transaction

### ISSUE THREAD

**Issue by loy124** [pinpoint-apm/pinpoint-c-agent#682]
`
def monkey_patch_for_pinpoint(pymongo=True,
                              PyMysql=True,
                              pyRedis=True,
                              requests=True,
                              urllib=True,
                              sqlalchemy=True,
                              MySQLdb=True,
                              MysqlConnector=True,
                              pyscopg2=True):
    __monkey_patch(_pymongo=pymongo, _MySQLdb=MySQLdb, _PyMysql=PyMysql, _pyRedis=pyRedis, _requests=requests,
                   _urllib=urllib, _sqlalchemy=sqlalchemy,   _MysqlConnector=MysqlConnector, _psycopg2=pyscopg2)
`

[https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/plugins/PY/pinpointPy/libs/__init__.py](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/dev/plugins/PY/pinpointPy/libs/__init__.py)

When looking at the code defined in that address, it is confirmed that there are no postgresql-related settings.
It is confirmed that only mysql related settings are visible.
pinpoint in django Is it impossible to look up postgresql transaction?

**Comment by eeliu** [comment]
@loy124  

hello, did you mean this library ? 

https://postgres-py.readthedocs.io/en/latest/

if not, please share your postgresql client library.

**Comment by mincoding-onyou** [comment]
@eeliu 
oh i use psycopg2-binary

**Comment by loy124** [comment]
@eeliu
i use psycopg2-binary 2.9.2 version

**Comment by eeliu** [comment]
What's your "postgresql transaction" meaning ?  

Is it  "transaction Per Second" in  Inspector View ?

![image](https://github.com/user-attachments/assets/1c2717cd-539a-412a-a7e0-b2a7965f4e8b)

`pyscopg2`  already supported. 

> it is confirmed that there are no postgresql-related settings.

What are settings you want to use ? I'm confusing 😕

**Comment by loy124** [comment]
@eeliu

Oh, I was using pinpointPy 1.1.0. 
I updated the version and it worked.

thank you
