### ISSUE TITLE
[Support] Does Python support call frequency, traffic limiting, and sampling rate?

### ISSUE THREAD

**Issue by car1000** [pinpoint-apm/pinpoint-c-agent#683]
pip install pinpointPy
Does this support call frequency, traffic limiting, and sampling rate?

I can see the related configuration in the agent of Java, such as profiler.sampling.percent.sampling-rate and profiler.sampling.counting.sampling-rate.

https://github.com/pinpoint-apm/pinpoint/blob/master/agent-module/agent/src/main/resources/profiles/local/pinpoint.config#L66C1-L66C43

What do we do in python if we want to set the relevant configuration?

**Comment by eeliu** [comment]
for pinpointpy,does not support `profiler.sampling.percent.sampling-rate`

as for `profiler.sampling.counting.sampling-rate` 

Try `trace_limit`: counting per second. 

https://github.com/pinpoint-apm/pinpoint-c-agent/blob/c35232017d1f2eb79e65373fda556638c7cf7d09/plugins/PY/pinpointPy/pinpoint.py#L122

BTW, `trace_limit` is process scope variable.

**Comment by car1000** [comment]
What does time_out mean? What does time_out: int = 0 mean?
@eeliu

**Comment by eeliu** [comment]
time_out ： max time out when sending a span.

If your script is run and exit, like db backup, crontab job, set time_out > 0 (1), or else  set time_out = 0.
