### ISSUE TITLE
Cannot install pinpointPy 1.3.2 on python3.7

### ISSUE THREAD

**Issue by donemin** [pinpoint-apm/pinpoint-c-agent#701]
## Bug

> what is it ?

Cannot install pinpoint 1.3.2 on python 3.7

> how to reproduce 

add `pinpointPy` in `requirements.txt` and run`pip install -r requirements.txt"

> logging file  attach 

```
Collecting pinpointPy
Downloading pinpointpy-1.3.2.tar.gz (114 kB)


ERROR: Command errored out with exit status 1: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n53mhaw6/pinpointpy_ae1de94f43104275b980dbbb662ed631/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n53mhaw6/pinpointpy_ae1de94f43104275b980dbbb662ed631/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zmm9_18_/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/pinpointPy Check the logs for full command output.
ERROR: process "/bin/sh -c pip3 install -r requirements.txt" did not complete successfully: exit code: 1

Running setup.py install for pinpointPy: started
Running setup.py install for pinpointPy: finished with status 'error'
```

It works when pinpointPy version changed to 1.3.1

**Comment by eeliu** [comment]
@donemin 

Can you share your OS version ?

**Comment by donemin** [comment]
@eeliu 
using `centos7.5.1804`. pretty old. 😢

**Comment by eeliu** [comment]
I tested in `python:3.7` , it's ok under g++ compiler. 

`docker run --rm -it  centos:centos7.5.1804` , it's EOL, I tried, but failed to install python3.7.  

Do you have some out-of-box image ?

**Comment by eeliu** [comment]
I tested in a lower version 3.6.7 

```
   /gcc/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/tmp/pip-build-gtajkssv/pinpointpy/common/include -I/tmp/pip-build-gtajkssv/pinpointpy/common/jsoncpp/include -I/tmp/pip-build-gtajkssv/pinpointpy/common/src -I/usr/include/python3.6m -c src/PY/_pinpoint_py.cpp -o build/temp.linux-x86_64-3.6/src/PY/_pinpoint_py.o -std=c++11
    src/PY/_pinpoint_py.cpp:18:10: fatal error: Python.h: No such file or directory
       18 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command '/gcc/bin/gcc' failed with exit status 1
    
```

if you got the same error, try https://stackoverflow.com/a/21530768

**Comment by donemin** [comment]
Also can see `Using legacy 'setup.py install' for pinpointPy, since package 'wheel' is not installed.` in build log.

should I install wheel? 
No problems when I set pinpointPy version to 1.3.1 instead not figured version.

in requirements.txt
```
pinpointPy==1.3.1
```

**Comment by eeliu** [comment]
@donemin  Maybe I confused you question, 

the latest is 1.3.2. 

You are right, our wheels are distributed by [cibuildwheel](https://github.com/pypa/cibuildwheel). It skipped some versions according  to [python  status](https://devguide.python.org/versions/)
