### ISSUE TITLE
can we use php-5.6.31-centos-6.x-release-pinpoint.so directly

### ISSUE THREAD

**Issue by linuxmyjob** [pinpoint-apm/pinpoint-c-agent#89]
hello,i saw php-5.6.31-centos-6.x-release-pinpoint.so,can we use it

**Comment by ChenGXQQ** [comment]
Theoretically yes. But I highly recommand to compile at your servers. It will avoid some weird errors.

**Comment by linuxmyjob** [comment]
hello, according you said i compiled it ,but when i compiled thrift ,an error is exposed:
cc1plus: warning: unrecognized command line option "-Wno-c++11-long-long"
make[4]: *** [src/thrift/async/libthriftnb_la-TEvhttpServer.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
cc1plus: warning: unrecognized command line option "-Wno-c++11-long-long"
make[4]: *** [src/thrift/async/libthriftnb_la-TEvhttpClientChannel.lo] Error 1
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I../../lib/cpp/src/thrift -I../../lib/c_glib/src/thrift -I/web/pinpoint-c-agent/thirdparty/var/include -I./src -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -pedantic -g -O2 -Wno-variadic-macros -Wno-long-long -Wno-c++11-long-long -MT src/thrift/transport/libthriftz_la-TZlibTransport.lo -MD -MP -MF src/thrift/transport/.deps/libthriftz_la-TZlibTransport.Tpo -c src/thrift/transport/TZlibTransport.cpp -o src/thrift/transport/libthriftz_la-TZlibTransport.o >/dev/null 2>&1
mv -f src/thrift/transport/.deps/libthriftz_la-TZlibTransport.Tpo src/thrift/transport/.deps/libthriftz_la-TZlibTransport.Plo
make[4]: Leaving directory `/web/pinpoint-c-agent/thirdparty/thrift/lib/cpp'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/web/pinpoint-c-agent/thirdparty/thrift/lib/cpp'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/web/pinpoint-c-agent/thirdparty/thrift/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/web/pinpoint-c-agent/thirdparty/thrift'
make: *** [all] Error 2

**Comment by linuxmyjob** [comment]
my gcc version is  :


gcc-c++-4.4.7-23.el6.x86_64
libgcc-4.4.7-23.el6.x86_64
gcc-4.4.7-23.el6.x86_64
 is it the gcc version problem?
